### ISSUE TITLE
Remove all orphan episodes with filesize zero

### ISSUE THREAD

**Issue by Invictaz** [PodcastGenerator/PodcastGenerator#155]
Sometimes I move the files after upload to a different directory. 
However, files remain in the database but cannot be downloaded.
There is no option to purge these empty entries (as they are 0 mb). 

I'm now using an external upload script but hopefully I can manage my list of episodes much faster when this request is fulfilled.

**Comment by emilengler** [comment]
Do you move the audio files or just the XML file or both?
Deleting the audio and the XML file should be enough.
Maybe changing the upload directory in `config.php` is an option as well

**Comment by Invictaz** [comment]
Only the audio files with a cron job. Deleting the audio does keep the XML files. 
I don't have a Cron job yet to delete all XML files

**Comment by emilengler** [comment]
The XML files are the files who matter actually. Just delete them instead of the audio files. Or delete both which is best. If you only delete the XML, they will get regenerated every time you use the FTP feature
