### ISSUE TITLE
Podcast Generator 3.1

### ISSUE THREAD

**Issue by emilengler** [PodcastGenerator/PodcastGenerator#157]
**The release date will be 2020-05-31**

As I want to make the development very transparent, I would like to have an issue related to the upcoming version.

If you want to submit a feature idea, please write it in the comments or open a separate issue. We will discuss it then and if it gets support, I will include it in the list below:

The development happens in the master branch!

## Upcoming features
* Podcast Generator Admin API (This would allow in theory the Creation of Podcast Generator apps for the admin interface) (Suggested by @emilengler)
* Multi-User support (The upcoming release will have support for multiple user accounts for the admin area instead of just one) (Suggested by @emilengler).
* Option to change the name of index.php (Suggested by @Invictaz).
* Upload episode by link (Suggested by @rebelojose, #29)
* Your idea?

**Comment by cacatuafm** [comment]
I would like him to have a small comment box from the listener. What do you think about the episode. with function of activating it or not.

**Comment by emilengler** [comment]
Multi-User System is done. Now I need a GUI to create and delete users

**Comment by alwa** [comment]
A suggestion: Advanced editing of iTunes metadata tags:

https://blog.pacific-content.com/its-the-one-year-anniversary-of-apple-s-new-podcast-tags-bf8487e4d19a

In particular

```
<itunes:type> (episodic or serial)
<itunes:season> for season numbers
<itunes:episode> for episode numbers
<itunes:episodeType> (full, trailer, or bonus)
```

**Comment by joerg-nafcom** [comment]
another suggestion: Allowing setting "Home" navigation link destination. e.g. in our case I would like it to be https://sceneworld.org/ and not the default https://sceneworld.org/history/index.php?

**Comment by emilengler** [comment]
@joerg-nafcom You can already do this:

Edit Line 11 in `themes/default/navbar.php`
There edit it to
```
                <a class="nav-link" href="https://sceneworld.org">Home</a>
```

**Comment by Invictaz** [comment]
@joerg-nafcom @emilengler Could that be a selectablle option in the config?

**Comment by emilengler** [comment]
Btw 3.0.1 is out now.

@Invictaz Yes

**Comment by joerg-nafcom** [comment]
> @joerg-nafcom You can already do this:
> 
> Edit Line 11 in `themes/default/navbar.php`
> There edit it to
> 
> ```
>                 <a class="nav-link" href="https://sceneworld.org">Home</a>
> ```

Thanks, this worked! I also vote for it being an option in the theme settings in the admin menu. will this be a feature of 3.1 for May? :)

**Comment by emilengler** [comment]
Ok, will add this :)

**Comment by emilengler** [comment]
Looks like 3.1 already has something similar called `$indexfile`. You can enter an absolute url there.

**Comment by ryangurn** [comment]
@emilengler Is there a specific reason the information is not being saved to a database of some sort, opting for using MySQL/noSQL/etc?

**Comment by emilengler** [comment]
@ryangurn Yes!
I also hate to work with text files but there's reason for it.
Back in 2006 when Podcast Generator was first released databases were pretty uncommon and very expensive. This was kept over the years. To allow backwards compatibility I decided to also rely on text files when I rewrote it in late 2019. However I'm looking forward to use MySQL as an optional alternative someday

**Comment by emilengler** [comment]
Alright guys, here is an short update!
I now plan to do one issue per day assigned to the milestone.
After I'm done with these I'll fix bugs and work on the API.
Maybe the release will delay 1-2 days because of missing translations.
Thanks, Emil

**Comment by ryangurn** [comment]
Please let me know if I can help with this @emilengler... I am quite bored and would love to help in any way that you find useful!

**Comment by emilengler** [comment]
@ryangurn Hey, yes you can help a lot!
I would have three things you can do:
* Fix bugs in the issue tracker
* Repair the config censor tool on podcastgenerator.github.io
* Make the theme system better, the current one has too much logic in it, it is too hard for others to make there custom themes
