### ISSUE TITLE
Call to undefined function bindtextdomain()

### ISSUE THREAD

**Issue by RealLongwayround** [PodcastGenerator/PodcastGenerator#163]
I have just freshly installed v3.0. Having entered a new admin username and password as part of the setup process I now get the following message:

Fatal error: Uncaught Error: Call to undefined function bindtextdomain() in /home/shrimper/public_html/bbmc/podcastgen3/core/translation.php:14 Stack trace: #0 /home/shrimper/public_html/bbmc/podcastgen3/core/include.php(23): include() #1 /home/shrimper/public_html/bbmc/podcastgen3/index.php(11): require('/home/shrimper/...') #2 {main} thrown in /home/shrimper/public_html/bbmc/podcastgen3/core/translation.php on line 14

**Comment by RealLongwayround** [comment]
I should add that my server runs PHP 7.0.

**Comment by emilengler** [comment]
You need PHP 7 and also php-gettext. Do you have shell access?

**Comment by RealLongwayround** [comment]
I don’t have shell access— I’m using the PHP 7 installation provided by my domain host.

--
Luke Bosman
— Sent from Polymail ( https://polymail.io/ )

**Comment by emilengler** [comment]
Hmmm is there any way to install the `php-gettext` extension? Otherwise you should contact your host provider. They should install the package for you
