### ISSUE TITLE
Certain file names breaks FTP indexing

### ISSUE THREAD

**Issue by nemosmithasf** [PodcastGenerator/PodcastGenerator#164]
This title will break auto-indexing: `01 Example (Part 1).mp3`

There's no response message, just a blank page.

**Comment by emilengler** [comment]
I will have a look at it.
Maybe you should change `$strictflienamepolicy` in config.php from `"yes"` to `"no"`

**Comment by nemosmithasf** [comment]
Changing `$strictnamepolicy` fixed it. Thanks!

Perhaps there should be some error message?

**Comment by nemosmithasf** [comment]
Seems like I spoke too soon. changing `srictnamepolicy` fixed reindexing, but the file doesn't appear in the feed

**Comment by emilengler** [comment]
Could you manually regenerate the RSS feed?

**Comment by nemosmithasf** [comment]
I tried, but it didn't fix the problem.

**Comment by emilengler** [comment]
Hmm could you post the directory listing of your `media/` folder?

**Comment by nemosmithasf** [comment]
I downgraded back to 2.6 yesterday, so I don't have the `media/` folder anymore. But the result of the renamed `01 Example (Part 1).mp3` and the associated .xml file was the only thing in the directory.

**Comment by emilengler** [comment]
I'm sorry that you had troubles with 3.0
I will try to improve the FTP Feature

**Comment by nemosmithasf** [comment]
No worries, thanks for all your good work

**Comment by emilengler** [comment]
I just tried it on my own and it worked fine though.
Maybe you need to change `max_recent` to all in your config.php

**Comment by emilengler** [comment]
Thanks for the report!
I can finally reproduce. Working on a fix right now

**Comment by emilengler** [comment]
Fixed now. I can index a file with that name^^
