### ISSUE TITLE
cron URL not working

### ISSUE THREAD

**Issue by nemosmithasf** [PodcastGenerator/PodcastGenerator#165]
I'm having trouble using the cron URL with an synology install. Not sure if its a user error or bug.

When I visit the URL directly, there is no response and the feed is not updated: `http://[username].synology.me/podcastgen/pg-cron.php?key=4a1zg90U`

also tried adding the following to task scheduler
```
wget -O- http://[username].synology.me/podcastgen/pg-cron.php?key=4a1zg90U >/dev/null 2>&1
```

**Comment by emilengler** [comment]
As far as I kno Synology still uses PG 2.6
Are you 100% sure you are using 3.0 and if so, could you post the error log from your web server?

**Comment by nemosmithasf** [comment]
I installed 2.6 and then performed an upgrade by replacing the files with the 3.0 release files. Unfortunately, I rolled back to 2.6, so I no longer have the error logs

**Comment by emilengler** [comment]
Actually the PG upgrade from 2.6 to 3.0 was not tested and is not supported.
Coeld you try it again with first upgrading to 2.7 and from 2.7 to 3.0?
You find 2.7 [here](https://github.com/albertobeta/PodcastGenerator/releases/tag/v2.7)
