### ISSUE TITLE
PodcastGenerator v3.0 performance concerns

### ISSUE THREAD

**Issue by cmpilato** [PodcastGenerator/PodcastGenerator#167]
I definitely appreciate the incredible amount of work that must have been invested into reworking the PG codebase for the 3.0 release, but the new version is an order of magnitude slower than the v2.7 codebase.  At the time of writing, my podcast site has 538 episodes.  PG2.7 was serving up its home page in less than half of a second.  Here are actual timings for three iterations of that service:

> $ for i in 1 2 3; do time wget https://podcasts.pbcharrisburg.org/ -q -O - > /dev/null; done
> 
> real	0m0.462s
> user	0m0.014s
> sys	0m0.001s
> 
> real	0m0.468s
> user	0m0.006s
> sys	0m0.007s
> 
> real	0m0.460s
> user	0m0.004s
> sys	0m0.009s
> 
> $

PG3.0 doesn't fair nearly as well.  Again, three timings: 

> $ for i in 1 2 3; do time wget https://podcasts.pbcharrisburg.org/ -q -O - > /dev/null; done
> 
> real	0m8.666s
> user	0m0.006s
> sys	0m0.006s
> 
> real	0m8.430s
> user	0m0.007s
> sys	0m0.007s
> 
> real	0m8.308s
> user	0m0.010s
> sys	0m0.004s
> 
> $

I have not attempted to figure out where the time is being spent.  (PHP isn't my strong suit...)  For what it's worth, though, the Admin interface of PG3.0 is blazingly fast, leading me to believe that this is quite possibly tied to my actual podcast dataset.

**Comment by emilengler** [comment]
Wow haven’t really thought about performance optimization yet. In future I should definitely test with lots of episodes. I will fix this with 3.1 probably it is because the feed is being regenrated to often. However once I figured it out I will tell you how to backport it to 3.0

**Comment by cmpilato** [comment]
I was able to do a bit of debugging today.  In my dataset, viewing index.php without any filtering parameters, `generateRSS()` cost about a second and `getEpisodes()` costs 6+ seconds.  I'll look into a pull request to fix some inefficiencies I've spotted in the getEpisodes() code.

**Comment by cmpilato** [comment]
Add PR #171 to address the major contributor to the performance concerns.

**Comment by cmpilato** [comment]
Another general (yet performance-related) concern is what you've already mentioned, @emilengler, that PG should not be generating the RSS feed on every page view.

Honestly, admins have the cron job, manual feed generation, and FTP auto-index features that can be used to generate the RSS feed as-needed.  In theory, PG should be able to work perfectly for non-admin users even if all the files and directories in the installation are read-only.

**Comment by cmpilato** [comment]
For kicks, here's are the new timings with my site running PG3.0 plus PR #171 and PR #173 :

> $ for i in 1 2 3; do time wget https://podcasts.pbcharrisburg.org/ -q -O - > /dev/null; done
> 
> real	0m2.149s
> user	0m0.008s
> sys	0m0.005s
> 
> real	0m2.000s
> user	0m0.003s
> sys	0m0.011s
> 
> real	0m1.994s
> user	0m0.014s
> sys	0m0.006s
> 
> $

**Comment by emilengler** [comment]
@cmpilato I think this is fixed now? Can I close it?
