### ISSUE TITLE
custom time zone

### ISSUE THREAD

**Issue by z3a** [PodcastGenerator/PodcastGenerator#176]
It would be very useful to configure the time zone of the PG instance to match the time zone of the publisher. For example, my server is two hours before my timezone, so every time I upload an episode I need to remember to subtract two hours of my desire to publish time in order for the episode to appear at my local time.

**Comment by emilengler** [comment]
Is it impossible for you to change the servers timezone?

**Comment by z3a** [comment]
I'm using a shared server for hosting my podcast. Change the server timezone is not an option.

**Comment by emilengler** [comment]
Will try my best :)

**Comment by emilengler** [comment]
This can be solved by adding
```
date_default_timezone_set("Asia/Bangkok");
```
at the end of core/include.php and core/include_admin.php.
Here is a list of all valid timezones: https://www.php.net/manual/en/timezones.php
