### ISSUE TITLE
Step 3 issue

### ISSUE THREAD

**Issue by distrob** [PodcastGenerator/PodcastGenerator#186]
On step 3, , when creating my login and password, upon submitting it, I see this message:

Warning: Cannot modify header information - headers already sent by (output started at /Users/bernardo/Sites/podcasthost/podcastgen/PodcastGenerator-3.0/PodcastGenerator/setup/step3.php:38) in /Users/bernardo/Sites/podcasthost/podcastgen/PodcastGenerator-3.0/PodcastGenerator/setup/step3.php on line 72

**Comment by emilengler** [comment]
Does it work anyway? A Waring isn't an error?

**Comment by drukenemo** [comment]
No it doesn't. I also see this message 

Fatal error: Uncaught Error: Call to undefined function bindtextdomain() in /Users/bernardo/Sites/podcasthost/podcastgen/PodcastGenerator-3.0/PodcastGenerator/core/translation.php:14 Stack trace: #0 /Users/bernardo/Sites/podcasthost/podcastgen/PodcastGenerator-3.0/PodcastGenerator/core/include.php(23): include() #1 /Users/bernardo/Sites/podcasthost/podcastgen/PodcastGenerator-3.0/PodcastGenerator/index.php(11): require('/Users/bernardo...') #2 {main} thrown in /Users/bernardo/Sites/podcasthost/podcastgen/PodcastGenerator-3.0/PodcastGenerator/core/translation.php on line 14

**Comment by emilengler** [comment]
`Uncaught Error: Call to undefined function bindtextdomain() `
That's probably the real error!
Could you install `php-gettext` to your machine?
Otherwise try to rename translation.php to translation2.php

**Comment by drukenemo** [comment]
I already have php-gettext installed.

Renaming translation.php to translation2.php didn't solve the issue unfortunately.

**Comment by emilengler** [comment]
Hmmm which OS are you using and do you have shell access?

**Comment by drukenemo** [comment]
MacOs Catalina. Yes, I do have.

**Comment by emilengler** [comment]
Great are you sure you could you create a php file on your web server with just this content:
```
?php
phpinfo();
```
and look for the gettext component? If you find it, please post a screenshot of it here

**Comment by drukenemo** [comment]
Not sure I did it correctly (don't know php well), but this is what I got:

Warning: Failed to set locale category LC_NUMERIC to en_NL.
Warning: Failed to set locale category LC_TIME to en_NL.
Warning: Failed to set locale category LC_COLLATE to en_NL.
Warning: Failed to set locale category LC_MONETARY to en_NL.
Warning: Failed to set locale category LC_MESSAGES to en_NL.

**Comment by emilengler** [comment]
`en_NL` is an unsupported locale.
You should change to `$scriptlang =  "en_US";` (or any other supported language)

**Comment by drukenemo** [comment]
OK. Now I still get:

Fatal error: Uncaught Error: Call to undefined function bindtextdomain() in /Users/bernardo/Sites/podcasthost/podcastgen/PodcastGenerator-3.0/PodcastGenerator/core/translation.php:14 Stack trace: #0 /Users/bernardo/Sites/podcasthost/podcastgen/PodcastGenerator-3.0/PodcastGenerator/core/include.php(23): include() #1 /Users/bernardo/Sites/podcasthost/podcastgen/PodcastGenerator-3.0/PodcastGenerator/index.php(11): require('/Users/bernardo...') #2 {main} thrown in /Users/bernardo/Sites/podcasthost/podcastgen/PodcastGenerator-3.0/PodcastGenerator/core/translation.php on line 14

**Comment by drukenemo** [comment]
I can't move forward. Maybe I don't know what I'm doing. Don't want to keep bothering.

**Comment by emilengler** [comment]
Strange....
Honestly Podcast Generator wasn't tested on macOS.
Maybe you should try it on a Linux/BSD setup?
It should work fine there

**Comment by cupcakearmy** [comment]
Having the same issue. (Using docker)
After installing gettext the second error with `Uncaught Error: Call to undefined function bindtextdomain()` disappeared. However the first error with the headers already sent is still there. The site works however.

Is there maybe a list of required PHP extensions needed? gettext ist not listed in the install guide. Probably should be added along other required extensions that are requried :)

Are you open to a official docker image? I could do the work of setting it up? Docker is pretty essential these days.

Nevertheless, thanks a lot for the project 🙏

**Comment by emilengler** [comment]
> Are you open to a official docker image? I could do the work of setting it up? Docker is pretty essential these days.

Sure but would you be willing to maintain it?

> Is there maybe a list of required PHP extensions needed? gettext ist not listed in the install guide. Probably should be added along other required extensions that are requried :)

gettext and php-xml

If the translations don't work, could you post your output of `locale -a`

**Comment by cupcakearmy** [comment]
Well I could do the prep work, but no, as I don't know the project at all I could not maintain it. That said, maintaining a docker image for someone who actively develops the project is basically free. You only need to change the Dockerfile if you add a php extension e.g.

**Comment by emilengler** [comment]
@cupcakearmy Sorry for the late answer.
Could you do the prep work now?

**Comment by cupcakearmy** [comment]
I can see what I can do this evening (Europe time)

**Comment by cupcakearmy** [comment]
What folders need to be persisted? `media`, `scripts`, `images`?

**Comment by emilengler** [comment]
@cupcakearmy The login data is stored in config.php.
The scripts folder is the root dir of the PG installation
