### ISSUE TITLE
Episodes and descriptions disappeared 

### ISSUE THREAD

**Issue by jhrockers** [PodcastGenerator/PodcastGenerator#187]
All of my episodes aren't showing, just 1 page out of several. The descriptions for each episode has disappeared as well and when you click on the episode title, it doesn't open in a new window.

Here are 2 links from 2 different websites to give you an idea.

https://harfordcountyliving.com/podcast/
https://chesapeakepodcastnetwork.com/pods

**Comment by emilengler** [comment]
Could you change `max_recent` in config.php to `"all"`?

**Comment by jhrockers** [comment]
No, the program was added through the software programs available on my cpanel from the hosting company

On January 10, 2020, at 6:14 PM, Emil Engler <notifications@github.com> wrote:

Could you change max_recent in config.php to "all"?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/albertobeta/PodcastGenerator/issues/187?email_source=notifications">https://github.com/albertobeta/PodcastGenerator/issues/187?email_source=notifications</a>\u0026email_token=AKB3ZQL3WXYBPBY2F2QRIX3Q5D6MRA5CNFSM4KFNUYYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIVPWOY#issuecomment-573242171", "url": "<a href="https://github.com/albertobeta/PodcastGenerator/issues/187?email_source=notifications">https://github.com/albertobeta/PodcastGenerator/issues/187?email_source=notifications</a>\u0026email_token=AKB3ZQL3WXYBPBY2F2QRIX3Q5D6MRA5CNFSM4KFNUYYKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEIVPWOY#issuecomment-573242171", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by emilengler** [comment]
But you still have access to the FTP files right?

**Comment by jhrockers** [comment]
I tried changing max_recent but it didn't work

**Comment by jhrockers** [comment]
Trying a fresh install

**Comment by jhrockers** [comment]
I do

**Comment by emilengler** [comment]
Then edit your config.php and change "$max_recent" to "all"

**Comment by jhrockers** [comment]
That fixed that part. However, when I click on an episode, the link isn't opening up

**Comment by jhrockers** [comment]
And RSS feed isn't generating

**Comment by emilengler** [comment]
Could you give me your error.log file

**Comment by jhrockers** [comment]
This is the error when I click RSS;

This page contains the following errors:
error on line 29 at column 34: xmlParseEntityRef: no name
Below is a rendering of the page up to the first error.

**Comment by emilengler** [comment]
Your XML is probably invalid

**Comment by jhrockers** [comment]
It was working before the upgrade though. What would the default code be for it to work?

**Comment by emilengler** [comment]
Do you have better logs? Like which XML file is invalid?

**Comment by jhrockers** [comment]
This feed does not validate.

line 3, column 4: xml:lang must be an ISO-639 language code: en_US [help]

    <rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xml:lang= ...
    ^
line 26, column 26: itunes:explicit must be "yes", "no", or "clean": [help]

        	<itunes:explicit></itunes:explicit>
                          ^
line 29, column 33: XML parsing error: <unknown>:29:33: not well-formed (invalid token) [help]

		<itunes:category text="Health & Fitness"></itunes:category>
                                 ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.

line 7, column 108: Self reference doesn't match document location [help]

... rel="self" type="application/rss+xml" />
                                             ^
Source: https://harfordcountyliving.com/podcast/feed.xml
<?xml version="1.0" encoding="utf-8"?>
   
   <rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xml:lang="en_US" version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
<channel>
<title>Harford County Living </title>
<link>http://harfordcountyliving.com/podcast/</link>
<atom:link href="http://harfordcountyliving.com/podcast/feed.xml" rel="self" type="application/rss+xml" />
<description>Local Businesses, People and Organizations from Harford County join Rich Bennett and guests to discuss business, arts, events, marketing and more.</description>
<generator>Podcast Generator 3.0 - http://www.podcastgenerator.net</generator>
<lastBuildDate>Mon, 13 Jan 2020 12:39:53 -0500</lastBuildDate>
<language>en</language>
<copyright>© 2020 Harford County Living</copyright>
<itunes:image href="http://harfordcountyliving.com/podcast/media/itunes_image.jpg" />
<image>
<url>http://harfordcountyliving.com/podcast/media/itunes_image.jpg</url>
<title>Harford County Living </title>
<link>http://harfordcountyliving.com/podcast/</link>
</image>
<itunes:summary>Local Businesses, People and Organizations from Harford County join Rich Bennett and guests to discuss business, arts, events, marketing and more.</itunes:summary>
<itunes:subtitle>There's No Place Like It</itunes:subtitle>
<itunes:author>Rich Bennett</itunes:author>
<itunes:owner>
<itunes:name>Rich Bennett</itunes:name>
<itunes:email>rbennett@harfordcountyliving.com</itunes:email>
        </itunes:owner>
        <itunes:explicit></itunes:explicit>
<itunes:category text="Business"></itunes:category>
<itunes:category text="Arts"></itunes:category>
<itunes:category text="Health & Fitness"></itunes:category>

**Comment by emilengler** [comment]
I will take a look at this tomorrow

**Comment by jhrockers** [comment]
Okay, thanks

**Comment by jhrockers** [comment]
I tried changing the lines in the feed.xml, but they keep reverting back

**Comment by emilengler** [comment]
How they revert back? With stuff like an `&amp`?

**Comment by jhrockers** [comment]
It looks like 1 with the &amp, but the others weren't.

This feed does not validate.

line 3, column 4: xml:lang must be an ISO-639 language code: en_US [help]

    <rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xml:lang= ...
    ^
line 26, column 26: itunes:explicit must be "yes", "no", or "clean": [help]

        	<itunes:explicit></itunes:explicit>
                          ^
line 29, column 33: XML parsing error: <unknown>:29:33: not well-formed (invalid token) [help]

		<itunes:category text="Health & Fitness"></itunes:category>
                                 ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.

line 7, column 108: Self reference doesn't match document location [help]

... rel="self" type="application/rss+xml" />

**Comment by emilengler** [comment]
What are your categories?
Can you give me the values from these items in the `config.php`?

**Comment by jhrockers** [comment]
Business 
Arts 
Health 
Music 
Education 
History 
Nonprofit 
Marketing 
Podcasting 

These are what's created in Podcast Generator

Here's what is in the config.php

$itunes_category[0] = "Business"; // iTunes categories (mainCategory:subcategory)

$itunes_category[1] = "Arts";

$itunes_category[2] = "Health & Fitness";

**Comment by emilengler** [comment]
Could you change `$itunes_category[2]` to `"Health &amp; Fitness"`

**Comment by jhrockers** [comment]
Changed $itunes_category[2] = "Health &amp; Fitness";

Stille getting 

This feed does not validate.

line 3, column 4: xml:lang must be an ISO-639 language code: en_US [help]

    <rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xml:lang= ...
    ^
line 26, column 26: itunes:explicit must be "yes", "no", or "clean": [help]

        	<itunes:explicit></itunes:explicit>
                          ^
line 29, column 33: XML parsing error: <unknown>:29:33: not well-formed (invalid token) [help]

		<itunes:category text="Health & Fitness"></itunes:category>
                                 ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendation.

line 7, column 108: Self reference doesn't match document location [help]

... rel="self" type="application/rss+xml" />
                                             ^

**Comment by emilengler** [comment]
> Changed $itunes_category[2] = "Health & Fitness";

I don't see the `&amp;`

**Comment by jhrockers** [comment]
Changed it to Health which seemed to fix that. Now I get the following:

This feed does not validate.

line 3, column 4: xml:lang must be an ISO-639 language code: en_US [help]

    <rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xml:lang= ...
    ^
line 26, column 26: itunes:explicit must be "yes", "no", or "clean": [help]

        	<itunes:explicit></itunes:explicit>
                          ^
line 53, column 90: Invalid character in a URI: http://harfordcountyliving.com/podcast/?."name=2019-12-16_whats_your_favorite.mp3 (99 occurrences) [help]

... "name=2019-12-16_whats_your_favorite.mp3</guid>
                                             ^
line 55, column 14: Invalid email address: () (98 occurrences) [help]

			<author> ()</author>
              ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

line 7, column 108: Self reference doesn't match document location [help]

... rel="self" type="application/rss+xml" />
                                             ^
line 49, column 209: itunes:summary should not contain HTML: &lt; (10792 occurrences) [help]

... oute 24 Ale House&lt;/a&gt;&lt;/p&gt;]]></itunes:summary>
                                             ^
line 64, column 160: itunes:subtitle should not contain HTML: &amp; (12 occurrences) [help]

... mp; EMS Association about Fire Safety]]></itunes:subtitle>
                                             ^
line 1984, column 89: itunes:keywords should not contain HTML: &amp; (2 occurrences) [help]

...  Bennett, Arts, Towne Grill &amp; Pub]]></itunes:keywords>
                                             ^

**Comment by jhrockers** [comment]
Any luck with the bugs and issues?

**Comment by emilengler** [comment]
I will work on this later. I currently have fever and therefore can't really concentrate on anything

**Comment by cmpilato** [comment]
The issue with invalid characters in the `itunes:category` has already been fixed in `master` (see #182).

The issue with missing/malformed author strings as well (#183).

I'm not seeing in my own PG3.0 feed the "Invalid character in a URI" issue you mention.  But perhaps your `$link` configuration value in `config.php` (which informs the content of the `<guid>` feed elements) is more complicated than mine, which reads only:  `$link = "?name=";`

**Comment by jhrockers** [comment]
The other issue I have is when you click on the link of the episode, it doesn't open to show all of the details. This is what I get for all episode links https://harfordcountyliving.com/podcast/index.php?.

**Comment by emilengler** [comment]
@jhrockers What is the value of `$link` in your config.php?

**Comment by jhrockers** [comment]
$link = "$url."?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

**Comment by cmpilato** [comment]
I think you need to lose the `."` from the middle of that.   This should result in calculated permalinks like `http://harfordcountyliving.com/podcast/?name=2019-12-16_whats_your_favorite.mp3`.

**Comment by cmpilato** [comment]
FWIW, my personal configuration just has this:  `$link = "?name=";`

**Comment by jhrockers** [comment]
That seemed to work, although all of the original text, hyperlinks and sponsors ads are no longer in the episodes notes

**Comment by jhrockers** [comment]
Still getting the following as well:

This feed does not validate.

line 3, column 4: xml:lang must be an ISO-639 language code: en_US [help]

    <rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xml:lang= ...
    ^
line 26, column 26: itunes:explicit must be "yes", "no", or "clean": [help]

        	<itunes:explicit></itunes:explicit>
                          ^
line 82, column 14: Invalid email address: () (97 occurrences) [help]

			<author> ()</author>
              ^
In addition, interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

line 7, column 108: Self reference doesn't match document location [help]

... rel="self" type="application/rss+xml" />
                                             ^

**Comment by cmpilato** [comment]
> That seemed to work, although all of the original text, hyperlinks and sponsors ads are no longer in the episodes notes

I'm pretty sure that this is because the default theme for PG3.0 doesn't show the "long description".  In my theme, I replaced this line in `singleepisode.php`:

```
echo '  <div class="episode-desc">' . htmlspecialchars($correctepisode["episode"]["shortdescPG"]) . '</div>';
```

with this:

```
echo '  <div class="episode-desc">' . $correctepisode["episode"]["longdescPG"] . '</div>';
```

**Comment by cmpilato** [comment]
I mentioned already that there's been a fix for the ugly "author" data (#183).  As for the other validation errors, I assume they are legit, but they haven't been hampering Google Play, iTunes, or PocketCasts on my own podcast.

**Comment by jhrockers** [comment]
I'm not finding that thread in echo '  <div class="episode-desc">' . htmlspecialchars($correctepisode["episode"]["shortdescPG"]) . '</div>';

I see what you posted in #183 , but I'm not sure what to change in that and how.

**Comment by jhrockers** [comment]
After taking a break since the holidays, I just went to upload a new episode and received this error: Invalid filename, only A-Z, a-z, underscores and dots are permitted

Never had that before and I haven't changed anything in the way I upload the episodes.

**Comment by cmpilato** [comment]
Disable the strict file name policy in your `config.php`?

**Comment by emilengler** [comment]
Yes, @cmpilato said the answer.
Do `$strictfilenamepolicy = "no";`

**Comment by emilengler** [comment]
Will close this because of inactivity. Let me know if you still have problems

**Comment by jhrockers** [comment]
Unfortunately I had to go to an online service because my Sponsors were getting upset that the podcasts weren’t showing their ads and other things.

**Comment by emilengler** [comment]
I'm very sorry to hear that :(
Hope we'll see you again in the future

**Comment by jhrockers** [comment]
Once Podcast Generator can be installed and ran without having to do any code, like the last one, I’ll be back
