### ISSUE TITLE
PodcastGenerator 3.0 does not show Swedish translation.

### ISSUE THREAD

**Issue by tellustheguru** [PodcastGenerator/PodcastGenerator#188]
I have set PodcastGenerator to se_SE, but still show the page in English. 

I have checked that gettext are installed and active.

The server is Debian Linux (Buster).

**Comment by emilengler** [comment]
Please use `sv_SE`

**Comment by tellustheguru** [comment]
Sorry I misspelled, I mean sv_SE :)

**Comment by emilengler** [comment]
Could you execute
`locale -a` and give me the output?

**Comment by tellustheguru** [comment]
Here is the output:
C
C.UTF-8
POSIX
swedish
sv_SE
sv_SE.iso88591
sv_SE.iso885915
sv_SE.utf8

**Comment by emilengler** [comment]
Edit `config.php`
Edit `$scriptlang` to `"sv_SE.utf8"`

**Comment by emilengler** [comment]
And restart your web server and php interpreter after this

**Comment by emilengler** [comment]
If it still doen't work, restart your entire server if possible.

**Comment by tellustheguru** [comment]
I have:
- change sv_SE to sv_SE.utf8 in config.php
- restarted apache server, no effect.
- rebooted Linux, no effect.

**Comment by tellustheguru** [comment]
I get this output in the errorlog if it´s helps:
[Sun Jan 12 14:29:55.212327 2020] [php7:notice] [pid 1595] [client xxx.xxx.xxx.xxx:43869] PHP Notice:  Undefined offset: 0 in /xxx/xxx/index.php on line 31

**Comment by emilengler** [comment]
Try `locale-gen`

**Comment by tellustheguru** [comment]
No effect :(

**Comment by emilengler** [comment]
Is `php-gettext` installed or just `gettext`?

**Comment by tellustheguru** [comment]
both :)

**Comment by emilengler** [comment]
I'm not familiar with apache but I believe this problem exists because of the gettext cache.
Maybe `apachectl graceful` will help to clear the cache.

**Comment by tellustheguru** [comment]
No effect :(

Have got another error message in error log:

[Sun Jan 12 23:05:03.762435 2020] [php7:notice] [pid 23625] [client xxx.xxx.xxx.xxxx:35677] PHP Notice:  Trying to access array offset on value of type null in /xxx/yyy/themes/kvesset/singleepisode.php on line 23, referer: https://xyz.foo.se/

**Comment by emilengler** [comment]
all these errors aren't dramatically, they are just warnings.
Have you re-installed PG3 completely after you installed the wrong "version"

**Comment by tellustheguru** [comment]
Yes,

It is a new installation.
I could send you a link, but not here.

**Comment by alwa** [comment]
For the record Swedish works for me. I just upgraded from 2.7 to 3.0

**Comment by alwa** [comment]
Let me know if you would like samples from my config ...

From my config.php:

`$scriptlang = "sv_SE";`

**Comment by itsckl** [comment]
I had the same problem with German language setting.  
Although I don't fully understand the translation system used in podcastgen, I've done a fix to translation.php which did the trick for me. 
[translation.zip](https://github.com/PodcastGenerator/PodcastGenerator/files/4422966/translation.zip)

**Comment by emilengler** [comment]
@itsckl I've looked at it, it is a good idea!
Are you familiar with opening a pull request on github? Otherwise I can commit for you but I need you permission to publish it into the public domain

**Comment by itsckl** [comment]
> but I need you permission to publish it into the public domain

Sure, go ahead!

**Comment by tellustheguru** [comment]
After a very long time I find the the source of the problem. It seems it is a bug in mod_perl in apache that is blocking gettext in php for some reason, when I disable mod_perl it works. But when I activate mod_perl the problem appers again.
(Se [https://www.claudiokuenzler.com/blog/1023/php-gettext-translations-not-working-apache-mod_php-cli-works](https://www.claudiokuenzler.com/blog/1023/php-gettext-translations-not-working-apache-mod_php-cli-works))

**Comment by emilengler** [comment]
Wow interesting, your research is helpful, I will close the issue for now.
Tack sa mycket!
