### ISSUE TITLE
Changing feed language has no effect (?)

### ISSUE THREAD

**Issue by alwa** [PodcastGenerator/PodcastGenerator#195]
Steps to reproduce:
1. Change Podcast Details
2. Edit the feed language (to Swedish)
3. Press Submit

Expected:
New language is set

Actual:
Language still English
**Update** what I mean by this is that the selected option reverts back to "English"

Same problem exists when changing whether podcast has explicit content. Probably more related problems...

**Comment by alwa** [comment]
OK, I haven't followed all upgrade steps yet. Closing this for now.

**Comment by alwa** [comment]
I still can't get this to work. 

Reopening...

**Comment by emilengler** [comment]
feed_language only changes the value in `feed.xml`.
Please change scriptlang to `sv_SE`

**Comment by alwa** [comment]
@emilengler Done and the RSS feed now is correct. But what I meant by the bug is that when saving a change in the edit view it reverts back (in this view to the old values). So it seems that something is off

**Comment by emilengler** [comment]
I don't know what you mean. Could you specify it?

**Comment by alwa** [comment]
I'll try.

Normally, when selecting something from a drop down menu and pressing Save the new selection is selected.
This is not the case. So in the view English is selected. I change to Swedish and press Save (called Submit in Podcast Generator). When the page is reloaded the language is reverted to English in the dropdown menu. Same problem with the "explicit" option (and possibly other options, I haven't tried changing anything else).

**Comment by itsckl** [comment]
The feed language field is not initialized from config.php, its value is hardcoded in podcast_details.php:
<option value="en" **selected**>English</option>
Same is true for the "explicit" flag:
<input type="radio" name="explicit" value="no" checked>

I attach a new version of podcast_details.php with a fix (this also adds  dropdown for the script language). 
[podcast_details.zip](https://github.com/PodcastGenerator/PodcastGenerator/files/4422583/podcast_details.zip)

**Comment by antonkarliner** [comment]
@itsckl thanks! your fix helped me as well!

**Comment by emilengler** [comment]
@itsckl Thanks!
