### ISSUE TITLE
Redirecting RSS Feed

### ISSUE THREAD

**Issue by AboundinginHope** [PodcastGenerator/PodcastGenerator#207]
I need to know how to redirect the RSS feed from Podcast Generator to a new podcast host. I tried doing it from my cPanel and also from inside my blog but it is not working.

**Comment by emilengler** [comment]
You can replace the `feed.xml` file with the feed file from your new host. However there is no automatic way to redirect. You'll need to update the feed file every time you update your feed

**Comment by cmpilato** [comment]
I should think that your cPanel would allow you to configure a Redirect for the feed.xml URL.  I'm not familiar with cPanel, but if this was a straight Apache HTTP Server configuration, it's a one-line directive:

    RedirectPermanent /podcast/feed.xml https://newhost.com/podcast/new-feed.xml

(where `/podcast/feed.xml` is the path-only bit of the URL of your current feed XML file).

Of possible utility:  https://www.a2hosting.com/kb/cpanel/cpanel-domain-features/redirects ?
