### ISSUE TITLE
Episode File has shown like a document on Itunes Podcast, not audio file

### ISSUE THREAD

**Issue by guillaumedavy01** [PodcastGenerator/PodcastGenerator#214]
Hello
I put some episodes on my nas with PG.
All work ! Thanks
One thing, on Itunes, episodes are define like document, not like audio file.
When you click on the episode, podcast app on IOS open a window and play the audio file.
Functions rewind or forward 10 sec don't work

Do you have an idee about that?

If you want to check on the podcast store
search : le metier a changé

Thanks for your help

Guillaume from France !
Sorry for my english school +1
**Description of your problem:**

**Comment by emilengler** [comment]
Hey Guillaume,
can you tell us which version of Podcast Generator do you use?
As far as I know the Synology Store uses 2.6 instead of 3.0.1

**Comment by guillaumedavy01** [comment]
I use the 2.4 version of PG

**Comment by guillaumedavy01** [comment]
Oups sorry, on the xml it's write 2.4 but on DSM, it's write 2.6-0109

**Comment by emilengler** [comment]
> I use the 2.4 version of PG

I'm sorry but the support of the version was dropped in 2015.
Would it be possible for you to update manually in example editing the files of Podcast Generator manually?

**Comment by guillaumedavy01** [comment]
Hello thanks to answer.
I don't understand very well your request! 

Just to improve my case
I use PG to broadcast my sounds recording. 
It's work very well with Android app like podcast addict on my phone. 
But on my iPad, when you open my podcast, you have each episode but with a small paper under the name of the episode. 
And when you type more it's write document 

My sounds file are in wave, around 300 mega octet. Is it in 44,1 16bit or different to be understood by iTunes like a sound file? 

Thanks for your feddback. 

Kind regards. 

Guillaume Davy

**Comment by emilengler** [comment]
I mean you use Podcast Generator Version 2.4. We don't offer support for this anymore. It is highly suggest to upgrade. My question was do you have access to the direcotry where podcast generator is installed?

**Comment by guillaumedavy01** [comment]
Ah I understand!
The version is 2.6, not 2.4 sorry. 
I have access of the directory. It's on my Nas synology and I'm admin

**Comment by emilengler** [comment]
Good. Can download version 2.7 from here: https://github.com/albertobeta/PodcastGenerator/releases/tag/v2.7 and replace all files in your folder with these? Concat folders if asked for.

After this, please do the same but with version 3.0.1 from here: https://github.com/albertobeta/PodcastGenerator/releases/tag/v3.0.1

**BE SURE TO MAKE A BACKUP OF THE ENTIRE PODCAST GENERATOR DIRECTORY BEFORE UPDATING**

**Comment by guillaumedavy01** [comment]
Thanks for your answer.
To be sure i made a backup of Podcastgenerator folder.

I try to update the version and i ll come back very soon

Thankssss a lot

Guillaume

**Comment by guillaumedavy01** [comment]
Hello
I copied the entire folder from 2.7 version. 
But I don't have message to enter my password.
Where can I find the version of PG on my server ?
When I click on feed.xml file it's write 2.0 version !

Strange !

Can you help me ! Thanks a lot

Guillaume

**Comment by emilengler** [comment]
Sorry but I don't know what you means with message to enter your password

**Comment by guillaumedavy01** [comment]
Hello, sorry for my last message, I didn't remember where I read I need to put my password !

So I download 2.7 version, I unziped the folder, I removed media, setup and images folder, I push files on my PG folder.
It's working but when I click on RSS button,
prodiction.fr/podcastgen/feed.xml
It's write 2.4 version !
So the upgrade didn't work !

Do you have an idee ?

Thanks a lot for your futur feedback

Guillaume

**Comment by emilengler** [comment]
Try to concat te folder (copy the files from the new version to the old folder and replace files if asked for)

**Comment by guillaumedavy01** [comment]
Thanks for your help
It's work now

Guillaume Davy
