### ISSUE TITLE
Only first file type from supported_media.xml is loaded

### ISSUE THREAD

**Issue by Plus200** [PodcastGenerator/PodcastGenerator#216]
**System Information**
Podcast Generator Version:  3.0
PHP Version: 7.2

It seems that only the first entry (mp3) from supported_media.xml is loaded by the loop
foreach ($supported_extensions_xml->mediaFile->extension as $item)

Thus, only mp3 are loaded to the feed.xml

When manually adding "mp4" to the array, it loads mp4 files as well.

Couldn’t figure out why only one extension is loaded to the array.

**Comment by emilengler** [comment]
Can you really upload ONLY mp3 files? Have you tried others?

**Comment by Plus200** [comment]
Yes. I was struggling to add mp4 files, but only after hardcoding mp4 as valid extension I was able to.
The loop to load valid extensions loads only tye first one (mp3) on the xml file

**Comment by xppx99** [comment]
Hello, I can confirm this issue. I've been using podcastgen 2.X for years, today I've made a clean 3.0 install and all my *.m4b files are missing.

**Comment by emilengler** [comment]
Thanks for letting me know!
I will plan to release Podcast Generator 3.0.2 this weekend which will remove the MIME type checking so this problem won't occur anymore.
Of course this is not the best solution but a quick patch is neccesary and I try to re implement this feature on a clean way with an option to disable in 3.1

**Comment by munkee** [comment]
I'm also seeing this and I think it may be the cause of some of the other issues related to empty feeds #219 & #222

**Comment by ryangurn** [comment]
I think I was able to identify the change that was needed for this to some lines in `core/feed_generator.php` which was pulling all of the supported extensions and doing some looping to get it back from the XML parser form into an array to use within the PHP file. 

The previous code was as following.

```
foreach ($supported_extensions_xml->mediaFile->extension as $item) {
    array_push($supported_extensions, $item);
}
```

However, it really needs to be... to ensure that it's not just getting the first item in the XML object.
```
    foreach ($supported_extensions_xml->mediaFile as $item) {
        array_push($supported_extensions, (string)$item->extension);
    }
```
 Please review PR #236 and you will see the code to fix this.

**Comment by emilengler** [comment]
I'm curios on how a type conversion should fix this but I'll test it later today

**Comment by munkee** [comment]
> I'm curios on how a type conversion should fix this but I'll test it later today

It's not the type conversion on the second line that fixes it, it's the change in what your looping over in the foreach. Instead of looping over the mediaFile.extension (there's only one in the first item) it now loops over all of the mediaFile items.

I too will check soon to see if this fixes it.

**Comment by ryangurn** [comment]
exactly @munkee i just had to do the type casting to ensure that they are not added to the array as an xml simple object. We want to ensure that we are looping over strings, I will be changing it to the c standard string cast in a little

**Comment by emilengler** [comment]
Ok, oversaw that

**Comment by AmeelMD** [comment]
Hi @emilengler I am having the same feed not containing any media issue as well, for years I've been using version 2.x and it's been great except when it stopped accepting any changes to anything :(
I made the decision to do a clean install of 3.x although 3.x doesn't want to populate the feed. I have been using .m4a files (enhanced podcast with chapter makers) with no issue until this point. Looking forward to your updates. Also, thank you for all the work that you do with this project, it's simple and amazing, thank-you and be safe.

**Comment by emilengler** [comment]
Thanks^^
