### ISSUE TITLE
Upgrade from 2.7 to 3.0.1 Problems

### ISSUE THREAD

**Issue by RobHowdle** [PodcastGenerator/PodcastGenerator#223]
**System Information**
Podcast Generator Version:  3.0.1
Webserver: Linux
PHP Version: 7.1.33

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE

Cannot import censored config because the link provided to cencor the config.php file doesn't work. The Javascript has an error according to my console and doesn't censor the output. Happy to send config via private email.
``` 

I have quite a few problems, had to upgrade due to change of computer and forgotten password for version 2.7 and there wasn't a way to change my login password that I could find. Installed V3.0.1, copied my media folder over had to change all of my details as nothing had copied over with regards to the details.

First issue is that when I have uploaded an episode previously, it has gone onto Apple and Spotify almost instantly. Since upgrading to this version, the episodes are taking a lot longer to come up. At the time of writing this, I uploaded an episode nearly 3 hours ago and it's still not appeared. I go straight from my server to apple and spotify, and previously they'd have been up on the platforms within minutes of uploaded the episode. When I go on the apple podcast preview the episodes are there they are just not pushed out fully for some reason... yes the feeds have been changed to the new one.

Second issue is that I have my podcast on Apple Podcasts, previous version 2.7 was great but this one all of the formatting on the Apple side of it has gone out the window. I've scheduled a refresh but that can take up to 48 hours so I'll have to come back to you on that one to see if that works but now my logo has gone and all the descriptions have the <p></p> tags and various other tags which are not present in the dashboard edit of the episode.
![image0](https://user-images.githubusercontent.com/43747640/74789694-65dca400-52ad-11ea-9688-7d9af86f48ce.png)

Third Issue is that I set categories to be disabled, in my config.php file $categoriesenabled="no"; but when I go to edit an episode, it's asking me to give categories.

Could you please help with this? I was unable to convert my config.php to the censored version as when I checked my console after nothing happening it said there was an issue in the javascript - screen shot blow
![errorpcg](https://user-images.githubusercontent.com/43747640/74790639-15b31100-52b0-11ea-8218-4f250fa6960f.png)

Hopefully you can help.

Thanks
Rob

**Comment by emilengler** [comment]
> First issue is that when I have uploaded an episode previously, it has gone onto Apple and Spotify almost instantly. Since upgrading to this version, the episodes are taking a lot longer to come up. At the time of writing this, I uploaded an episode nearly 3 hours ago and it's still not appeared. I go straight from my server to apple and spotify, and previously they'd have been up on the platforms within minutes of uploaded the episode. When I go on the apple podcast preview the episodes are there they are just not pushed out fully for some reason... yes the feeds have been changed to the new one.

I'm not sure if PG 2.7 had something like a push algorithm. Will take a look at the codebase

> Second issue is that I have my podcast on Apple Podcasts, previous version 2.7 was great but this one all of the formatting on the Apple side of it has gone out the window. I've scheduled a refresh but that can take up to 48 hours so I'll have to come back to you on that one to see if that works but now my logo has gone and all the descriptions have the 

Hmmm I saw your screenshot. If this was your only problem (HTML tags details section) then it should be fixed now :)

> Third Issue is that I set categories to be disabled, in my config.php file $categoriesenabled="no"; but when I go to edit an episode, it's asking me to give categories.

Will check this out

**Comment by cmpilato** [comment]
I am preparing a fix for the disabled-categories issue ("Third issue").

**Comment by cmpilato** [comment]
See #227 for the fix to the disabled-categories bit.

**Comment by emilengler** [comment]
Hi!
First big sorry to you @cmpilato for not including your Patch into 3.0.1. I will do my best to get it into 3.0.2. I think I've forgot the purpose of this commit.

I will now try to reproduce this issue as it got reported a lot here

**Comment by emilengler** [comment]
The third issue should be fixed now!
Big thanks to @cmpilato for the patch!
