### ISSUE TITLE
Configuration writer mishandled semicolons found in config values

### ISSUE THREAD

**Issue by cmpilato** [PodcastGenerator/PodcastGenerator#224]
**System Information**
Podcast Generator Version: 3.0.1 (fresh install)
Webserver: Apache HTTP Server 2.4
PHP Version: 7.2

**Report**
Podcast Generator mishandles `config.php` values which contain semicolons.  This can be demonstrated using the Change Podcast Details (`admin/podcast_details.php`) admin form.

Before editing the Podcast details, the Copyright configuration line in my `config.php` reads:

```
$copyright = ""; // Your copyright notice (e.g CC-BY)
```

After entering "Copyright C. Michael Pilato; Licensed under the cc-by-3.0 license." as my copyright statement and submitting the form, the `config.php` line reads:

```
$copyright = "Copyright C. Michael Pilato; Licensed under the cc-by-3.0 license."; // Your copyright notice (e.g CC-BY)
```

So far, so good.  There's only one problem:  the resulting form shows only the following in that field's value:

`Copyright C. Michael Pilato`

This would seem to indicate that something is stripping semicolons -- even those quoted inside strings -- and subsequent characters from the configuration values before displaying them.  What's worse is that resubmitting the form then makes things get really wonky, resulting in a `config.php` line that reads:

```
$copyright = "Copyright C. Michael Pilato"; Licensed under the cc-by-3.0 license."; // Your copyright notice (e.g CC-BY)
```

Now the quoting and semicolon placement are all wonky.

**Comment by emilengler** [comment]
Will work on this tomorrow to get it into 3.0.1. Thanks for letting me know
