### ISSUE TITLE
Changing Password

### ISSUE THREAD

**Issue by RobHowdle** [PodcastGenerator/PodcastGenerator#226]
**System Information**
Podcast Generator Version: 3.0.1
Webserver: Linux
PHP Version: 7.1.33

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**
I am unable to figure out how to change the password on the account. Cannot see any documentation and I cannot find any Forgotten Password Resets anywhere. I have had to unexpectedly rebuilt my PC and I wasn't able to copy my passwords out and I seem to have forgotten it. Any suggestions on changing the password/ resetting it?

**Comment by emilengler** [comment]
> I am unable to figure out how to change the password on the account. Cannot see any documentation and I cannot find any Forgotten Password Resets anywhere. I have had to unexpectedly rebuilt my PC and I wasn't able to copy my passwords out and I seem to have forgotten it. Any suggestions on changing the password/ resetting it?

PG does not have a feature for it. I might write a small php recovery script.
Currently the pretty much only easy solution would be to backup your `config.php` file, then delete it and run the installer again.

Then open up the newly created config file and copy the entire line with the `userpassword` value.

Now go back to your backup config and replace the userpassword line with the copied one above.

Now replace the new config with the modified old one and you have your new password set.

The last steps are all optional if you are willing to re configure your PG installation

**Comment by emilengler** [comment]
Hope it worked for you. If not just delete the config.php and run the installer again (you'll need to re configure your podcast then).

I added a recovery tool compatible with the future version only in d01b75d76d3703d7e3ce02d8b541de2a78067532
