### ISSUE TITLE
How do I save changes when editing an episode?  There is no save button.

### ISSUE THREAD

**Issue by rjlappin** [PodcastGenerator/PodcastGenerator#228]
**System Information**
Podcast Generator Version: 3.0
Webserver: dreamhost
PHP Version: 7.4

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**
I do not know how to save changes when editing an episode.

**Comment by cmpilato** [comment]
I found this interface confusing, too. See issue #178 for an explanation and related fixes.

**Comment by rjlappin** [comment]
Well that did not help me since I have a category select.  However, the Author fields have asterisk (usually means required).  I tried putting data in thos field but still pressing Edit just reloads the form with the old information.

**Comment by emilengler** [comment]
Hi rjlappin!
As this issue is a common one (unfortunately) I wanna try reproducing it.
However for this I need your config.php file

Could you copy the content of this file to [this site](https://podcastgenerator.github.io/tools/secure_config.html) and paste the output of this site here?

**Comment by rjlappin** [comment]
I was able to figure it out.  All fields must be filled in and the Explicit content must be set to either yes or no.

**Comment by emilengler** [comment]
The fields should be set anyways. I will close this issue then and have a deeper look at it
