### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by rajnish71** [PodcastGenerator/PodcastGenerator#229]
**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**How do we add multiple users?**

**Comment by emilengler** [comment]
Currently this is not possible. However in Podcast Generator 3.1 which will be released on May 31th or even earlier there will be support for multiple users.
