### ISSUE TITLE
Getting error on rss feed: xmlParseEntityRef: no name

### ISSUE THREAD

**Issue by cgazzolo** [PodcastGenerator/PodcastGenerator#232]
**System Information**
Podcast Generator Version:  current ?
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

Proper rss feed

**Actual behavior**
 
Got error: error on line 27 at column 36: xmlParseEntityRef: no name

**How to reproduce**

Go to: http://byzantinecatholic.com/podcast/feed.xml

**Comment by emilengler** [comment]
This error is already fixed with 3.0.1.
Download and upgrade the new version here: https://github.com/PodcastGenerator/PodcastGenerator/releases/tag/v3.0.1
