### ISSUE TITLE
Will not upload.  Keep getting Invalid Filename

### ISSUE THREAD

**Issue by ozstar** [PodcastGenerator/PodcastGenerator#240]
**System Information**
Podcast Generator Version:  3.01  Softalucious
Webserver:   CloudLinux 6.10
PHP Version: 7.3

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**
HI,

I'm sorry to bug. but I am still  having trouble uploading.  I fixed the file names as suggested still bet. missing flieds, yet all have been filled,. or this, 'Invalid mime type, are you actually uploading a mp3', when it is an mp3 that plays everywhere. 

I would love ti use your script as it does seem like what i want, but have to get over these upload problems.  PHP is 7.3 BTW.

Many thanks

David
David

**Comment by cmpilato** [comment]
Unless it's a typo, it appears you have a hyphen in your filename, which is not one of the permitted character classes.  If you need to use an extended set of characters for your episode names, set the `strictfilenamepolicy` configuration setting to "no".

**Comment by ozstar** [comment]
HI,

I'm sorry to bug. but I am still having trouble uploading. I fixed the file names as suggested still bet. missing fields, yet all have been filled,. or this,
'Invalid mime type, are you actually uploading a mp3', when it is an mp3 that plays everywhere.
or 
'The file upload was not successfully', when all fields are filled.
I would love to use your script as it does seem like what i want, but have to get over these upload problems. PHP is 7.3 BTW.

Many thanks

David
David

**Comment by ozstar** [comment]
Hi,

I deleted the installation then downloaded the file from your site and loaded it from /setup/

Unfortunately I am still having the same problem.

I have attached screenshots which will explain what is happening to me, no matter what file I choose.

It is really weird when I see the good reviews you have and I am having this trouble. 
There must be an explanation somewhere.

Many thanks

David


![PG-Upload 1](https://user-images.githubusercontent.com/7389836/77842976-43ab3f80-71e4-11ea-8a25-fbe21f786a6b.JPG)
![PG-Upload 2](https://user-images.githubusercontent.com/7389836/77842977-44dc6c80-71e4-11ea-829c-6a10bbc68102.JPG)
![PG-Upload 3](https://user-images.githubusercontent.com/7389836/77842978-44dc6c80-71e4-11ea-9b4a-3614394f0ddd.JPG)
![PG-Upload 4](https://user-images.githubusercontent.com/7389836/77842979-45750300-71e4-11ea-9660-01031cb1897f.JPG)
![PG-Upload 5](https://user-images.githubusercontent.com/7389836/77842980-460d9980-71e4-11ea-9ab7-e3cb4940adf7.JPG)

**Comment by emilengler** [comment]
I'm still sorry for the many issue people still have in 3.0 :/
Most problems actually come from the backwards compatibility.
Does your mp3 file has a cover? In 99% of all cases this is the troublemaker of this issue

**Comment by emilengler** [comment]
Just fixed the patch in dc4cd1c365bd789f14fd5121490d62ef76159141
Will try my best to release 3.0.2 with a fix as soon as I can :)

**Comment by ozstar** [comment]
Many thanks Emile.  I appreciate your help and understand the frustration trying to track down problems as I too was once a programmer.
It could be a terrific program once these bugs get sorted out.
Look forward to the patches or new version.
Thanks again and be safe.

**Comment by ozstar** [comment]
BTW Does it matter if there is MetaData in the file details or what bitrate the MP3 files are?
Is there an program upload limit for the file other that the php one?

**Comment by emilengler** [comment]
> BTW Does it matter if there is MetaData in the file details or what bitrate the MP3 files are?

I don't think it matters, it is detected automatically. It is only for the Podcast Clients so the users know which quality it has

>  Is there an program upload limit for the file other that the php one?
YES! I'm thinking about removing it since it is really useless. There is the max_upload_form_size in config.php which has the maximum upload size in byte. Set it to "1000000000" for one GB as example

**Comment by ozstar** [comment]
Hi again Emile,

Tried a few more changes including the max limit upload but still get.. 
'The file upload was not succesful'

I wonder if this would happen in the previous version too?

Do you have a version that I could try please?

Have a great (safe) day,

We in Sydney Oz are in total lock down. A very strange feeling..

Regards,

David

**Comment by emilengler** [comment]
Can you edit configuration files on your server?

**Comment by ozstar** [comment]
Yes I have access to all the files via ftp and can change them.

⁣From our Samsung Note 8. Have a great day from Starlite International Prty Ltd

Get BlueMail for Android ​

**Comment by emilengler** [comment]
I think you should inspect your webserver configuration.
Google something like
"YOUR WEBSERVER increase upload limit"

**Comment by ozstar** [comment]
HI,  This is now solved!

Our host changed the upload limits on the server and now everything does upload as long as there are no space, dashes, in the filename. Words MUST be separated by an undercsore ( _ ) or all words linked together. 

I just need to try and get an image of the file without having to go to itunes.  I have an image already embeded in the MP3 file.  Can this be done ?

Nice program !  Just got to get a few things to work for me.

Thank you

**Comment by ozstar** [comment]
A couple of things if you don't mind please.

 I do not want any downloads so have done this to the index file but a small button still apreas. How do I remove that button?

```
// Some translation strings
$more = _('More');
// $download = _('Download');           <<<------ Did this
$editdelete = _('Edit/Delete (Admin)');
$categories = _('Categories');

$buttons = getButtons('./');
require $config['theme_path']."index.php";
?>
```
Also the file names are very large on the Home Page, where do I chnage these can't seem to see anywhere.

Thank you

**Comment by emilengler** [comment]
Good to know that it is working now :)

For your changes I would have a look at `themes/default/` specifically the files index.php, listepisodes.php and singleepisode.php

Also I'm working on a patch right now to allow mp3 cover uploads. Will publish a version which fixes it soon but currently I lack a bit of motivation though :/
