### ISSUE TITLE
Add Google podcast RSS tags

### ISSUE THREAD

**Issue by guipsfr** [PodcastGenerator/PodcastGenerator#241]
**Description**
Is there a way to add google Podcast rss tags requierment,
https://developers.google.com/search/reference/podcast/rss-feed

**Motivation**
I want to publish our podcasts to Google podcast and maybe others wants to.
Google wont publish to there platforme exept if you have the good tags.
https://search.google.com/devtools/podcast/preview

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by emilengler** [comment]
On my list, I'm going to rewrite the feed generation soon anyways

**Comment by emilengler** [comment]
Should be fixed now
