### ISSUE TITLE
Where can i download themes?

### ISSUE THREAD

**Issue by antonkarliner** [PodcastGenerator/PodcastGenerator#242]
Hello! Thanks for the great work.

I tried the demo and there are some beautiful themes included. But they're not present in a fresh installation. Maybe one day I'll write my own theme – but it would be great to have an ability to download existing ones. I tried to google, no luck.

Thanks in advance!

**Comment by emilengler** [comment]
The current theme system was redone in version 3.0 meaning all previous themes are incompatible now. The current theme system has only one known theme and this is the default one but I'm looking forward in making others. The current theme engine isn't really good either so I'm also planning on rewriting this.
