### ISSUE TITLE
Fails at setup/step1.php

### ISSUE THREAD

**Issue by nneil** [PodcastGenerator/PodcastGenerator#244]
**System Information**
Podcast Generator Version: v3.0
Webserver: Apache 2.4.39
PHP Version: 7.2.19

**Expected behavior**
I want step1.php to work

**Actual behavior**
I get an error 500, but nothing in Apache logs

**How to reproduce**
- Install to folder on webserver.
- Browse to /podcastgen/setup/
- That works
- Click on green button
- Get error 500

**Comment by nneil** [comment]
I managed to work out how to turn on error reporting!

---
Fatal error: Uncaught Error: Call to undefined function simplexml_load_file() in /var/www/html/podcastgen/setup/step1.php:15 Stack trace: #0 {main} thrown in /var/www/html/podcastgen/setup/step1.php on line 15
---

**Comment by emilengler** [comment]
Can you install the package `php-xml`?

**Comment by nneil** [comment]
That fixes it. Maybe add that to your quick install page.
