### ISSUE TITLE
Edit / Delete Episode Broken

### ISSUE THREAD

**Issue by nneil** [PodcastGenerator/PodcastGenerator#245]
**System Information**
Podcast Generator Version: 3.0.1
PHP Version: 7.2.24

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**
I want to edit the list of episodes

**Actual behavior**
I get taken to the homepage

**How to reproduce**
From Admin choose "Episodes" -> "Edit / Delete Episode"

**Comment by emilengler** [comment]
Like I answered earlier, can you show me your permissions of the media directory?

**Comment by emilengler** [comment]
Oh I get what you mean!
This is actually a feature.
You get taken to the homepage, that is true. However you'll see that every episode has a Edit / Delete button than. Click this and you'll be able to edit the episode details.
