### ISSUE TITLE
Error since moving Podcast Generator to new Synology Diskstation

### ISSUE THREAD

**Issue by JLF69** [PodcastGenerator/PodcastGenerator#247]
**System Information**
Podcast Generator Version: 2.6-0109
Webserver: Synology Diskstation 1817+
PHP Version: 2.6

**Podcast Generator Config**

```
<?php

	#################################################################
	# Podcast Generator
	# http://podcastgen.sourceforge.net
	# developed by Alberto Betella
	#
	# Config.php file created automatically - v.2.6


	$podcastgen_version = "2.6"; // Version

	$first_installation = 1504637852;
	
	$installationKey = "zuvyr68i";
	
	$scriptlang = "en_EN";

	$url = "https:///"; // Complete URL of the script (Trailing slash REQUIRED)

	$absoluteurl = "/volume1/web/podcastgen/"; // Absolute path on the server (Trailing slash REQUIRED)

	$theme_path = "themes/exposure/";

	$username = "";

	$userpassword = "";

	$max_upload_form_size = "104857600"; //e.g.: "30000000" (about 30MB)

	$upload_dir = "media/"; // "media/" the default folder (Trailing slash required). Set chmod 755

	$img_dir = "images/";  // (Trailing slash required). Set chmod 755

	$feed_dir = ""; // Where to create feed.xml (empty value = root directory). Set chmod 755

	$max_recent = 6; // How many file to show in the home page

	$recent_episode_in_feed = "All"; // How many file to show in the XML feed (1,2,5 etc.. or "All")

	$episodeperpage = 10;

	$enablestreaming = "yes"; // Enable mp3 streaming? ("yes" or "no")
	
	$enablesocialnetworks = array(1,1,1,); // Enable social networks integration? value 1 (true) or 0 (false) for each social network. Array order: Facebook, Twitter, G+

	$dateformat = "d-m-Y"; // d-m-Y OR m-d-Y OR Y-m-d 

	$freebox = "yes"; // enable freely customizable box

	$enablehelphints = "yes";

	$enablepgnewsinadmin = "no";

	$strictfilenamepolicy = "yes"; // strictly rename files (just characters A to Z and numbers) 

	$categoriesenabled = "no";
	
	$cronAutoIndex = 1; //Auto Index New Episodes via Cron
	
	$cronAutoRegenerateRSS = 1; //Auto regenerate RSS via Cron
	
	$cronAutoRegenerateRSScacheTime = 21600; //Cache (in seconds)


	###################
	# XML Feed elements
	# The followings specifications will be included in your podcast "feed.xml" file.

	$feed_iTunes_LINKS_Website = "";

	$feed_URL_replace = "";
	
	$feed_iTunes_URL_replace = "";

	$podcast_title = "St. Paul's Church, East Ham";

	$podcast_subtitle = "The Sermons";

	$podcast_description = "So you missed the sermon last week because you woke up late, your small child needed the toilet, or you just plain and simply nodded off.  Don't worry, now you can listen again at your leasure.  Grab your Bible, make some notes, or just sit back and relax.";

	$author_name = "St. Paul's Church, East Ham"; 

	$author_email = "sound@stpaulseastham.co.uk"; 

	$itunes_category[0] = "Religion & Spirituality:Christianity"; // iTunes categories (mainCategory:subcategory)
	$itunes_category[1] = "Society & Culture:Philosophy";
	$itunes_category[2] = "";

	$link = $url."?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

	$feed_language = "en_EN"; // Language used in the XML feed (can differ from the script language).

	$copyright = "Copyright St. Paul's Church, East Ham"; // Copyright notice

	$feed_encoding = "utf-8"; // Feed Encoding (e.g. "iso-8859-1", "utf-8"). UTF-8 is strongly suggested

	$explicit_podcast = "clean"; //does your podcast contain explicit language? ("yes", "no" or "clean")

	// END OF CONFIGURATION

	?>
``` 

**Description of your problem:**

I get the following error when trying to regenerate the RSS feed:

Warning: fopen(/volume1/web/podcastgen/feed.xml): failed to open stream: Permission denied in /volume1/web/podcastgen/core/functions.php on line 1459 Warning: fclose() expects parameter 1 to be resource, boolean given in /volume1/web/podcastgen/core/functions.php on line 1460 Warning: fopen(/volume1/web/podcastgen/feed.xml): failed to open stream: Permission denied in /volume1/web/podcastgen/core/functions.php on line 1462 Warning: fwrite() expects parameter 1 to be resource, boolean given in /volume1/web/podcastgen/core/functions.php on line 1463 Warning: fclose() expects parameter 1 to be resource, boolean given in /volume1/web/podcastgen/core/functions.php on line 1464 Warning: fopen(/volume1/web/podcastgen/feed.xml): failed to open stream: Permission denied in /volume1/web/podcastgen/core/functions.php on line 1459 Warning: fclose() expects parameter 1 to be resource, boolean given in /volume1/web/podcastgen/core/functions.php on line 1460 Warning: fopen(/volume1/web/podcastgen/feed.xml): failed to open stream: Permission denied in /volume1/web/podcastgen/core/functions.php on line 1462 Warning: fwrite() expects parameter 1 to be resource, boolean given in /volume1/web/podcastgen/core/functions.php on line 1463 Warning: fclose() expects parameter 1 to be resource, boolean given in /volume1/web/podcastgen/core/functions.php on line 1464

Could anyone point me in the right direction please?  Ive just switched disk stations and now receive the above error when regenerating the RSS feed.

Any help much appreciated.

Thank you in advance.

**Comment by garyee** [comment]
Hi,

The problem is, that php has no "User-rights" on the `/volume1/web/podcastgen` folder. PHP get's executed by a system user called http and you have to grant this user the right to modify (create, delete, execute) the podcast generator folder.
See: https://www.synology.com/en-global/knowledgebase/DSM/help/FileStation/privilege
There is a User and a Usergroup called `http` this user has to have the right to create and modify files in the podcast generator folder.

**Comment by JLF69** [comment]
Thanks, much appreciated, that’s sorted it!
