### ISSUE TITLE
Missing Fields Error

### ISSUE THREAD

**Issue by dank2882** [PodcastGenerator/PodcastGenerator#249]
**System Information**
Podcast Generator Version: 3.1
Webserver: fbc.live
PHP Version: 5.6

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**
I'm afraid this is just dumb user error but I can't figure out what I am doing wrong. I have filled out all the fields, made sure my file size is not to large, filled out all fields and no matter what I do I keep getting the Missing fields error every time I try to post/upload a podcast. 

Can anyone help?

Thank ahead of time,

Dan

**Comment by emilengler** [comment]
You said you use 3.1,
3.1 is not released yet.
Where do you downloaded your version?

**Comment by dank2882** [comment]
I'm so sorry, looks like i was just being lazy when I looked at the file. I'm on version 3.0.1.

Dab

**Comment by emilengler** [comment]
Can you post your error log

**Comment by eichmmar** [comment]
I have the same problem here. It seems that $_POST is emty...

**Comment by emilengler** [comment]
Do you have an error log or something?

**Comment by eichmmar** [comment]
No, there is no error or any warnings. Just the message that not all required fields have been filled.
