### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Grisu1959** [PodcastGenerator/PodcastGenerator#250]
Hello
I installed PODCAST GENERATOR with Softacoulus 
the installation seems ok but it doesn't work
http://pdudine.it/podcast/
http://pdudine.it/podcast/admin/login.php

I have a white page HTTP ERROR 500
Wich could be the problem?

**Comment by Grisu1959** [comment]
Fatal error: Uncaught Error: Call to undefined function bindtextdomain() in /home/hostingandes/public_html/pdudine.it/podcast/core/translation.php:14 Stack trace: #0 /home/hostingandes/public_html/pdudine.it/podcast/core/include.php(23): include() #1 /home/hostingandes/public_html/pdudine.it/podcast/index.php(11): require('/home/hostingan...') #2 {main} thrown in /home/hostingandes/public_html/pdudine.it/podcast/core/translation.php on line 14

**Comment by emilengler** [comment]
You don't have php-gettext installed, can you install it somehow?

**Comment by Grisu1959** [comment]
The support installed it
and now it's working fine

Thanks

Il giorno mer 8 apr 2020 alle ore 16:05 Emil Engler <
notifications@github.com> ha scritto:
