### ISSUE TITLE
Adding Chapter Markers to Episodes

### ISSUE THREAD

**Issue by hervinjr** [PodcastGenerator/PodcastGenerator#253]
**System Information**
Podcast Generator Version: PG 2.7
Webserver:  XAMPP 7.4.1
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**
I was recently asked if it is possible to add Chapter markers so that listeners can jump to specific interviews in the Podcast.  Does this feature exist?

**Comment by emilengler** [comment]
No this is not possible but you can add the location in the video in the long description like

11:12 - Interview with John Doe
