### ISSUE TITLE
Unable to upload podcast cover art

### ISSUE THREAD

**Issue by StrikerObi** [PodcastGenerator/PodcastGenerator#255]
**System Information**
Podcast Generator Version: 3.0.1
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**

When attempting to upload cover art for our podcast, I am receiving an error that says "the image is not quadratic". I'm not really sure what that means, so I have no clue as to how to solve it. And I didn't see anything in the documentation about cover art requirements. My first guess was that the image wasn't perfectly square but I checked and it is exactly 3000x3000px. Has anybody had this error before?  

Sorry I am not sure about the webserver, PHP version, or config. I am the show's producer, and our webmaster is currently unavailable.

**Comment by emilengler** [comment]
Fixed! The new version will be deployed on 31th of May!
