### ISSUE TITLE
Hello I can't generate the podcast on spotify and the rss or the fedd is only for itunes this is very bad that

### ISSUE THREAD

**Issue by createcpty** [PodcastGenerator/PodcastGenerator#256]
**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

**Actual behavior**
 

**How to reproduce**

**Comment by emilengler** [comment]
I've been working on a new feed generator for the next release
