### ISSUE TITLE
Remove spaces in media files

### ISSUE THREAD

**Issue by Strider3000** [PodcastGenerator/PodcastGenerator#258]
Previous version of PCG removed spaces in media file names by replacing spaces with underlines '_'. Can this version do the same? I couldn't get Outcast on apple watch to grab episodes from my private PCG server instance. When I wrote the developer he replied by demonstrating that space characters were breaking his app's ability to grab those media files.

**Comment by emilengler** [comment]
I don't think the current version can. Can you just remove/replace the spaces in the filenames

**Comment by Strider3000** [comment]
I've removed the spaces manually. Could PGC 3.1 please automatically fill-in spaces? thanks

**Comment by emilengler** [comment]
Ok, but I won't add backwards for old files. It will only apply to new files then.

**Comment by Strider3000** [comment]
Fine by me - thanks

**Comment by emilengler** [comment]
Fixed, thanks for the report!
