### ISSUE TITLE
Multiple Users

### ISSUE THREAD

**Issue by pointspreadmedia** [PodcastGenerator/PodcastGenerator#259]
**Description**

I really need a way to manage multiple users rather than multiple episodes. I need a system where users can log in to upload their own episodes, maybe customize their show's profile page, etc. That would really put this product over the top.

**Motivation**

**Legal aspect**

* [ X ] I am the inventor of this idea or the idea is public domain
* [ X ] I release this idea into the public domain

**Comment by emilengler** [comment]
Already added, will be in the 3.1 release expected on 31th of May 2020
