### ISSUE TITLE
New uploads not showing up

### ISSUE THREAD

**Issue by 0scubasteve0** [PodcastGenerator/PodcastGenerator#260]
Hello,
New to the project, just spun it up on a server. I uploaded a test MP3, filled in the necessary info and it claimed the upload was successful. In the /media directory I can see the mp3 and the generated XML file, but the homepage doesn't show the episode. The entire www folder is owned by www-data and the user has read/write permissions. You can take a look at https://thatyearinfilm.com.

Any ideas? Any settings in php.ini I should be adding? Thanks in advance!

**Comment by emilengler** [comment]
Hi, thanks for using Podcast Generator!
Can you post your error log?

If you use apache you should find it under `var/log/apache/error.log`.
On nginx: `/var/log/nginx/error.log`

**Comment by emilengler** [comment]
This looks more like an access.log. Are you sure it is the error.log

**Comment by 0scubasteve0** [comment]
Apologies, I think there were some weird symbolic link configurations with Apache. I think I have the right data now, a lot of PHP errors. 
[error2.log](https://github.com/PodcastGenerator/PodcastGenerator/files/4523625/error2.log)

**Comment by emilengler** [comment]
I'm working on this now but unfortunately I cannot reproduce the issue

**Comment by emilengler** [comment]
I hope 4e7a61e7cade209e4e4410261bb9b5e3bdda18ad fixed it

**Comment by emilengler** [comment]
Ok, I looked a bit deeper in your site. The problem resides in your .xml file in the media directory. Could you remove the ampersand and replace it with a word? There was a bug in the past which didn't allowed special characters. Fixing this should do the trick!

**Comment by 0scubasteve0** [comment]
That solved it! Thanks so much for looking into it.

**Comment by emilengler** [comment]
No problem. I'm also working on a fix for this expected in the next released on the 31th of May this year :)
