### ISSUE TITLE
is there a way to remove download button?

### ISSUE THREAD

**Issue by smitzter** [PodcastGenerator/PodcastGenerator#261]
is there a way to remove download button?

**Comment by emilengler** [comment]
Yes, edit `themes/default/listepisodes.php` and remove line 27 and 28. Now put this line on line 27:

```
    echo '  <a class="btn btn-outline-primary btn-sm" href="' . $config['indexfile'] . '?' . $link . '=' . $item[$i]["episode"]["filename"] . '">' . $more . '</a>;
```

Then remove line 37 in `themes/default/singleepisode.php`

**Comment by smitzter** [comment]
Hi, Thank you. I was very careful and did exactly this but now the episodes are not visible at all.

**Comment by emilengler** [comment]
Ok, can you reset the files and then post the source of the files here? I will modify it for you so you just need to copy and paste the entire file
