### ISSUE TITLE
Password protecting the feed and front-end

### ISSUE THREAD

**Issue by nemosmithasf** [PodcastGenerator/PodcastGenerator#263]
**Description**
I use Podcast Generator mostly to host personal audio-files that I and a few friends can then access through the Podcast app via iPhone.

Due to their personal nature, it's ideal if there's a way to password protect access to the files. However, I don't believe this feature is currently supported by PodcastGenerator.

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by emilengler** [comment]
There is already a front-end protection added in 3.1 whcih will be released in 1 month.
However it is not possible to protect the feed without changing your webserver configuration instead I could add a way to disable the feed generation

**Comment by nemosmithasf** [comment]
Hey, just checking in to see if this was ever implemented?

I checked the demo site and I couldn't find any options for the front-end password.

Thanks!

**Comment by emilengler** [comment]
> Hey, just checking in to see if this was ever implemented?
> 
> 
> 
> I checked the demo site and I couldn't find any options for the front-end password.
> 
> 
> 
> Thanks!

Unfortunately the demo is outdated. You can find the option in the config.php after you installed Podcast Generator
