### ISSUE TITLE
Cover Art Will not update.

### ISSUE THREAD

**Issue by juhenriquez** [PodcastGenerator/PodcastGenerator#264]
**System Information**
Podcast Generator Version: 3.0.1 - Commit 57c4bf03b3ce05743b48d7e033622847cd63f252
Webserver: nginx/1.14.0 (Ubuntu)
PHP Version: php-fpm 7.2

**Podcast Generator Config**

```

Wasn't able to generate CENSORED config since tool doesn't seem to be working.
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**
UPDATE Image on cover art.

**Actual behavior**
When I go on to /PodcastGenerator/images I see itunes_image.jpg image has update to my uploaded image, in admin panel it keep's showing defualt cover art, which confuses end user.

![image](https://user-images.githubusercontent.com/8250019/81064576-ec198700-8ea7-11ea-9f5d-13b865fbdb03.png)

**How to reproduce**

**Comment by emilengler** [comment]
You should not run master. Please go to the release page and download 3.0.1 there https://github.com/PodcastGenerator/PodcastGenerator/releases/tag/v3.0.1

**Comment by computertalkradio** [comment]
This problem still exists in 3.0.1.  I just did a fresh install, and had to manually update the image.

**Comment by PeterAlfonsLoch** [comment]
Same issue here, it doesnt work I have release version

**Comment by PeterAlfonsLoch** [comment]
> This problem still exists in 3.0.1. I just did a fresh install, and had to manually update the image.

I tried disabling cache, and then it showed up.

**Comment by hallvors** [comment]
I'm just testing out PCG and I'm also seeing this issue. I can confirm it is a caching issue, showing the image and reloading fixes things. I suggest adding a random string to the URL for cache busting after an upload. You may also look at ETag / If-None-Match cache headers that should also fix the problem if applied (though I have not looked at the headers sent for this file).

**Comment by emilengler** [comment]
@hallvors Good idea, will do that
