### ISSUE TITLE
When I try to validate my xlm iTunes says my explicit tag is not there or empty but I can see it is in the XML feed.

### ISSUE THREAD

**Issue by saasnuthusk** [PodcastGenerator/PodcastGenerator#267]
**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

**Actual behavior**
 

**How to reproduce**

**Comment by emilengler** [comment]
Already fixed. New version will be deployed on the 31th of May

**Comment by PeterAlfonsLoch** [comment]
> Already fixed. New version will be deployed on the 31th of May

What is the issue?

**Comment by emilengler** [comment]
@PeterAlfonsLoch It used a variable name which does not exist. Therefore the field was empty in the feed and it was invalid

**Comment by rnjailamba** [comment]
@emilengler can you please tell the commit id of this fix.

**Comment by emilengler** [comment]
@rnjailamba PG 3.1 will come out today or next week depending on how fast the translators are.
To your question: I'm not entirely sure but a search guided me to these 4 commits: 5b08776a46e94bc1dff35cdd0645afa0e7a959d8 80b8a73c2d5fca7b569334e32a5dbec60628bf4e a1770507ce7a0185a3d620f0431c524b468139e0 7cdb1f0d3e9241f0fef80739929efeb729acbcc0

**Comment by rnjailamba** [comment]
@emilengler Thanks!

**Comment by rnjailamba** [comment]
I incorporated the changes in those commits and the podcast was submitted to iTunes for review successfully! @emilengler

**Comment by emilengler** [comment]
@rnjailamba Happy podcasting!
