### ISSUE TITLE
Missing Language: Luxembourgish

### ISSUE THREAD

**Issue by PeterAlfonsLoch** [PodcastGenerator/PodcastGenerator#268]
Could you please add Luxembourgish as a selection possibility for the main podcast language?

**Comment by emilengler** [comment]
I cannot speak this language but I added it to our transifex project.
If you or someone you know can speak english he/she can help to translate the project.
https://www.transifex.com/albertobeta/podcast-generator/language/lb/

**Comment by PeterAlfonsLoch** [comment]
> I cannot speak this language but I added it to our transifex project.
> If you or someone you know can speak english he/she can help to translate the project.
> https://www.transifex.com/albertobeta/podcast-generator/language/lb/

I did not ask to have the whole thing translated, just to have it in the selection list in the podcast info. so i can set the podcast to be in Luxembourgish.

**Comment by emilengler** [comment]
Oh sorry my fault :smile: 
In that case edit `admin/podcast_details.php` 
And add this to the long language section:
```
                <option value="lb">Luxembourgish</option>
```
