### ISSUE TITLE
Support Episode Specific Images

### ISSUE THREAD

**Issue by juhenriquez** [PodcastGenerator/PodcastGenerator#269]
**Description**
Support Episode Specific Images
**Motivation**
Customized Art per episode to be uploaded to spotify and other sources.
**Legal aspect**

* [x ] I am the inventor of this idea or the idea is public domain
* [x ] I release this idea into the public domain

**Comment by emilengler** [comment]
Will be released in 3.1 on 31th of May

**Comment by PeterAlfonsLoch** [comment]
Where is that function?

**Comment by emilengler** [comment]
Give an mp3 a cover
