### ISSUE TITLE
Step 3 Fatal Error

### ISSUE THREAD

**Issue by thebearddontlie** [PodcastGenerator/PodcastGenerator#271]
**System Information**
Podcast Generator Version: 3.0.1
Webserver: Linux
PHP Version: 5.3

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**
I cant get past this part of the setup
Fatal error: Call to undefined function password_hash() in /setup/createconf.php on line 28

**Comment by thebearddontlie** [comment]
I just updated my php to 5.6 and still same error

**Comment by emilengler** [comment]
Have you fixed it? PG requires a version of PHP 7.0 or higher

**Comment by thebearddontlie** [comment]
It kinda started working. But on the website it said required min php 5.3 which i had but i updated to php 5.6 and the error originally stated changed to a different error but it let me continue and i can log in now at least

Sent via the Samsung Galaxy Note10+, an AT&T 5G Evolution capable smartphone

________________________________
