### ISSUE TITLE
Editing the webpages

### ISSUE THREAD

**Issue by antonmarks123** [PodcastGenerator/PodcastGenerator#273]
Hi,
How can I add a menu on the webpage (Next to home and all epidodes and admin) and add pages to my website?
Can I open index.php in an html editing software and see the site as it looks?
I'd love to add program notes to each episode page.
I have coffeecup html editor but it doesnt display the site correctly.
Any help would be greatly appreciated.
I love the PodcastGenerator but would love to be able to add content to the website that it generates.
Thanks
Anton

**Comment by emilengler** [comment]
Hello Anton.
Currently there is no built in way on doing this.
I would create a new file in the base podcast generator directory called `programnotes.html`. There you can do all the HTML stuff like putting content into it and so on. After, go to `themes/default/navbar.php` and add this after line 19.
`            <li class="nav-item">
                <a class="nav-link" href="programnotes.html">Program Notes</a>
            </li>`

Keep in mind that you need to change this every time you upgrade to a new version of Podcast Generator

**Comment by antonmarks123** [comment]
Thanks so much for your help, but I can't find a navbar.php file in any of my theme folders.
I have the latest version of your generator.
I'm actually using exposure as the theme.
Thanks again
![podcast](https://user-images.githubusercontent.com/54483421/82732035-60ab4d00-9d13-11ea-9a38-dd50fc959415.png)

**Comment by antonmarks123** [comment]
![kol](https://user-images.githubusercontent.com/54483421/82732858-afa7b100-9d18-11ea-857e-2cf8fd585774.png)

Is it named something else?

**Comment by antonmarks123** [comment]
![kol3](https://user-images.githubusercontent.com/54483421/82733646-e16f4680-9d1d-11ea-9632-738a8774593c.png)

This is the index.htm file that is in the theme folder of the theme that I am using. Can I add the new menu here somehow?

**Comment by emilengler** [comment]
Oh you use version 2.7?
I can't help you with that, sorry

**Comment by coldacid** [comment]
Custom pages is on the roadmap for version 3.3, see #470
