### ISSUE TITLE
Error 'missing fields' for upload form

### ISSUE THREAD

**Issue by bassport** [PodcastGenerator/PodcastGenerator#274]
**System Information**
Podcast Generator Version: 3.0.1
Webserver: 1and1
PHP Version: 7.3

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
<?php

$podcastgen_version = "3.0.1"; // Version

$first_installation = 1590472828;

$installationKey = "Qcjqoq0E";

$scriptlang = "en_US";

$url = "http://bpfm.responsiveaudio.co.uk/subvert/PodcastGenerator/";

$absoluteurl = "/homepages/28/d413840903/htdocs/bpfm/subvert/PodcastGenerator/"; // The location on the server

$theme_path = "themes/default/";

$feed_iTunes_LINKS_Website = "http://bassport.fm/”;

$username = "subvert";

$userpassword = "\$2y\$10\$uEMukOPzHM3zywC96PQ1K.9grz6TJ76ToYN45TJ6yRRIFdQ87NCd6";

$max_upload_form_size = "472320000"; //e.g.: "30000000" (about 30MB)

$upload_dir = "media/"; // "media/" the default folder (Trailing slash required). Set chmod 755

$img_dir = "images/"; // (Trailing slash required). Set chmod 755

$feed_dir = ""; // Where to create feed.xml (empty value = root directory). Set chmod 755

$max_recent = 4; // How many file to show in the home page

$recent_episode_in_feed = "All"; // How many file to show in the XML feed (1,2,5 etc.. or "All")

$episodeperpage = 10;

$enablestreaming = "yes"; // Enable mp3 streaming? ("yes" or "no")

$freebox = "no"; // enable freely customizable box

$enablepgnewsinadmin = "yes";

$strictfilenamepolicy = "yes"; // strictly rename files (just characters A to Z and numbers) 

$categoriesenabled = "yes";

$cronAutoIndex = 1; //Auto Index New Episodes via Cron

$cronAutoRegenerateRSS = 1; //Auto regenerate RSS via Cron

#####################

# XML Feed stuff

$podcast_title = "Subvert Podcast on Bassport.FM";

$podcast_subtitle = "Drum & Bass radio show from Subvert Promotions on Bassport.FM";

$podcast_description = "Drum & Bass radio show from Subvert Promotions on Bassport.FM";

$author_name = "Subvert";

$author_email = "podcasts@bassport.fm";

$itunes_category[0] = "Music"; // iTunes categories (mainCategory:subcategory)

$itunes_category[1] = "null";

$itunes_category[2] = "null";

$link = "?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

$feed_language = "en";

$copyright = "Licensed with PPL & PRS";   // Your copyright notice (e.g CC-BY)

$feed_encoding = "utf-8";

$explicit = "yes"; //does your podcast contain explicit language? ("yes" or "no")

// END OF CONFIG





**Description of your problem:**

Error 'missing fields' is returned for upload form, when all form fields are complete. Filename requirements are adhered to, and I have attempted full re-install of podcast generator (twice). I host numerous instances of podcast generator on my server. For x2 this is a persistent issue, while others function as expected.

Screenshot is of form as it was submitted.


![Screen Shot 2020-05-26 at 08 12 10](https://user-images.githubusercontent.com/65942799/82870929-a55c0180-9f28-11ea-966c-2456927cdbfb.png)

**Comment by emilengler** [comment]
Have you actually selected a category?

**Comment by bassport** [comment]
Yes

> Have you actually selected a category?

**Comment by emilengler** [comment]
Which are browser are you using? Maybe try a different one

**Comment by denisveneno** [comment]
I'm having this same problem, I've tested it on firefox, chrome and on the edge, and they all have the same "missing fields" error

**Comment by emilengler** [comment]
Could you give me the mp3 file you are trying to upload and a screenshot before the error occurred? it should be done quickly as I need to release 3.1 Sunday

**Comment by denisveneno** [comment]
this is the mp3 file -> https://drive.google.com/file/d/1_dmqGd2poYz7vPaUHkq_huNgWA9rGcls/view?usp=sharing 

and the Error image
![image](https://user-images.githubusercontent.com/7849321/83290604-3ea34600-a1bd-11ea-9a32-2c984c12be0b.png)

**Comment by emilengler** [comment]
You don't have filled the title, nor short descripton nor a category

**Comment by denisveneno** [comment]
Yes I did, but when I click on the upload button it returns to this page with the fields cleared and this "missing fields" error at the top

**Comment by bassport** [comment]
Perhaps this user has absent fields but I did not. I have tried this over and over again. It seems to happen with some installations of Podgen, but not others. I am administering an entire (non commercial) podcast network with over a dozen functioning installations of podgen. If you would like to gain full access in order to troubleshoot these for yourself please email be on iain at bassport dot fm - thanks

**Comment by emilengler** [comment]
Also in your config, the $feed_iTunes_LINKS_Website is closed wrong. You have an illegal '"' character there

**Comment by ugurarici** [comment]
In my case it's because of http timeout. I use cloudflare on website and it's http timeout limit is 100 seconds. After that it returns 524 timeout and reloads the page. So, request is sent with GET method with an empty $_POST. But on [line 13 of episodes_upload.php](https://github.com/PodcastGenerator/PodcastGenerator/blob/master/PodcastGenerator/admin/episodes_upload.php#L13) it checks if url has a query string named 'upload'.

Of course there is a ?upload=1 in url but there isn't posted on that page.

So, to make sure it isn't a false check on posted data, I changed this;

`if (isset($_GET['upload'])) {`

to this:

`if (count($_POST) > 0) {`

and o[n line 212](https://github.com/PodcastGenerator/PodcastGenerator/blob/master/PodcastGenerator/admin/episodes_upload.php#L212) deleted to action="..." completely.

Now I'm sure if it says "Missing fields" it's surely because of a missing field. Not because of there is an ?upload=1 in the url.

**Comment by emilengler** [comment]
Hello @ugurarici, thanks for your contributions. It is helpful and I will add it!

**Comment by emilengler** [comment]
I made a commit to fix this and added you as a co author, hope it is ok :)

**Comment by ugurarici** [comment]
Thank you, it's very kind of you :)

**Comment by bassport** [comment]
Hi, would it be possible for you to clarify the line 212 edit with "from" and "to" example as with the other one please? Want to see if this will fix the issue before swamping Emil with this many installs of podgen lol

**Comment by emilengler** [comment]
> Hi, would it be possible for you to clarify the line 212 edit with "from" and "to" example as with the other one please? Want to see if this will fix the issue before swamping Emil with this many installs of podgen lol

I'm not entirely sure what you mean but instead of checking for a specific value in the URL in determines if data was sent and starts then
