### ISSUE TITLE
Location: redirect must be before markup output

### ISSUE THREAD

**Issue by hallvors** [PodcastGenerator/PodcastGenerator#275]
On registering a new site I get this:

![Skjermdump fra 2020-05-27 02-20-39](https://user-images.githubusercontent.com/120136/82962515-b7897e80-9fc0-11ea-89b2-5448acd00f92.png)

The lines setting Location: header to redirect must be moved up to before line 38 where the markup starts: 
https://github.com/PodcastGenerator/PodcastGenerator/blob/master/PodcastGenerator/setup/step3.php#L71-L75

**Comment by emilengler** [comment]
Sure, makes sense forgot that.
Thanks for the report!
