### ISSUE TITLE
Expose the file size upload limits of the PHP configuration

### ISSUE THREAD

**Issue by hallvors** [PodcastGenerator/PodcastGenerator#276]
On upload the form informs me that *Your server configuration allows you to upload files up to around 105 MB.*. On this plain vanilla install, php.ini does actually limit the size of a POST request to 8M, the 105 MB value seems to be an internal PCG setting.

Submitting something larger than PHP accepts will cause a truncated POST request, and a most confusing "Missing values" error without context because PHP truncates away data like title.

I suggest using this:

ini_get('post_max_size')

to get and inform the users of the actual limit(s).

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by emilengler** [comment]
Thanks, I already removed that "feature" in the following 3.1 built as it only causes problems
