### ISSUE TITLE
Apple Podcast Connect refuses XML: "There is no category tag in your feed, or the category tag is empty."

### ISSUE THREAD

**Issue by MatteAce** [PodcastGenerator/PodcastGenerator#277]
**System Information**
Podcast Generator Version: 3.01
Webserver: Apache
PHP Version: 7.4

**Expected behavior**
Podcast Connect should accept the feed.xml file

**Actual behavior**
Podcast Connect opens the XML file correctly, shows the episodes, but a red message above tells this: "Can’t submit your feed. There is no category tag in your feed, or the category tag is empty."
The XML file has the following lines in it:

 <itunes:category text="Music:Music Interviews"></itunes:category>
		<itunes:category text="Music:Music Commentary"></itunes:category>
		<itunes:category text="null"></itunes:category>

**How to reproduce**
I inputted my feed.xml URL into my Apple Podcast Connect account

**Comment by MatteAce** [comment]
Filling out the third, empty category in Podcast Generator -> Change Podcast Category and rebuilding the RSS feed fixed the issue.

**Comment by emilengler** [comment]
So you no longer have a problem?

**Comment by MatteAce** [comment]
I don't have that problem anymore, but I do think the backoffice is bugged since it allows to specify blank categories. I was on a fresh install.

**Comment by emilengler** [comment]
Ok I will have a look at this tomorrow
