### ISSUE TITLE
Episode Image with itunes:image tag

### ISSUE THREAD

**Issue by moemueller** [PodcastGenerator/PodcastGenerator#279]
Hi, first of all I really love PodcastGenerator, at least the idea because I'm running in some issues. I have just found it last night and I am testing it today and I really need one feature to make it really worth for me. 

It would be awesome if there is an option to upload or select an image for an episode cover with the itunes:image tag. If there is a workaround for this please let me know!

Good job on PodcastGenerator anyway, it's exactly what I'm looking for!

**Comment by emilengler** [comment]
Podcast Generator 3.1 which will be released on Sunday probably has such a feature

**Comment by chrisdoth2** [comment]
We've just updated to 3.1.1 and I can't see any image upload feature for the episode. 

The old episode covers we'd been adding manualy also got broken in the updgrade. In the feed they now all are linked like

`<itunes:image href="1"/>`

For some reason. I'm not sure if its related to this bug report but if the feature were there to manualy fix these then we could go back and update each episode and hopefully get the episode covers showing again.

**Comment by emilengler** [comment]
Can you provide a screenshot of the media and images directory?
