### ISSUE TITLE
How do I change the episode-specific artwork?

### ISSUE THREAD

**Issue by MatteAce** [PodcastGenerator/PodcastGenerator#281]
I've upgraded to 3.1, in the release notes there's a mention to the upload of episode-specific artwork. I can't find anything in the Edit Episode menu. How do I add artwork for each episode? Thank you.

**Comment by emilengler** [comment]
It is a bit tricky. You need to edit your mp3 file with a so called mp3 tag editor. With this one you can set an image directly into the mp3 file which PG will extract then.
You can find a youtube tutorial about this here: https://www.youtube.com/watch?v=aDlP9kYz5r0

**Comment by MatteAce** [comment]
ok so, I uploaded a new episode with the image in the mp3 tag and everything worked out fine. Now I want to also reupload the old episodes, I tried replacing the files using the same filename and manually reindexing but podcast generator won't find them, and the episode-specific xml file contains no data about the image. I've seen though that PG extracts the episode image in the images folder, should I just add the image I need there?

**Comment by emilengler** [comment]
@MatteAce 
You have two ways:
Deleting the old episodes and reuploading them with the normal episodes upload feature
Delete all XML files of the old episodes and then re-index. Keep in mind that this will delete all titles, descriptions, etc.

Be sure to make a backup before

**Comment by MatteAce** [comment]
I’ve deleted one xml file, the episode disappeared. I’ve reindexed with the FTP Feature and now it can’t find the mp3 anymore.

**Comment by emilengler** [comment]
This sounds strange, can you try to reupload the file instead?

**Comment by MatteAce** [comment]
I’ve fixed the issue by renaming the files to something different.

So the whole procedure was:

1) download the old file without album art
2) insert the artwork in the ID tag
3) upload and overwrite the new file
4) delete the episode’s xml file
5) slightly change the mp3 file name
6) start the FTP auto indexing

**Comment by emilengler** [comment]
Ok, if it works then it's great :)

**Comment by MatteAce** [comment]
I’ve written the whole procedure so if somebody got the same issue as me, while you fix it, can still find an easy solution without waiting for an answer.
