### ISSUE TITLE
Possible to add 4th Menu item for end user podcast page?

### ISSUE THREAD

**Issue by R2D2C3POOU812** [PodcastGenerator/PodcastGenerator#288]
**System Information**
Podcast Generator Version: 3.1
Webserver: Litespeed 5.4.7
PHP Version: 7.2.30

**Podcast Generator Config**

```

<?php

$podcastgen_version = "3.1"; // Version

$first_installation = 1591576989;

$installationKey = "CENSORED";

$scriptlang = "en_US";

$url = "https://podcast.xxx.ca/PodcastGenerator-3.1/PodcastGenerator/";

$absoluteurl = "/home/xxx/xxx.ca/PodcastGenerator-3.1/PodcastGenerator/"; // The location on the server

$theme_path = "themes/default/";

$upload_dir = "media/"; // "media/" the default folder (Trailing slash required). Set chmod 755

$img_dir = "images/"; // (Trailing slash required). Set chmod 755

$feed_dir = ""; // Where to create feed.xml (empty value = root directory). Set chmod 755

$max_recent = "all"; // How many file to show in the home page

$recent_episode_in_feed = "All"; // How many file to show in the XML feed (1,2,5 etc.. or "All")

$episodeperpage = 10;

$enablestreaming = "yes"; // Enable mp3 streaming? ("yes" or "no")

$freebox = "yes"; // enable freely customizable box

$enablepgnewsinadmin = "yes";

$strictfilenamepolicy = "no"; // strictly rename files (just characters A to Z and numbers) 

$categoriesenabled = "yes";

$cronAutoIndex = 1; //Auto Index New Episodes via Cron

$cronAutoRegenerateRSS = 1; //Auto regenerate RSS via Cron

$indexfile = "index.php";    // Path of the index file

$podcastPassword = "";       // Password to protect the podcast generator webpages, this will NOT protect the audio or XML files. Leave blank to disable.

#####################

# XML Feed stuff

$podcast_title = "THIS SECTION IS CENSOREDt";

$podcast_subtitle = "THIS SECTION IS CENSORED";

$podcast_description = "THIS SECTION IS CENSORED";

$author_name = "THIS SECTION IS CENSORED";

$author_email = "THIS SECTION IS CENSORED";

$itunes_category[0] = "THIS SECTION IS CENSORED"; // iTunes categories (mainCategory:subcategory)

$itunes_category[1] = "THIS SECTION IS CENSORED";

$itunes_category[2] = "THIS SECTION IS CENSORED";

$link = "?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

$feed_language = "en";

$copyright = "All rights reserved";   // Your copyright notice (e.g CC-BY)

$feed_encoding = "utf-8";

$explicit_podcast = "no"; //does your podcast contain explicit language? ("yes" or "no")

$users_json = "{\"THIS SECTION IS CENSORED\": \"\$2y\$10\$BbBA5.MGzlzbhA5ukXu8v.0JTWspZM2Wyo6CVsTITNfRBQw/Ufou2\"}";

// END OF CONFIG

INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**

If I wanted to add an item to the menu in the end-user podcast page, would there be a fairly simple way to add it? 

So currently there's "Home, Categories, and Admin" 

Could I add a 4th menu item?

I'm guessing there is a ul tag somewhere within the body of a file. I'm only slightly familiar with CSS and HTML. Not familiar with bootstrap or PHP or jquery but perhaps if this was feasible you could help me write code to add it?

![Custom Menu Item](https://user-images.githubusercontent.com/66576550/85186414-de0ca380-b266-11ea-940f-5bd6df71d844.png)

**Comment by R2D2C3POOU812** [comment]
Update: If it's easy to add the menu item, all I want to add to it is a link that takes me to my primary domain homepage (or any other page on my domain if I decide to change it.)

**Comment by emilengler** [comment]
Currently there is no such way except if you would "code" it for yourself in.
You only very basic HTML skills. If so, you can edit themes/default/navbar.php

**Comment by R2D2C3POOU812** [comment]
Ok, I think I managed to do it, with your description of the file location. 

I added this line of code to the navbar.php file just below the admin li tag : 
```
</li>
            <li class="nav-item">
                <a class="nav-link" href="https://rateraiders.ca/" target="_blank">RateRaiders</a>
            </li>
```

I know this is a kindergarten HTML, but as I said before I'm super new to this world of coding. Previously I was a music teacher. 

Everything seems functional including the link when I checked it on mobile and desktop. So I'm guessing that's it?

 No other code elsewhere is necessary?

**Comment by ryangurn** [comment]
I think that would work! @R2D2C3POOU812, HTML is my least favorite thing in the world so the comparison to kindergarten seems to be fitting since its mainly babysitting. lol

**Comment by emilengler** [comment]
> No other code elsewhere is necessary?

Nope thats it, but you'll need to adjust it every time you update Podcast Generator unfortunately.

**Comment by R2D2C3POOU812** [comment]
Thanks boys. You rock!
