### ISSUE TITLE
Update to 3.1 breaks the RSS feed

### ISSUE THREAD

**Issue by joerg-nafcom** [PodcastGenerator/PodcastGenerator#294]
When I upgrade from last version to 3.1 I get this error:

The URL does not appear to reference a valid XML file. We encountered the following problem: Error on line 33: The entity name must immediately follow the '&' in the entity reference.

I tried it with the <![CDATA data tags removed and without in the episode xm files, didn't make a difference. (see https://github.com/PodcastGenerator/PodcastGenerator/issues/210)

In the end the only solution was reverting back to 3.0 and now as I removed the ![CDATA tags in the ones of podcastgen2.7 in those episodes where quotes deface the name in the rss feed, do now display correctly 3.0

Why the 3.1 update breaks the RSS feed for me I have no idea.

**Comment by emilengler** [comment]
Can you give me the broken rss feed and the related XML episode files?

**Comment by joerg-nafcom** [comment]
sure, if you let me know how to download the xml feed I will do that. I tried with a couple of browsers but they only would give me the option to display the rss feed but not save it as a file.

Once I know what line 33 is I can give you the xml files accordingly.

**Comment by joerg-nafcom** [comment]
attached the feed.xml podcastgen 3.1 created in comparasion the one that causes the error
[feed.zip](https://github.com/PodcastGenerator/PodcastGenerator/files/4841019/feed.zip)

**Comment by emilengler** [comment]
Turns out it was because of malformatted XML files.
Solved within a private mail conversation.
