### ISSUE TITLE
Auto-Indexing new episodes broken in 3.0.1 and 3.1

### ISSUE THREAD

**Issue by joerg-nafcom** [PodcastGenerator/PodcastGenerator#296]
found out that the Auto index feature broken in 3.0: I tried uploading an episode via ftp and normally I would click "auto index" and it would automatically find it and generate the fitting xml file along with it. However it said "found!" in green letters. then went at "edit episode" page but there was no new entry there.
 
Then I delted the /media/index.html and 2020-06-27 file as they appear to have 0 bytes.
Now the function auto index does not even run anymore and is stuck endlessly.
 
If I copy back the index.htm from a backup it unstuck the auto-indexing feauture but still the newly added mp3 is not found.

In 3.1 it is even worse, it will simply say "no new files found".

As the file is too big for github, I sent the MP3 to you via WeTransfer now.

**Comment by emilengler** [comment]
I tried it with your file on version 3.1 and it worked without any problems.
For the record: I use nginx on Debian 10 with PHP 7.3 and without any big modifications except a huge upload limit

**Comment by joerg-nafcom** [comment]
so what to do now? I am on 3.1 now and whatever I do it's stuck with "FTP Auto Indexing
No new episodes were found"

**Comment by joerg-nafcom** [comment]
I got the following info from our webhost today:
"On the server side there's CentOS 7, with Apache 2, PHP 7.3, standard upload limit on PHP.ini"

I am still waiting for the log file

**Comment by emilengler** [comment]
Hmm. Autoindexing should not effect the upload limit. I am actually really curious. I will have a look at this later on

**Comment by joerg-nafcom** [comment]
I was also told, there was no valuable info or error / warnings in any of the server logs regarding the indexing.

All I get is this:

![image](https://user-images.githubusercontent.com/16625923/87060792-38b47200-c20b-11ea-8832-ca87b507e351.png)


The webserver admin had a look while I was triggering the auto-index functionality in the admin panel

**Comment by joerg-nafcom** [comment]
Update: Our webhost did update to PHP 7.4 yesterday. still not working and still nothing written in any logs.

**Comment by joerg-nafcom** [comment]
Good news: With the work of our webhoster I have got it working but this is still because of major issues with the Podcast Generator.

Our webhoster had to change:

1) Apache variable (namely FcgiMaxRequestLen)
2) for bug #297: " there's another variable in PHP post_max_size that fails when you upload via the form"

This resulted into error message "Invalid filename, only A-Z, a-z, underscores and dots are permitted"

I tried with renaming the file to "Holger" before our webhost did the change 1), so the auto-index ignored the new file because of too low setting in 1) despite the file name had no signs or German umlauts.

So, 1) should be written in the documentation and the nationalized characters should be supported. Our webhoster said 1) wasn't changed for Podcast Generator 2.7 and it worked regardless.

You should make sure UTF-8 (Unicode) is supported with Podcast Generator. The original filename of the MP3 was "Holger Weßling"-

**Comment by dskeen** [comment]
i ran into this exact same problem.  i have always named my files (for example) 7-12-20.mp3.   PG no longer will detect those on an FTP auto index.  after reading this thread, i changed the file name to 7_12_20.mp3 and it found the file.  a bit annoying that it will find underscore, but not dash.

**Comment by ryangurn** [comment]
Please review what was determined for #297 I think this has to do with configs. 

> It occurs to me that you can go into config.php and change $strictfilenamepolicy to "no" and it will allow for your file names to be utf-8 and include dashes. There is no code adjustment needed. Please give this a shot and let me know how it goes.

**Comment by ryangurn** [comment]
@dskeen the issue with the dash should be solved at this point, just waiting for a review from the rest of the PG team.

@joerg-nafcom I do not know that you will be able to use a file name such as "Holger Weßling.mp3" because "ß" is a non ascii character so in general, now it will be replaced by a question mark ("?"). There are many resources online that explain the complexity with using non ascii characters, but I will continue to look for a better way to handle this. For now the changes will ensure that you can use ascii characters that conform to UTF-8 standards and other symbols that are not supported will be converted to another ascii representation by the upload script.
