### ISSUE TITLE
manually uploading MP3 files not possible in 3.0.1. and 3.1

### ISSUE THREAD

**Issue by joerg-nafcom** [PodcastGenerator/PodcastGenerator#297]
As auto-indexing stopped working for me (see #296), I tried with manually adding the episode via upload within the admin panel  as the file size is below 105 MB  but I do get then
 
ERROR 500 - Internal Server Error!
The following error occurred:
The requested URL caused an internal server error.
 
If you get this message repeatedly please contact the webmaster.

As the file is too big for github, I sent the MP3 to you via WeTransfer now.

**Comment by emilengler** [comment]
A 500 error is a thing of your web server not from our side.
Can you post your error log and the name of your web server?

**Comment by joerg-nafcom** [comment]
log file from the web server I suppose or does podcastgenerator has its own logfile? if not,  then I gotta ask our webhoster for that first.

**Comment by emilengler** [comment]
> log file from the web server I suppose or does podcastgenerator has its own logfile? if not, then I gotta ask our webhoster for that first.

No we don't usually every webserver has it's own

**Comment by joerg-nafcom** [comment]
I got the following info from the webhoster today:

"Please, let them tell you which is the limit and the parameter name they are using on php.ini (should be max_upload_size)
 and the value of course "

I am still waiting for the log file

**Comment by emilengler** [comment]
The max_upload_size setting got removed in 3.1 btw

**Comment by joerg-nafcom** [comment]
They said they checked the general php.ini settings and find no cause there,
There is also not anything in any server logs that would indicate why it throws an internal server error.
They had a look at the webserver logs while I was uploading the MP3 file via the GUI.

![image](https://user-images.githubusercontent.com/16625923/87061252-d019c500-c20b-11ea-92b1-a1da97dd8b8a.png)

**Comment by joerg-nafcom** [comment]
Update: Our webhost did update to PHP 7.4 yesterday. still not working and still nothing written in any logs.

**Comment by joerg-nafcom** [comment]
Update 2: Good and bad news. 

Bad news: The upload still doesn't work.  internal server error anymore but the file is not uploaded anywhere it simply stops and no upload is done or a new entry is created.

Good news: The webhoster found why it threw an internal server error. "found a problem with an Apache variable (namely FcgiMaxRequestLen)."

However the main problem remains, the upload is not possible still.

**Comment by joerg-nafcom** [comment]
Good news: With the work of our webhoster I have got it working but this is still because of major issues with the Podcast Generator.

Our webhoster had to change:

1) Apache variable (namely FcgiMaxRequestLen)

2) "variable in PHP post_max_size that fails when you upload via the form"
This resulted into error message "Invalid filename, only A-Z, a-z, underscores and dots are permitted"


So, 1) and 2) should be written in the documentation and the nationalized characters should be supported.

You should make sure UTF-8 (Unicode) is supported with Podcast Generator. The original filename of the MP3 was "Holger Weßling.mp3"

Normally, our files are named like "Holger Weßing_Scene World_interview_59.mp3" and that worked in PodcastGenerator 2.7

**Comment by emilengler** [comment]
Ok, I will work on this!

**Comment by joerg-nafcom** [comment]
great! Don't forget to add #296 to the milestone too, please

**Comment by ryangurn** [comment]
@joerg-nafcom so at this point, are you able to upload the files with the increased FcgiMaxRequestLen and post_max_size? It seems as though the national characters and dashes are now the issue correct?

@emilengler Would there be a reason that we are not allowing dashes (-) or national characters up until this point?

**Comment by joerg-nafcom** [comment]
ryan, you are 100% correct in your assumptions.

**Comment by ryangurn** [comment]
ok, so here is my order of operations for getting this fixed. 

1. Address the issues with uploading files that contain "-"
2. Ensure that UTF-8 is being properly supported for file names.

**Comment by joerg-nafcom** [comment]
seems good to me

**Comment by ryangurn** [comment]
I will get to #296 at some point it is just being held up by a bit more that I need to research.

It occurs to me that you can go into `config.php` and change `$strictfilenamepolicy` to "no" and it will allow for your file names to be utf-8 and include dashes. There is no code adjustment needed. Please give this a shot and let me know how it goes.

**Comment by joerg-nafcom** [comment]
I will have to ask our webhoster for that, this can take a while

**Comment by ryangurn** [comment]
I have tested it and it appears to work, give it a shot and let me know what happens. Please be sure to use @ryangurn to send me a ding.

**Comment by emilengler** [comment]
> @joerg-nafcom so at this point, are you able to upload the files with the increased FcgiMaxRequestLen and post_max_size? It seems as though the national characters and dashes are now the issue correct?
> 
> @emilengler Would there be a reason that we are not allowing dashes (-) or national characters up until this point?

I am not exactly sure on this but I think UTF-8 characters are allowed if strictfilenames is disabled in the configuration

**Comment by ryangurn** [comment]
@emilengler they are allowed, I am perfectly fine with you closing the PR if we do not want to make adjustments to the configuration. I was able to test and if it is disabled this should all work normally. 

Let me know what you decide with this config option, remove it entirely or something else.

**Comment by hughwilliams94** [comment]
I am using nginx and php 7.4 and can't get any large uploads  to work (auto or manual). I have tried tweaking all of the php upload vars, but it isn't working. Small files (created using `head -c 6MB /dev/urandom > a.mp3`) work OK, but similarly named real mp3's of roughly the same size fail.

**Comment by emilengler** [comment]
Could you give me the failing mp3 file?
