### ISSUE TITLE
page navigation not working

### ISSUE THREAD

**Issue by mishcazzulani** [PodcastGenerator/PodcastGenerator#299]
hello,
it seems page navigation is not working in the last version. 
i have a podcast with hundreds interviews (podcastgen.radioveg.it) but pg 3.1 only shows the first page
at the bottom of the page i only have the number "1" 
if i force the url with for example ?page=2 nothing appears

**Comment by emilengler** [comment]
Can you post your config.php?

**Comment by mishcazzulani** [comment]
oh thank you so much! you pointed me in the right direction, i had a limit of 10 episodes in the config.php now everything works like a charm.
