### ISSUE TITLE
uppercase and lowercase filename

### ISSUE THREAD

**Issue by mishcazzulani** [PodcastGenerator/PodcastGenerator#300]
hello
in the previous version i was using (2.7) despite the filename being written in uppercase or lowercase, when uploaded it was converted to lowercase, keeping the media library nice and tidy.
in 3.1 this has not been implemented, and if i upload a .MP3 file instead of .mp3 it gives a wrong extension error.
i suggest to re-implement the case conversion option!

**Comment by emilengler** [comment]
Sorry for my late reply. This is indeed a serious bug. I am working on this right now
