### ISSUE TITLE
Adding Episodes for Future play

### ISSUE THREAD

**Issue by rodarkcompass** [PodcastGenerator/PodcastGenerator#301]
I have created a ne podcast feed and I've added three episodes with future dates.
The XML is created beside the files, no problem there, but I'm not seeing them in the episodes list.
Am I doing anything wrong here?

**Comment by emilengler** [comment]
They will appear once the date was reached

**Comment by rodarkcompass** [comment]
Thanks, and If I need to edit them beforehand, is that a manual change in the xml?

**Comment by emilengler** [comment]
Yes

**Comment by rodarkcompass** [comment]
Thanks, appreciate it.
