### ISSUE TITLE
wrong re-direction after submitting an edit on a podcast episode

### ISSUE THREAD

**Issue by joerg-nafcom** [PodcastGenerator/PodcastGenerator#302]
**System Information**
Podcast Generator Version: 3.1
Webserver: Apache 
PHP Version: 7.3

Found out, when I save an edited  episode, it redirect the homepage to an invalid URL e.g. https://sceneworld.org/history/index.php$url."?name=2020-07-12-Holger.mp3

Rather than https://sceneworld.org/history/ where it came from

**Comment by emilengler** [comment]
What is your $link value in your config.php

**Comment by joerg-nafcom** [comment]
`$link = "$url."?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)`

**Comment by emilengler** [comment]
Change it to
```php
$link = "?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)
```

**Comment by joerg-nafcom** [comment]
that fixed it ,thanks!

**Comment by ryangurn** [comment]
@joerg-nafcom if things are working, would you mind closing this issue?

**Comment by emilengler** [comment]
I will do this now, let me know if the problem still exists
