### ISSUE TITLE
quotation sign defaces after edit of an entry.

### ISSUE THREAD

**Issue by joerg-nafcom** [PodcastGenerator/PodcastGenerator#304]
**System Information**
Podcast Generator Version: 3.1
Webserver: Apache
PHP Version:7.3

When this:

![image](https://user-images.githubusercontent.com/16625923/87290708-9fcd7180-c4fe-11ea-807c-e1afdcf7cd75.png)

Is edited in Admin mode and I am simply hitting "Save" without changing anything, it defaces to this:

![image](https://user-images.githubusercontent.com/16625923/87290773-b4aa0500-c4fe-11ea-92a4-3faf9be88e59.png)

**Comment by ryangurn** [comment]
@joerg-nafcom ah it appears that we are escaping quotes to protect against some sort of SQL injection. 

I think we will need to find a creative way to ensure that this is properly fixed. Thanks for the report!

**Comment by emilengler** [comment]
> @joerg-nafcom ah it appears that we are escaping quotes to protect against some sort of SQL injection.

No, we don't use any SQL at all, although I thought about switching to an SQLite database in the future

**Comment by ryangurn** [comment]
oops @emilengler i mean html injection oops.

**Comment by emilengler** [comment]
Yes I think this causes the problem

**Comment by ryangurn** [comment]
I will take a look and push a PR for adjusting this!

**Comment by ryangurn** [comment]
@joerg-nafcom so initially the data is added in correctly, and then upon updating it we get the "&quote"?

**Comment by ryangurn** [comment]
I hope that the title is the only place where this is needed since that is the only place where I allowed for html special chars. @joerg-nafcom please let me know if that will suffice, we are trying to ensure that there is some level of security so that html code cannot be executed by the browser accidentally.

**Comment by emilengler** [comment]
This was fixed due to great work by @ryangurn!

**Comment by joerg-nafcom** [comment]
Hi Ryan,

exactly!

I am sorry I didn't reply to this in time. I saw the notifcations but am super busy with Gamescom livestream this weekend.

https://now.gamescom.global/area/retro.html

Glad you've got this fixed, thank you! :)

Cheers!
Joerg


On Sun, 30 Aug 2020 07:39:44 +0200, Ryan Gurnick <notifications@github.com> wrote:

>
> @joerg-nafcom so initially the data is added in correctly, and then upon updating it we get the "&quote"?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.



--
Using Opera's revolutionary e-mail client: https://en.wikipedia.org/wiki/Opera_Mail
--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------
DON'T SEND FILES BIGGER THAN 4 MB! THANKS!
(send to joerg.droege@gmail.com instead).
--------------------------------------------------------------------------------------------
Want to send to my iPhone? Use nafcom@games.com - thanks!
--------------------------------------------------------------------------------------------

**Comment by ryangurn** [comment]
@joerg-nafcom my pleasure, I will most likely be commenting on your other bug reports to get those squashed also. It was a pleasure.
