### ISSUE TITLE
vimeo integration

### ISSUE THREAD

**Issue by mdifilm** [PodcastGenerator/PodcastGenerator#307]
**Description** I was wondering if there is a way I can connect my vimeo account info so I don't have to host the media files on my own server?

**Motivation**

**Legal aspect**

* [ ] I am the inventor of this idea or the idea is public domain
* [ ] I release this idea into the public domain

**Comment by emilengler** [comment]
There is a feature to use an external resource as a media file in podcast generator. However you NEED the DIRECT link to the mp4 video. Vimeo hides this AFAIK

**Comment by mdifilm** [comment]
Thanks I actually have the direct link url from vimeo that I can grab,... so just add that link when adding a new podcast?

**Comment by emilengler** [comment]
I explained this in #308.
You need to upload the episode first but you can delete it thereafter

**Comment by mdifilm** [comment]
Thank you!
