### ISSUE TITLE
Keep losing my podcast cover art everytime i upload a new episode

### ISSUE THREAD

**Issue by dskeen** [PodcastGenerator/PodcastGenerator#309]
**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**
guessing im doing something wrong, but im not sure what. i have the same cover art embedded in my mp3 files that matches the cover art for the entire podcast.  everytime i upload a new episode,  i end up with 2 episodes. one is just the album art only, the other is the actual mp3 files and somewhere in the process the album art for the entire podcast is removed.  ive tried uploading the mp3 with no embedded album art, however that also seems to remove the album art for the entire podcast.  not sure what im doing wrong. every week i have to go back in and fix the album art for the entire podcast.  i have 2 different PG sites, and both of them are doing the same thing.

**Comment by emilengler** [comment]
What do you mean with two different episodes, two mp3 files where only one has the cover art?

**Comment by dskeen** [comment]
One is the mp3 file. The other is only album art. Nothing else.

Sent from my iPhone

On Aug 2, 2020, at 9:23 AM, Emil Engler <notifications@github.com> wrote:

﻿

What do you mean with two different episodes, two mp3 files where only one has the cover art?

**Comment by emilengler** [comment]
Both in the media/ directory?

**Comment by dskeen** [comment]
Yes. It’s creating a “file name”-itunes_image.jpg and .xml for every mp3 file i upload

Sent from my iPhone

On Aug 2, 2020, at 12:14 PM, Emil Engler <notifications@github.com> wrote:

﻿

Both in the media/ directory?

**Comment by emilengler** [comment]
What is your config.php?

**Comment by senarvi** [comment]
After upgrading to version 3.1, I have the same problem. The cover art .jpg file is now copied to the media directory. They used to be in images. The old cover art images are not found, unless I move them to the media directory too. If they are in the media directory, they appear correctly in the episode, but for each episode there appears also an additional "episode" that displays the cover art and the short description, but doesn't have the option to play the mp3 file.

**Comment by senarvi** [comment]
In my config I had $upload_dir and $img_dir both set to "media/". I moved the .jpg images to images directory and changed $img_dir to "images/" and now the episodes are displayed correctly. I'm not sure whether $upload_dir should be changed too.

**Comment by ryangurn** [comment]
@senarvi & @dskeen are you putting the JPG files into the $upload_dir?

**Comment by senarvi** [comment]
I have now $upload_dir pointing to "media/" and $img_dir pinting to "images/", where I have the JPG files. For me it's working now. Thanks anyway!

**Comment by ryangurn** [comment]
@senarvi Wonderful, im glad that worked! Please let us know if you ever need any assistance, and sorry for the delay in responding!
