### ISSUE TITLE
Fix for a warning after the upload of an episode.

### ISSUE THREAD

**Issue by Marco-Lugo** [PodcastGenerator/PodcastGenerator#310]
After the upload of an episode I have this warning:
Warning: sizeof(): Parameter must be an array or an object that implements Countable in /home/mhd-01/www.****.org/htdocs/podcast/admin/episodes_upload.php on line 35

The problem is here in "episodes_upload.php":
    // If no categories were selected, add the 'uncategorized'
    // category.  Otherwise, ensure that no more than three categories
    // were actually selected.
    if (sizeof($_POST['category']) == 0) {
        $_POST['category'] = array();
        array_push($_POST['category'], 'uncategorized');
    } else if (sizeof($_POST['category']) > 3) {
        $error = _('Too many categories selected (max: 3)');
        goto error;
    }

My solution:
    // If no categories were selected, add the 'uncategorized'
    // category.  Otherwise, ensure that no more than three categories
    // were actually selected.
    // Marco Lugo:
    //I have changed the if below adding a casting to array to eliminate a Warning.
    if (sizeof((array)$_POST['category']) == 0) {
        $_POST['category'] = array();
        array_push($_POST['category'], 'uncategorized');
    } else if (sizeof((array)$_POST['category']) > 3) {
        $error = _('Too many categories selected (max: 3)');
        goto error;
    }

Thanks for your work ;)

**Comment by Marco-Lugo** [comment]
I have opened a pull request about this fix.

**Comment by emilengler** [comment]
Fixed by your PR
