### ISSUE TITLE
Per-episode cover art

### ISSUE THREAD

**Issue by coldacid** [PodcastGenerator/PodcastGenerator#315]
**Description**

Support the ability to upload and use different cover art images for individual episodes, defaulting to the podcast cover art whenever a custom image is not provided for an episode.

**Motivation**

A number of podcasts already use a different cover art image for each episode, such as [No Agenda](https://www.noagendashow.net/) and [Hog Story](http://www.hogstory.net/). I want to be able to do the same with my own podcast.

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by emilengler** [comment]
> Support the ability to upload and use different cover art images for individual episodes, defaulting to the podcast cover art whenever a custom image is not provided for an episode.

This is already possible :-)
Just add a covert art to the mp3 file. There are numerous guides online which show you how.

**Comment by coldacid** [comment]
@emilengler: So then PodcastGenerator will also extract the embedded image from the mp3 for use on the site?

**Comment by emilengler** [comment]
Yes

**Comment by coldacid** [comment]
Thanks.
