### ISSUE TITLE
Field Missing

### ISSUE THREAD

**Issue by jokoblitar** [PodcastGenerator/PodcastGenerator#318]
When save editing podcast ,  error, Field Missing

**System Information**
Podcast Generator Version: 
Webserver:  www.gretha.my.id
PHP Version: 7.1

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

**Actual behavior**
 

**How to reproduce**

**Comment by senarvi** [comment]
I tried editing an episode with the latest 3.1 version. I filled the fields and clicked Save Changes. I got the red error message "Missing fields".

I was going to debug this problem, but now I can't repeat it. Instead, every time I try to save the changes, I get 404 Not Found error from the web server. The URL looks strange: `index.php$url."?name=` and then the episode file name.

**Comment by jokoblitar** [comment]
I re-download today, install a new application. There is already a Search column.
I filled all fields completely, successfully edited and uploaded the new mp3.

**Comment by senarvi** [comment]
I compared my configuration to `setup/createconf.php` and found out what caused the 404 error. `$link` variable in `config.php` has to be changed from `"$url."?name="` to `"?name="` after upgrade.
