### ISSUE TITLE
Setting the Language

### ISSUE THREAD

**Issue by Saladoc** [PodcastGenerator/PodcastGenerator#319]
In the [documentation](https://podcastgenerator.net/documentation/FAQ-localization) it is stated that all available languages are shown automatically on the configuration page. This is not the case. Following the installation instructions with version 3.1, I am unable to switch the language to de_DE.

A quick glance at the admin/pg_config.php source code shows no indication.

How does one change the language?

**Comment by emilengler** [comment]
Edit your config.php file and change the scriptlang variable to de_DE

**Comment by Saladoc** [comment]
Did that. No change sadly. 

Also in the Podcast Details menu the language can be changed but the change will always be discarded and switched back to english. Idk if those issues are related.

**Comment by emilengler** [comment]
Try adding `.UTF_8` to the setting

**Comment by emilengler** [comment]
For de_DE.UTF_8 for example

**Comment by Saladoc** [comment]
Thanks, that did it.
