### ISSUE TITLE
Unable to upload Cover Art

### ISSUE THREAD

**Issue by katelynbolds** [PodcastGenerator/PodcastGenerator#321]
**System Information**
Podcast Generator Version: 3.1
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**
I am unable to upload cover art. Every time I try it errors out, but does not tell me anything that is wrong. I've tried multiple sizes, files sizes, etc and can't figure it out. Please help!

**Comment by emilengler** [comment]
How do you upload it?

**Comment by katelynbolds** [comment]
Under podcast platform settings - Change Cover Art.

**Comment by emilengler** [comment]
The image needs to be quadratic

**Comment by ryangurn** [comment]
@katelynbolds what is erroring? can you provide more information or a screenshot of the error so that we can provide more specific assistance with this?

**Comment by Zamino** [comment]
same case for me. Can't upload a quadratic cover picture. No error occurs. The website just refreshes. The picture is in jpg with 982x982 pixels and a file size of 365 kb.

**Comment by emilengler** [comment]
Hmmmm, can you just replace itunes_image.jpg in images/ with your desired picture?

**Comment by Zamino** [comment]
It looks like this is an Safari-Problem. When I open Podcast Generator on Crome I can see my uploaded cover.

**Comment by Go-rom** [comment]
Which Safari version please ?

**Comment by emilengler** [comment]
Can you also post the cover you try to here?

**Comment by nicolasguzca** [comment]
Getting the same behavior, can't change the image on `admin/store_cover.php` and no error shows, had to change it via FTP.
