### ISSUE TITLE
Theme (CSS) not loading

### ISSUE THREAD

**Issue by Archiware** [PodcastGenerator/PodcastGenerator#324]
Hello there!

I've installed PG on a self hosted server running Ubuntu 20.04. I'm using PHP 7.4.9 and as a web server I've got Caddy 2.1.1 running.

The problem is visible in my attached screenshots. In the admin area, everything looks fine so far. But on the actual index.php / homepage, the CSS is not being loaded. I am honestly a little confused as of why. I gotta admit at this point, that I'm not too familiar with PHP and am not too experienced with such hosting, apart from very basic tasks I had to do in my apprenticeship back in the days. I usually work with Java (and nowadays also Dart / Flutter), so this might be a very stupid beginner's mistake on my side, maybe just a file permissions problem or something else.

Here's everything about my setup accumulated:

- Self-hosted
- Ubuntu 20.04
- Caddy 2.1.1
- PHP 7.4.9
- PodcastGenerator 3.1

The following have already been installed:
`sudo apt install php7.4 php-fpm php-cgi php-xml gettext`

The following is the relevant content from my `Caddyfile`:
```
podcast.example.de {

        root * /var/www/podcast-generator

        file_server {
                index index.php
        }

        log { ... }

        php_fastcgi unix//run/php/php7.4-fpm.sock

        encode gzip zstd
}
```

Commands I've taken from a installation assistance here in the GitHub issues section:
`sudo chown -R caddy:caddy podcast-generator/`
`sudo chown -R caddy:caddy podcast-generator/media/`
`sudo chown -R caddy:caddy podcast-generator/images/`
`sudo chmod 775 podcast-generator/`
`sudo chmod 775 podcast-generator/media/`
`sudo chmod 775 podcast-generator/images/`
`sudo chmod 775 podcast-generator/themes/`
`sudo chown -R caddy:caddy podcast-generator/config.php`
`sudo chmod 775 podcast-generator/config.php`

I've also tried setting all the folders / files to `chmod -R 777` out of desperation, but that did not change anything either.

Base folder structure:
```
user@example-01:/var/www/podcast-generator$ ls
admin     buttons.xml     categories.xml  config.php  external.php  feed.php             images     media        themes
auth.php  categories.php  components      core        favicon.ico   freebox-content.txt  index.php  pg-cron.php
```

Any help or ideas would be greatly appreciated!

![Screenshot 2020-09-08 120630](https://user-images.githubusercontent.com/61418092/92464767-e9b89800-f1cd-11ea-8c04-9ea5d278c3c6.png)
![Screenshot 2020-09-08 122215](https://user-images.githubusercontent.com/61418092/92464788-f3da9680-f1cd-11ea-89c0-406835d2befe.png)

**Comment by Archiware** [comment]
Please don't look at me. I'm a shame to the guild of software developers. It _was_ a file permission issue and I should have seen it from a mile away.

I'm crawling back into my cave of shame now.

**Comment by emilengler** [comment]
> Please don't look at me. I'm a shame to the guild of software developers. It _was_ a file permission issue and I should have seen it from a mile away.
> 
> 
> 
> I'm crawling back into my cave of shame now.

No problem! Sometimes you don't see the forest because there are too many trees ;)
