### ISSUE TITLE
'64kbps' displayed as '640kbps'

### ISSUE THREAD

**Issue by scateu** [PodcastGenerator/PodcastGenerator#325]
**System Information**
Podcast Generator Version: 3.1
Webserver: nginx
PHP Version: 7.3

**Expected behavior**
`Filetype: MP3 - Size: 32 MB - Duration: 1:05:53m (64 kbps 44100 Hz)`

**Actual behavior**
`Filetype: MP3 - Size: 32 MB - Duration: 1:05:53m (640 kbps 44100 Hz)`
**How to reproduce**
It's a mp3 file encoded by forecast.app. When encoded in 192kbps, it shows as expected.

Thank you for making this fantastic program.

**Comment by emilengler** [comment]
There's nothing we can do against this unfortunately. We don't parse such files manually. It's a getID3 bug I suppose

**Comment by scateu** [comment]
Thank you for letting me know. And thanks again for this great program!

**Comment by murty2** [comment]
Edit file: core/episodes.php

1. Function saveEpisode: Replace portion
    $writer->writeElement('bitrate', substr(strval($bitrate), 0, 3));
By
    $writer->writeElement('bitrate', strval((int) ($bitrate/1000)));

2. Function indexEpisodes: Replace portion
                <bitrate>' . substr(strval($bitrate), 0, 3) . '</bitrate>
By
                <bitrate>' . intval($bitrate/1000) . '</bitrate>

For already uploaded podcasts, edit media/*.xml files to manually fix value in <bitrate></bitrate>
