### ISSUE TITLE
Admin Login

### ISSUE THREAD

**Issue by DavidmSRBC** [PodcastGenerator/PodcastGenerator#326]
I have tried every step that I have found to try to change the admin password to be able to log in but nothing works.

is there something I am missing?

I am trying to upgrade from version 2.6 but I can not even log into that version.

Any help would be much appreciated.

Thanks David

**Comment by emilengler** [comment]
It's not possible to upgrade directly. You will need to go to 2.7 first and then each version

**Comment by DavidmSRBC** [comment]
I read that I have to do it in steps.  However I can not even login the version 2.6.  I need help with this.  I have followed all the instructions but nothing works

**Comment by emilengler** [comment]
Hey if you are still there. I think it's best for you to backup your media directory and do a fresh install.
