### ISSUE TITLE
RSS Feed Public Email

### ISSUE THREAD

**Issue by travisterwilliger** [PodcastGenerator/PodcastGenerator#327]
**EDIT** : It looks like Spotify needs to be declared. View documentation here https://podcasters.spotify.com/terms/Spotify_Podcast_Delivery_Specification_v1.6.pdf

In order to link Podcast Generator's RSS Feed up with Spotify, we need a way to publicly display an email address.

Itunes owner information populates in the XML, but I am assuming Spotify needs something different.

- [ ] Enable Podcast Generator to be compatible with Spotify.

Here is the error message from Spotify for reference (ignore the Episodes missing notation)

Your podcast RSS feed is missing some things:
Episodes
**Email address**

And here is my XML for reference:
You can view the raw XML here: https://naptimetalks.com/podcasts/rss/feed.xml

This XML file does not appear to have any style information associated with it. The document tree is shown below.

<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:googleplay="http://www.google.com/schemas/play-podcasts/1.0" xmlns:atom="http://www.w3.org/2005/Atom" xml:lang="en" version="2.0">
<channel>
<title>Nap Time</title>
<link>https://naptimetalks.com/podcasts/rss/</link>
<atom:link href="https://naptimetalks.com/podcasts/rss/feed.xml" rel="self" type="application/rss+xml"/>
<description>Episodes last as long as the name!</description>
<generator>Podcast Generator 3.1 - http://www.podcastgenerator.net</generator>
<lastBuildDate>Sat, 12 Sep 2020 21:01:54 -0500</lastBuildDate>
<language>en</language>
<copyright>All rights reserved</copyright>
<itunes:image href="https://naptimetalks.com/podcasts/rss/images/itunes_image.jpg"/>
<image>
<url>https://naptimetalks.com/podcasts/rss/images/itunes_image.jpg</url>
<title>Nap Time</title>
<link>https://naptimetalks.com/podcasts/rss/</link>
</image>
<itunes:summary>Episodes last as long as the name!</itunes:summary>
<itunes:subtitle>A tired couple talks about their world of raising kids whenever the kids fall asleep.</itunes:subtitle>
<itunes:author>telah32</itunes:author>
<itunes:owner>
<itunes:name>telah32</itunes:name>
<itunes:email>terwilligertm@gmail.com</itunes:email>
</itunes:owner>
<itunes:explicit>yes</itunes:explicit>
<itunes:category text="Comedy"/>
<itunes:category text="Kids & Family:Parenting"/>
<itunes:category text="Education:Self-Improvement"/>
</channel>
</rss>

**Comment by emilengler** [comment]
I'll have a look at it

**Comment by travisterwilliger** [comment]
> I'll have a look at it

I'd be inclined to take a look as well. Browsing the Spotify docs, it looks quite simple to do. Perhaps we can even provide compatibility with other large Podcast based websites (TuneIn, Google Podcasts, Stitcher, etc).

I believe all that would need to happen is include inputs for each platform you want to link up with (email and username). Save them and append the xml to the feed.

**Comment by emilengler** [comment]
Google Podcasts is already supported but I am open to the alternatives :-)

**Comment by emilengler** [comment]
The feed already has an email included. I don't know whats wrong now?
