### ISSUE TITLE
Connection is Reset During Audio Upload

### ISSUE THREAD

**Issue by Amvalain** [PodcastGenerator/PodcastGenerator#329]
"This site can’t be reached

The connection was reset.

Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_RESET"

Happened multiple times with multiple file types. Just trying to figure out if it just me and what the fix could be.

**Comment by emilengler** [comment]
Can you try it with a smaller file?

**Comment by Amvalain** [comment]
> Can you try it with a smaller file?

Sorry about the late reply. I will try with a smaller file size this evening. Is there a file size limit?

**Comment by emilengler** [comment]
> Sorry about the late reply. I will try with a smaller file size this evening. Is there a file size limit?

No, at least not by Podcast Generator! However I think the problem comes from your web server. If you try a smaller file it will very likely mean your web server is the trouble maker

**Comment by Amvalain** [comment]
> > Sorry about the late reply. I will try with a smaller file size this evening. Is there a file size limit?
> 
> No, at least not by Podcast Generator! However I think the problem comes from your web server. If you try a smaller file it will very likely mean your web server is the trouble maker

You were correct, sir. Sorry to bother you. Any idea about where to change such a setting?

**Comment by emilengler** [comment]
Have you an error log or something similar?

**Comment by flattery103** [comment]
Look in your server's php.ini files for settings like this:

; Maximum allowed size for uploaded files.
upload_max_filesize = 40M

; Must be greater than or equal to upload_max_filesize
post_max_size = 40M
