### ISSUE TITLE
Where is the synology Podcast Generator package

### ISSUE THREAD

**Issue by garyee** [PodcastGenerator/PodcastGenerator#332]
Hi,

saw the package on my diskstation some time ago and thought that I would definetly try it. But it is gone now...
And has been since two month ([reddit](https://www.reddit.com/r/synology/comments/hs8cih/whats_happened_to_podcast_generator/))

**Comment by emilengler** [comment]
Hello @garyee 
Unfortunately I have no idea!
The package is entirely maintained by Synology, not by me. I have no influence on this.
Therefore you have two options:

1) Contact Synology and ask them nicely
2) Install Podcast Generator "by hand" on your Synology

**Comment by RicardoVelaC** [comment]
> Therefore you have two options:

Or a third option: Consider the changes for create a Docker version of PG, with docker you get a standard package with multi-system support, Synology, QNAP, Windows, Linux, Raspberry Pi, with a clean and easy install.

CC @vonProteus #289

**Comment by garyee** [comment]
@emilengler hi, thanks for the quick reply.
I did the first one. For the second one: sadly my diskstation does not support docker. Is there a install guide for this?

**Comment by garyee** [comment]
Okay I did get an answer it seems that the support for the package has been discontinued:
https://www.synology.com/en-global/support/download/DS211j#eols

I think they do not want support packages that they haven't made, as there is docker support now ... on newer models.
They also told me that I could install it manually, so I will try and do that.

**Comment by emilengler** [comment]
> Okay I did get an answer it seems that the support for the package has been discontinued:
> 
> https://www.synology.com/en-global/support/download/DS211j#eols
> 
> 
> 
> I think they do not want support packages that they haven't made, as there is docker support now ... on newer models.
> 
> They also told me that I could install it manually, so I will try and do that.

Sad that they have removed it though. Thanks for your research anyway :-)

**Comment by vonProteus** [comment]
@garyee if you want my docker container it is available at
https://hub.docker.com/r/vonproteus/podcast-generator
and is runnable on linux/386 linux/amd64 linux/arm/v7 linux/arm64
i supposed Synology use linux/arm/v7 so you shut be fine

**Comment by garyee** [comment]
@vonProteus your docker-image works like a charm. Could you maybe open a PR? This would allow for an official docker image, which is always up to date with the generator version, this would be great!

**Comment by coldacid** [comment]
Changes to support Docker (as well as sharing one install of PG among multiple podcasts) will require multiple breaking changes, but I anticipate that PG 4.0 will allow us to provide this support out of box. That said, I do not plan to support PG packages created by third parties for their platforms (e.g. Synology, Softaculous), only those released here on GitHub.
