### ISSUE TITLE
m4a upload bug

### ISSUE THREAD

**Issue by VikkiBaptie** [PodcastGenerator/PodcastGenerator#336]
**System Information**
Podcast Generator Version: 3.1
Webserver: linux
PHP Version: 7.4

**Podcast Generator Config**

```
Couldn't get your tool to work for some reason.
```  

**Expected behavior**

Unsupported mime type detected for file with extension "m4a"

**Actual behavior**
 
To upload an m4a file

It said in your FAQ to:  You can add as many new file formats as you want by manually editing core/supported_media.php and appending to the list the new extension, along with its corresponding mime type.

But the file supported_media.php is not there? I could find .xml? which included m4a so I'm not sure why it's not working?

	<mediaFile>
		<extension>m4a</extension>
		<mimetype>audio/x-m4a</mimetype>
	</mediaFile>

**How to reproduce**

Uploaded an m4a file.

**Comment by VikkiBaptie** [comment]
Sorry guys I fixed this... 

Changed the XML file to read:

	<mediaFile>
		<extension>m4a</extension>
		<mimetype>audio/mp4</mimetype>
	</mediaFile>

**Comment by eglinski** [comment]
Oh thanks for this. I was so excited to try PodcastGenerator but deleted it after the error displayed when I tried using an M4A.

**Comment by csss1234** [comment]
I'm new here, just installed 3.1.1, and the supported media XML was still

```
<mediaFile>
	<extension>m4a</extension>
	<mimetype>audio/x-m4a</mimetype>
</mediaFile>
```
