### ISSUE TITLE
Login disabled for security reasons

### ISSUE THREAD

**Issue by Loopzorbital** [PodcastGenerator/PodcastGenerator#337]
I had an issue with my current version of PodcastGenerator, so i just uploaded new version to a fresh directory.

Set it up with no issues. Then i copied the MEDIA and IMAGES folder over from the original installation to the new installation
Now when i go to the NEW installation, it correctly loads the page and i can see my podcasts but if i click on ADMIN, it tells me

"Login disabled for security reasons"

Can you advise what i should do?

My plan was to rename the old installation to .OLD and then rename the NEW installation to the original installation name. That way it doesn't (in theory) break the existing APPLE connection. This was my idea anyway 👍

**Comment by emilengler** [comment]
Delete the reset.php file

**Comment by Go-rom** [comment]
Hello @Loopzorbital 
if the previous answer helped you, could you please close this ticket ?

**Comment by emilengler** [comment]
I will close this now anyways. If there are still problems please comment so we can re-open this issue.
