### ISSUE TITLE
Need to upgrade (Current v1.3)

### ISSUE THREAD

**Issue by pudealee** [PodcastGenerator/PodcastGenerator#339]
**System Information**
Podcast Generator Version: 1.3
Webserver: cpsrvd 11.86.0.25 
PHP Version: 7.3.6

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**
GoDaddy did some sort of upgrade this weekend, and I can no longer access my site. I am working with them on that. But, I suppose I need to upgrade to the latest version of PG. Since I'm going from 1.x to 3.x, should I do a complete new install? I obviously want to save all of my media, etc. So what files should I not upload from the install?

**Comment by emilengler** [comment]
Doing a new install is probably the best way. 1.3 is just too old and the upgrader would fail

**Comment by pudealee** [comment]
Thanks. I figured as much. So in doing a new install, what procedure should I undertake to preserve my content?

**Comment by emilengler** [comment]
> Thanks. I figured as much. So in doing a new install, what procedure should I undertake to preserve my content?

I'm not into 1.3 but I think the most important thing is to backup your media/ and images/ folder. After you re-installed PodcastGenerator and changed the settings to your favor replace the media/ and images/ folders and you should be ready to go

**Comment by pudealee** [comment]
I finally upgraded to 3.1 (new install from 1.3). Everything went smoothly! I'm looking forward to some new themes at some point in the future. Thanks for your assistance.

**Comment by emilengler** [comment]
No problem! Thanks for using this software :-)
