### ISSUE TITLE
3.1 compatible themes

### ISSUE THREAD

**Issue by berkeleybernie** [PodcastGenerator/PodcastGenerator#343]
Hi, just a musician here with a little geek know-how. Just installed PG at my web host to check it out. Are there any themes for 3.1 yet besides the default? I haven't been able to locate any.

Thanks!

**Comment by emilengler** [comment]
No, there are no other themes beside the default one. However @NeaMitika created was working/is working on a light or dark theme if I remember correctly

**Comment by NeaMitika** [comment]
You know what, i am gonna start working on it again :) Here in Italy we are in lockdown again for atleast 1 month, this is the perfect moment to do it :)

**Comment by Go-rom** [comment]
Hello @NeaMitika 

Hope your lockdown is over now. Did you have the time to make one or several themes ?

Thank you :)

**Comment by NeaMitika** [comment]
> Hello @NeaMitika
> 
> Hope your lockdown is over now. Did you have the time to make one or several themes ?
> 
> Thank you :)

Here is the link to the PR, #353 but i dont know if it was merged i didnt followed it anymore :) , but the files are there

**Comment by Go-rom** [comment]
oh didn't see your PR, sorry !

It hasn't been merged yet,  i think that @emilengler is busy for now.

Anyway thank you for this new theme 👍
