### ISSUE TITLE
Scripts is not writeable

### ISSUE THREAD

**Issue by BrandenWitte** [PodcastGenerator/PodcastGenerator#344]
During setup it came up with Media, Images, and Scripts are not writeable. I was able to change permissions for Media and Images, but could not find Scripts. I've tried searching, but had no luck.

Any known solutions? Scripts is not writeable. I was able to fix the others using chmod.

**Comment by emilengler** [comment]
Scripts is the root folder of your Podcast Generator installation. (The folder where media and scripts reside in)

**Comment by BrandenWitte** [comment]
That did it! Thank you so much. I had searched and found nothing, and I'm newer to this so appreciate the help.
