### ISSUE TITLE
Navbar displayed on all episode pages (instead of only on index pages)

### ISSUE THREAD

**Issue by Radiowiec** [PodcastGenerator/PodcastGenerator#345]
**System Information**
Podcast Generator Version:  3.1
Webserver: Apache
PHP Version: 7.4

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

No paging control (NAV tag) on single episode pages.

**Actual behavior**
 
All single episode pages display a navbar.

**How to reproduce**

Display any single episode page - a navbar is displayed at the bottom.

**Comment by emilengler** [comment]
Can you provide a screenshot?

**Comment by Radiowiec** [comment]
Of course. Look at the podcast at
https://www.download.blindiphone.pl/PodcastGenerator/index.php

![singleepisode](https://user-images.githubusercontent.com/46573256/98736776-92899c00-23a5-11eb-876d-37e172aed46a.png)

- there's a NAV tag at the bottom there, which is correct. Look at a single episode page, e.g.

https://www.download.blindiphone.pl/PodcastGenerator/index.php?name=2020-08-06-prezentacja_launchera_square_home.mp3

- there's also the NAV tag there (where it shouldn't).

![indexpage](https://user-images.githubusercontent.com/46573256/98736779-93223280-23a5-11eb-9dbb-02c4d31092e9.png)

I would suggest to solve it by enclosing proper section of the PodcastGenerator-3.1\PodcastGenerator\themes\default\index.php file with the following condition:
if (!isset($_GET[$link])) {
...
}

**Comment by emilengler** [comment]
Thanks for the report! I will fix it in the next release!
