### ISSUE TITLE
The latest release doesnt have the latest modifications

### ISSUE THREAD

**Issue by NeaMitika** [PodcastGenerator/PodcastGenerator#346]
**Description**
I was working on the black version for the default theme, and i have downloaded the latest release and i have noticed that is different from the actual repo... 
For example the installation steps are not with the new "design" (by design i mean the bootstrap classes added to the divs) and the same with the listing of the podcast.

Could we make a pre-release or a new release adding the latest modifications?

**Comment by emilengler** [comment]
Hey thanks for working on it! :)
If you work on Podcast Generator, please use the development version/master branch. Your design patches (f9ea5235527d2af2e910fc18a6bac9acab804110, 34bfb74c5ac469c8077079077a687e2eb051f70d, d92a7b8b622738b2c43abd5a27108fd0e43cf3fe) have been merged slightly after 3.1 came out therefore they are not in the new version.

> Could we make a pre-release or a new release adding the latest modifications?

The next release is scheduled on 2020-12-13 so as long as there are no critical bugs I don't think it's worth it

**Comment by NeaMitika** [comment]
Roger that! 

So many things to discover about GitHub! 

I will try to make it by 2020-12-13 :), i mean come on 1 FULL month, I can do it! (encouraging my self)
