### ISSUE TITLE
Your access to TinyMCE will expire on 20 November 2020. 

### ISSUE THREAD

**Issue by ortv15wjmj** [PodcastGenerator/PodcastGenerator#347]
**System Information**
Podcast Generator Version: 2.7
Webserver: cPanel
PHP Version: 7.3.6

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**
Receive the following message when uploading files.
Your access to TinyMCE will expire on 20 November 2020. Please either contact your administrator or upgrade your account using the instructions available at https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/.

**Comment by emilengler** [comment]
This has nothing to do with PG

**Comment by cosmomans** [comment]
I'm getting the same issue:
Your access to TinyMCE will expire on 30 November 2020. Please either contact your administrator or upgrade your account using the instructions available at https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/.

**Comment by cosmomans** [comment]
By the way, this happens also on the demo account! 

Check it out: 
https://podcastgenerator.net/demoV2/

**Comment by emilengler** [comment]
> This error also occurs on the demo account:
https://podcastgenerator.net/demoV2/

The demo is horrendously outdated unfortunately. Keep in mind that Podcast Generator 3.0 doesn't use TinyMCE anymore. Therefore I would suggest to upgrade.

> I tried using podcastgenerator-3.1 but there is a missing functionality. We cannot get separate RSS feeds by category, but with 2.7 we could do. HEEEELP!

Will add this in 3.2 :-)

**Comment by cosmomans** [comment]
Thank you @emilengler!

**Comment by ortv15wjmj** [comment]
We plan on upgrading from 2.7 but haven't had the time as this is a very busy time of year for our organization.  Thank you @emilengler for reopening and @cosmomans for pointing out the demo error.

**Comment by AmigaMaster** [comment]
See https://github.com/PodcastGenerator/PodcastGenerator/issues/354#issuecomment-733976206 for a possible workaround but you will loose WYSIWYG editing features, so you have to use native HTML code instead.

**Comment by emilengler** [comment]
Turns out everything still works fine somehow
