### ISSUE TITLE
Apple Podcast loading icon gets to 100% but never disappears

### ISSUE THREAD

**Issue by ClimbingArb** [PodcastGenerator/PodcastGenerator#348]
Hi,

I use Podcast Generator 2.7 to upload my podcasts. In recent months the podcast when uploaded to Apple podcasts, will show it downloading on the phone but when it is complete the icon remains there. 
Has anyone else encountered this? and is it an issue in the RSS feed code?

Thanks,

**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**

**Comment by Go-rom** [comment]
Hello, PG 2.7 is not supported anymore.

You should run a full backup of your podcast directory then do a an upgrade to PG 3.0.1 then an upgrade to PG 3.1
