### ISSUE TITLE
After create an episode which will publish in the future time, it does not show in the list of "edit/delete episode"

### ISSUE THREAD

**Issue by hocdevitionorg** [PodcastGenerator/PodcastGenerator#349]
**System Information**
Podcast Generator Version: v3.*
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

After create an episode which will publish in the future time, it does not show in the list of "edit/delete episode"

**Actual behavior**
 
The episode should appear in the list of "edit/delete episode" for edit and delete.
But two files can be seen in podcast/media/ for that episode.

**How to reproduce**

create an episode by using "upload episode"

**Comment by emilengler** [comment]
This is not, it is a feature! If you schedule a future episode, why should people still see it on the page?

**Comment by hocdevitionorg** [comment]
We had old site using old PodcastGenerator which has been always showed the all created episodes, but this time after installed on a new site, not all created episodes showing up. 

For example, now is 1pm, create an episode to publish at 8am tomorrow morning, this used to show in the list and let you to modify or delete before it is to publish before 8am tomorrow morning. Right now, it does not show up any more. If need to modify or delete we have to go through IPS file manager to delete files in podcast/media and recreate new one. This is extremely inconvenient. Why to hide these episodes to admin? This is a severe regression.

**Comment by emilengler** [comment]
> For example, now is 1pm, create an episode to publish at 8am tomorrow morning, this used to show in the list and let you to modify or delete before it is to publish before 8am tomorrow morning. Right now, it does not show up any more after click "Edit/Delete Episodes". If need to modify or delete we have to go through hostsite file manager to delete files in podcast/media and recreate new one. This is extremely inconvenient. I understood to hide for people to view episode, but why to hide these episodes to admin in "Edit/Delete Episodes"? This is a severe regression.

Hmmm, curious. Was it only possible if a user was signed in? It's easy to re-implement it though

**Comment by hocdevitionorg** [comment]
@emilengler this was done all after signed-in. This is not about "View Episodes" page, it is about "Edit/Delete Episodes" page which only Admin using. Hope this fix asap. Thanks!

**Comment by hocdevitionorg** [comment]
@StoryHack @emilengler 
regarding the fix with "Replaces 'Edit / Delete' link in admin navbar with a 'View All Episodes' link ..."
We still want to restore the "Edit/Delete" function, rather remove this feature. This was a regression from previous release. 
Thanks!

**Comment by StoryHack** [comment]
The "Edit/Delete" link was just a link to the front page of the installation, where you could only see a few posts. You can still go to that page. No functionality was lost. You still edit/delete the episodes in the same way. This change just makes it easier to find the episode you wish to edit/delete.

**Comment by hocdevitionorg** [comment]
@StoryHack that sounds perfect! We are looking forward to getting the fix/release asap. Thanks!
