### ISSUE TITLE
Option for RSS feed split per category / Multiple podcast feeds

### ISSUE THREAD

**Issue by pblommendaal** [PodcastGenerator/PodcastGenerator#350]
**Description**
It would be nice if multiple podcast feeds could be generated. There are multiple ways to implement it I guess, for instance a filter on the category that creates a separate feed, with the downside that the podcast details are all the same for each category. Or support multiple podcast details that will generate a separate feed for each podcast, this would be the better option.

**Motivation**
The only way to do this right now is to create multiple installations into different folders I guess? This creates a maintenance overhead in terms of administration, upgrade etc. 

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by emilengler** [comment]
> The only way to do this right now is to create multiple installations into different folders I guess? This creates a maintenance overhead in terms of administration, upgrade etc.

Unfortunately such a change would be very hard as it would mean a completely new architecture.

**Comment by cosmomans** [comment]
@emilengler this used to be possible on podcastgenerator-2.7...

Any way we could bring this back?

**Comment by emilengler** [comment]
Yes, see your other issue

**Comment by cosmomans** [comment]
Thanks @emilengler!

**Comment by andyhuai** [comment]
> @emilengler this used to be possible on podcastgenerator-2.7...
> 
> Any way we could bring this back?

How to do this in 2.7 ? 
@cosmomans

**Comment by emilengler** [comment]
Yes

**Comment by andyhuai** [comment]
@emilengler 
I have found that,
But, can I use sub-folder in `media` to seperate categories ? so that I can easy to manage podcast file

**Comment by emilengler** [comment]
> @emilengler 
> 
> I have found that,
> 
> But, can I use sub-folder in `media` to seperate categories ? so that I can easy to manage podcast file

I could implement it so it will traverese within sub folders inside it yes. But please avoid duplicate file names though

**Comment by andyhuai** [comment]
my

> > @emilengler
> > I have found that,
> > But, can I use sub-folder in `media` to seperate categories ? so that I can easy to manage podcast file
> 
> I could implement it so it will traverese within sub folders inside it yes. But please avoid duplicate file names though

yeah, will see in 3.2? great!!!
maybe, each category have on sub folder, then autoindex file, add file to category ?
I think, this will be very NICE~
