### ISSUE TITLE
TinyMCE

### ISSUE THREAD

**Issue by Pp896** [PodcastGenerator/PodcastGenerator#352]
Problem with TinyMCE.
Your access to TinyMCE will expire on 30 November 2020. Please either contact your administrator or upgrade your account using the instructions available at https://www.tiny.cloud/blog/how-to-migrate-from-tinymce-4-to-tinymce-5/.

**Comment by frcoulter** [comment]
I'm getting the same warning.  Any advice what to do?

**Comment by Pp896** [comment]
In the file /core/admin/loadjavascripts.php change URL of tiny (//tinymce.cachefly.net/4.1/tinymce.min.js) with (https://cdn.tiny.cloud/1/no-api-key/tinymce/5.5.1-99/tinymce.min.js)
when you log in to your admin, you are asked to create an account on Tiny. By creating this account you get an API key. In the URL you replace ´no-api-key´ by this key. And it's good.

**Comment by emilengler** [comment]
FYI: We will see what happens after 30th of November this year. If it makes any serious problems, I will release 2.7.1 which will be 2.7 but with the TinyMCE editor patched out or replaced with something else.

**Comment by emilengler** [comment]
Will close this now as we already have many issues with this topic.

**Comment by 0d0a** [comment]
Got the same message ... will wait for patch
