### ISSUE TITLE
Downgrading back to 2.7- so many issues in 3.1

### ISSUE THREAD

**Issue by schematicdnb** [PodcastGenerator/PodcastGenerator#354]
I updated from 2.7 to 3.01 to 3.1 after getting the TinyMCE expiration message but unfortunately I'm going to have to downgrade again because v3 is essentially unusable to me at this stage.

- Functions such as upload/ftp index/rss regeneration take enormously longer than they did in 2.7, in some cases several minutes
- Can only view first page of episodes (i.e. however many $max_recent in config is set to)
- All album/cover art from previously uploaded episodes is missing. The images exist on the server but the xml generates <itunes:image href="1"/> for all previous episodes
- Long description is not present in the generated XML (no <itunes:summary> tag generated per episode). Also a minor annoyance, the long description input box is very narrow and can only be enlarged vertically but not horizontally.

I can only hope by the time TinyMCE finally expires on PG 2.7 these issues have been addressed in PG 3

**Comment by Strider3000** [comment]
Will TinyMCE expiry cause PG 2.7 to stop working?

**Comment by emilengler** [comment]
@Strider3000 I have no idea! But if there is really such a demand on PG 2.7 I could try to release 2.7.1 with TinyMCE patched out.

**Comment by schematicdnb** [comment]
I'm guessing we'll lose the ability to input text into the title/description fields. I was going to see if I could edit a few bits to update TinyMCE 4 to 5 which would hopefully solve the problem, but a 2.7.1 hotfix for that would be greatly appreciated until all the kinks of PG 3 are worked out!

**Comment by emilengler** [comment]
Ok, I will create a 2.7.1 version for the case the expired TinyMCE does any problems! Please tell me how it works after 30th of November

**Comment by AmigaMaster** [comment]
In case there are problems on or after 30th November, edit line  58 in your /core/admin/loadjavascripts.php file.
Make sure, you create a backup of the file before editing or you can use the following link to get the origin v2.7 file: https://github.com/PodcastGenerator/PodcastGenerator/blob/b17c2ace9bae42d0eab9371b7ed93cee09f35f21/core/admin/loadjavascripts.php

Change the TinyMCE URL to some URL which does not exist, for example

```js
<script src="//tinymce.cachefly.xyz/4.1/tinymce.min.js"></script>
```

PG will then display a simple text input field where you can enter your HTML text.

Note that this may happen automatically when the old TinyMCE is shut down but it depends on how it is shut down.

**Comment by wilhen01** [comment]
I've also found loads of issues with 3.1. About to downgrade back to 2.7. I don't really use the WYSIWIG HTML features so losing TinyMCE is not a huge deal compared to the bugs I'm seeing in 3.1 😞

**Comment by madsha** [comment]
I am seeing the same problems, and I'll apply a 2.7.1 patch as soon as possible. Thanks @Emil Engler!

**Comment by emilengler** [comment]
How is 2.7 now once TinyMCE is dead?

**Comment by madsha** [comment]
Hi Emil,

Thanks for asking! Actually, it works just like it did in November, no change at all!

It still shows the message about TinyMCE, but everything works, once you click OK.

Best regards,
Mads

Fra: Emil Engler <notifications@github.com>
Sendt: 1. december 2020 07:24
Til: PodcastGenerator/PodcastGenerator <PodcastGenerator@noreply.github.com>
Cc: Mads Hansen <madsha@kk.dk>; Comment <comment@noreply.github.com>
Emne: Re: [PodcastGenerator/PodcastGenerator] Downgrading back to 2.7- so many issues in 3.1 (#354)


How is 2.7 now once TinyMCE is dead?

**Comment by emilengler** [comment]
Thanks, I think there is no need for 2.7.1 then!

**Comment by madsha** [comment]
Hi Emil,

I agree, but I should note, that I’m running PG on PHP 5.2.17 (I have to, because of some legacy software)
Perhaps people with newer PHP versions see something different than I do?

/Mads

Fra: Emil Engler <notifications@github.com>
Sendt: 1. december 2020 11:37
Til: PodcastGenerator/PodcastGenerator <PodcastGenerator@noreply.github.com>
Cc: Mads Hansen <madsha@kk.dk>; Comment <comment@noreply.github.com>
Emne: Re: [PodcastGenerator/PodcastGenerator] Downgrading back to 2.7- so many issues in 3.1 (#354)


Thanks, I think there is no need for 2.7.1 then!

**Comment by schematicdnb** [comment]
I can confirm the input fields do appear to still be working as normal for me after clicking through the notification.

**Comment by chrisdoth2** [comment]
Are there any security implications of moving back to 2.7?

We finally upgraded to 3.1 today and while the update all went okay(thank you) we now see there are some issues. 

All the old individual podcasts images are not displaying on the main page and are also broken in the feed, the front page only lists the latest six shows along with some other issues in the admin. It seems 3.1 is not as functional as the old version currently, but I worry about how old 2.7 is?
