### ISSUE TITLE
Image uploads in media folder

### ISSUE THREAD

**Issue by wilhen01** [PodcastGenerator/PodcastGenerator#358]
I've noticed two bugs since upgrading from 2.7 to 3.1 around image uploads.

When changing the iTunes image (Admin / Podcast Platform Settings / Change Cover Art) it ends up in the media folder, not the images folder. Doing an FTP index then causes an episode to appear attached to the image file. 

When uploading episodes with cover art attached, FTP indexing then creates the image in the media folder too, so you get two episode entries - one for the actual audio, and one for the image. Removing the entry for the image also removes the entry in the feed for the audio (but doesn't remove the audio file from the media directory). 

As a workaround for now I'm just not using custom cover art, and I'm stripping cover art from the individual episodes, but this feels like a significant regression compared to functionality in 2.7 😞

**Comment by Go-rom** [comment]
Hello,

i tried to reproduce the upload bug but i can't.
When i upload a new covert art, it ends up in images folder as itunes_image.jpg

**Comment by wilhen01** [comment]
Strange. I've since downgraded to 2.7 so I'm afraid I can't try and reproduce it again.

**Comment by Go-rom** [comment]
Ok.
I can tell you that PG 3.1 does what it says about cover upload, i'm working on a PR that aims to enhance this feature (https://github.com/PodcastGenerator/PodcastGenerator/pull/396)

This is the line where it all happens
`(!move_uploaded_file($_FILES['file']['tmp_name'], $config['absoluteurl'] . $config['img_dir'] . 'itunes_image.jpg'))`

The upload folder is given by this variable : img_dir that you can find in your config.php file like this : 

`$img_dir = "images/"; // (Trailing slash required). Set chmod 755`

So if anything unattended happens, you should look at this line.

For now, i think you should close this issue.

**Comment by wilhen01** [comment]
Happy to close - I'll reopen if I'm still experiencing issues if and when I upgrade to 3.* again
