### ISSUE TITLE
Several issues after upgrade to 3.1

### ISSUE THREAD

**Issue by frcoulter** [PodcastGenerator/PodcastGenerator#359]
Like many others I just upgraded from 2.7 to 3.1 because of the TinyMCE issue.
Thankfully from other posts I knew I had to set:
$max_recent = "All"; in the config.php file to see all my episodes, and
$strictfilenamepolicy = "no"; to use the FTP auto-index because I use hyphens in my filenames.

Here are the issues I'm having using 3.1:
1. Help/Feature Request: the categories used to be alphabetical, now they are ordered by creation date.
Is there a variable so that this sort order can be changed?  If not, can you please add?

2. Help/Feature Request: what is the purpose of the "More" button that appears on every episode? All it does is take one to the permalink URL exactly the same as clicking on the title.
Could there be a variable to hide the "More" button?  

2b. I could understand if 'More' showed the long description, but it doesn't, which also raises the question of what's the purpose of the long description if I can't see it anywhere (for users who access my page but don't subscribe)?
Could there be an option for the long description to be shown on the individual episode (permalink URL) page?

3. Bug: every time I edit an episode and hit 'Save Changes' - I am redirected to a non-working URL:
http://frcoulter.com/podcast/index.php$url.%22?name=2020-11-29-Sunday.mp3
[the actual URL is http://frcoulter.com/podcast/index.php?name=2020-11-29-Sunday.mp3]

P.S. I have not changed the config line:
$link = "$url."?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

Thanks for the support.

**Comment by Radiowiec** [comment]
When it comes to description fields, I'd suggest applying a small correction (I did it to my podcast): in the PodcastGenerator/themes/default/singleepisode.php file change the line
echo '  <small>' . $correctepisode["episode"]["shortdescPG"] . '</small><br>'; 
to
echo '  <small>' . $correctepisode["episode"]["longdescPG"] . '</small><br>'; 
Having short descriptions on index pages and long descriptions on single episode pages makes sense to me, so...

**Comment by frcoulter** [comment]
Thank you Radiowiec, that answer one of questions about the long description.

Does anybody know:
1. Can categories be sorted alphabetical?
2. Can I remove the "More" button?
3. Why editing & saving episode info takes me to a broken link?

**Comment by Radiowiec** [comment]
The [thread about editing episode page](https://github.com/PodcastGenerator/PodcastGenerator/issues/362) should answer the third of your questions.

**Comment by emilengler** [comment]
Now more displays the long descriptions! Thanks

**Comment by emilengler** [comment]
> Why editing & saving episode info takes me to a broken link?

Which link? I don't have this problem?

**Comment by emilengler** [comment]
Now categories are also sorted alphabetically! :-)
