### ISSUE TITLE
Cron job functionality in 3.1 not working

### ISSUE THREAD

**Issue by astevens93** [PodcastGenerator/PodcastGenerator#360]
**System Information**
Podcast Generator Version: 3.1
Webserver: Apache Version 2.4.46
PHP Version: 7.3

**Description of your problem:**
Is there a known issue with running the CRON job as described here https://podcastgenerator.net/documentation/FAQ-cron-job in 3.1?

I am a new user, and followed the instructions in the link above for 3.1 but could not get PG to auto index the FTP media folder, or re-generate the RSS feed when running this.  

I downgraded to 2.7 and it seems to work fine.  I do recognise that the page I've linked to is not now public on the FAQ section: https://podcastgenerator.net/documentation#faq so perhaps it is not.

It's a really important feature for us to be able to automate episode indexing so for now I am using 2.7.  I would prefer to upgrade to 3.1 because it offers some features that 2.7 does not have (like password protect the main index.php access).

Please let me know if I have missed something that needs to be tweaked to get this to work in 3.1.

Appreciate your help in advance.

**Comment by tomanageit** [comment]
See issue https://github.com/PodcastGenerator/PodcastGenerator/issues/230
I did many tests with version 3.1 without any solution. Version 2.7 still works fine with cron job funtionality.

**Comment by astevens93** [comment]
Thanks @tomanageit  - kind of pleased it is not just me that hasn't found a solution to this.

**Comment by prolibre** [comment]
+1
I have too many problems with this last version and so I stay in 2.7. Unfortunately TinyMCE has expired on version 2.7 (message on the podcast modification page).

**Comment by computertalkradio** [comment]
After the TinyMCE issue, I decided to upgrade to the latest.  Yes, this problem exists for me and it's a pain.

**Comment by tomanageit** [comment]
The cron job functionality is a key feature for me. I'm also still in 2.7 and wait for help.

**Comment by dsuz** [comment]
I checked through source codes and found  auto-indexing by cron is not implemented yet for version 3. It just regenerate RSS and NOT creating xml in media folder. So the best bet is staying version 2.

**Comment by esturniolo** [comment]
Hi guys!
Do you have any update about this?

Thanks!!!

**Comment by emilengler** [comment]
> I checked through source codes and found auto-indexing by cron is not implemented yet for version 3. It just regenerate RSS and NOT creating xml in media folder. So the best bet is staying version 2.

I will implement that

**Comment by emilengler** [comment]
Fixed, it is now implemented and will be released with the next version! Sorry for forgetting it

**Comment by esturniolo** [comment]
Hi guys.
Sorry for reopen this thread, but I download the new version (3.1.1) and I don´t see the cron working. Is this ok?

**Comment by emilengler** [comment]
> Hi guys.
> Sorry for reopen this thread, but I download the new version (3.1.1) and I don´t see the cron working. Is this ok?

This is intended to work that way. With next version I meant 3.2, sorry was a bit unclear. 3.1.1 "only" fixes security vulnerabilities.

**Comment by esturniolo** [comment]
Ohhh!! Ok.
Now is clear.

Thanks!

**Comment by steverueg** [comment]
I'm looking forward to this too.  "this" = a working FTP auto-index via pg-cron.php?key=

**Comment by soundneedle** [comment]
Was this fixed? Running the cron link does not (also) do an auto index (or I've got something wrong). 3.1.2

**Comment by coldacid** [comment]
@soundneedle as @emilengler mentioned in https://github.com/PodcastGenerator/PodcastGenerator/issues/360#issuecomment-770603942 this will be in the next minor release, not in the 3.1 revision releases.

**Comment by dsuz** [comment]
The latest package looks contains fix for this issue. However, I tried and verified it is not working yet.
