### ISSUE TITLE
Hidden Image uploader on version 2.7

### ISSUE THREAD

**Issue by cyros74** [PodcastGenerator/PodcastGenerator#361]
**System Information**
Podcast Generator Version: 2.7
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**
If I add an mp4 video there is no way to add a cover art and the image uploader functionality has been removed in version 2.7. I found the relevant code commented out in upload.php and sendfile.php. See below.

UPLOAD.PHP
`//	$PG_mainbody .= '<label for="image">'._("Image").'</label><br /><span class ="alert">'._("You can associate an image to this episode; it will appear on the recent podcast page and on the details page.").'</span><br /><span class ="alert">'._("Upload a SMALL image (suggested dimensions: 150x150 pixels). Accepted formats: png, gif e jpg.").'</span><br /><br /><input name="image" type="file"><br /><br /><br />';`

SENDFILE.PHP
`//	if (isset($_FILES['image'])) $img= $_FILES['image'] ['name']; // image file`

**Actual behavior**
When I removed the comments from the strings above I could select an image for the podcast, then the podcast file uploads successfully but the image doesn't.

What am I missing?

**Comment by Go-rom** [comment]
Hello,

since PG 2.7 has became a legacy version, it's not supported anymore except when it comes to update it to 3.x
