### ISSUE TITLE
Bug Report - Episode Edit Page

### ISSUE THREAD

**Issue by Rob-McIntyre** [PodcastGenerator/PodcastGenerator#362]
Hi,
We're using version 3.1.
Just moved from 2.7.
When we edit an episode and save we get a 404 page not found error.
The episode updates okay, but we need to reload the main page in order to edit more episodes.
The error log indicates there is something wrong in the keywords section.
Error log entries below:
[04-Dec-2020 18:28:22 UTC] PHP Notice:  Undefined offset: 1 in /home/lp4v2sxkysvi/podcast/admin/episodes_edit.php on line 112
[04-Dec-2020 18:28:22 UTC] PHP Notice:  Undefined offset: 2 in /home/lp4v2sxkysvi/podcast/admin/episodes_edit.php on line 113
[04-Dec-2020 18:28:22 UTC] PHP Notice:  Undefined index: keywords in /home/lp4v2sxkysvi/podcast/admin/episodes_edit.php on line 115
The page generates a url for the destination page but inserts or leaves a code bit in the url.
Wrong url: https://podcast.summitpacific.ca/index.php$url.%22?name=2020-11-18_309_thursday_november_12_2020_-_joel_locke.mp3
Correct url: https://podcast.summitpacific.ca/index.php?name=2020-11-18_309_thursday_november_12_2020_-_joel_locke.mp3
Config file below signature.
I have a few others, but will post them separately for organization and tracking purposes.
Rob McIntyre
IT Director
Summit Pacific College

**Comment by Rob-McIntyre** [comment]
Hi,
SOLVED - spotted the code snippet in the config file when I pasted it here.
For others who may have same issue: Look for this line in config.php: $link = "?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)
Remove "$url. and save.
Rob McIntyre
IT Director
Summit Pacific College

**Comment by emilengler** [comment]
Thanks but keep in mind that the procedure for upgrading is this:

2.7 -> 3.0.1 -> 3.1
