### ISSUE TITLE
Support episode and season numbers

### ISSUE THREAD

**Issue by coldacid** [PodcastGenerator/PodcastGenerator#368]
**Description**

Add support for `<itunes:episode>` and `<itunes:season>` tags (and when finalized, `<podcast:episode>` and `<podcast:season>` from the [podcast namespace project](https://github.com/Podcastindex-org/podcast-namespace)). Also use this information for ordering and displaying episodes on the podcast website.

**Motivation**

This is primarily a metadata improvement for podcast clients and aggregators. However, it is also useful for podcasts which organize their shows into seasons, since it can be used in a theme to group episodes of a season together instead of using a basic 10-per-page paging system.

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by coldacid** [comment]
I'm going to tackle this in the near future.

**Comment by samisaacscreative** [comment]
Hey all, I managed to get this working for a project of mine. Happy to support the development of this for the wider community if you would like some assistance.
