### ISSUE TITLE
Add <podcast:locked> support

### ISSUE THREAD

**Issue by coldacid** [PodcastGenerator/PodcastGenerator#369]
**Description**

Implement support for the `<podcast:locked>` element from the [podcast namespace project](https://github.com/Podcastindex-org/podcast-namespace). See https://github.com/Podcastindex-org/podcast-namespace/blob/main/docs/1.0.md#locked

**Motivation**

This is a step towards fighting podcast piracy. See http://www.insideradio.com/podcastnewsdaily/buzzsprout-adds-locked-tag-feature-encourages-other-hosting-platforms-to-do-the-same/article_64a99b02-17a5-11eb-a6e3-4b3670ca346f.html for some more details about the motivation behind the tag itself, and also the above podcast namespace doc.

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by Go-rom** [comment]
Hello @coldacid 
did you manage to add this feature to your fork ?

**Comment by emilengler** [comment]
I have never heard of the podcast namespaces project although it looks interesting. However instead of adding every single tag to PG it would probably be better to add a feature so users can include custom tags (on channel and episode level) instead.

**Comment by coldacid** [comment]
I haven't added <podcast:locked> yet but it's still on my radar. Given how many more things are in the pipeline for the podcast namespace, it might be better to have the ability to add raw XML at the channel and item levels; the one issue with that however is how easy it could be for someone to accidentally break their feed in more ways than we could probably even think of.

I'd have no problem with the ability to add custom XML to the channel and individual items in the generated feed, but it should be behind a "power users" flag so that anyone who goes for it knows that they're on their own if something gets screwed up. For everyone else, we should have first-party support for at least certain podcast namespace tags:

* podcast:locked
* podcast:season and podcast:episode (building from my earlier season/episode support, now that phase 2 is closed for discussion and about to be officially documented)
* podcast:category*
* podcast:contentRating*

(Items marked * are in phase 3 and still in discussion. It is premature to consider support for these tags at this time, but should be considered in the future.)

**Comment by emilengler** [comment]
I think the best and easiest solution is that the feed parser includes two files `customchannel.xml` and `customitem.xml` where power users can define custom tags. Non power users won't accidentally change something in these files I guess

**Comment by coldacid** [comment]
Given that each episode may have its own set of custom values (for example: podcast:person for guests, podcast:location for a travel podcast) a single customitem.xml file probably won't cut it. For episodes, we'll most likely need to add an additional element in the PG XML file for each episode, with a CDATA block holding its custom XML, emitting that directly into the generated feed.

customchannel.xml itself should probably be a CDATA wrapper for loose XML as well, instead of being directly inserted into the generated feed. Otherwise, there's a good chance that they'll create a proper XML document that when included will cause the generated feed to be improperly formed and non-parsable.

My assumption for this "raw" XML entry for power users will be accessible through the admin UI, which at least gives us the ability to validate for correctness. It's just that those pages should have these textareas hidden by default, and only shown if the user checks off a box that pretty much states "here be dragons".

**Comment by coldacid** [comment]
If that sounds good, I can start working on that probably Thursday, and we can slowly start introducing user-friendly functionality for various podcast namespace features afterwards. This way we can get Podcasting 2.0 compliant feeds out the door sooner rather than later for those on the bleeding edge, while building out support for everyone else as the namespace gets greater adoption.

**Comment by emilengler** [comment]
Yep sounds good
