### ISSUE TITLE
Bug: Edit / Delete Podcast page prefills the "date" field incorrectly.

### ISSUE THREAD

**Issue by StoryHack** [PodcastGenerator/PodcastGenerator#375]
**System Information**
Podcast Generator Version: 3.1
Webserver: Apache
PHP Version: 7.1

The "date" field on admin/episodes_edit.php prefills with the last date the episodes was edited, not the actual publish date as expected.

**Comment by StoryHack** [comment]
This is particularly bothersome, as if you change the publication date, then PG doesn't know how to save the new xml file and rename the mp3.

This is one of the dangers of storing the publication date as part of the filename, rather than as a field in the xml.

**Comment by emilengler** [comment]
> The "date" field on admin/episodes_edit.php prefills with the last date the episodes was edited, not the actual publish date as expected.

This is not a bug. We use the file timestamp of a file to detect when to publish and when it was published. This is indeed not a good solution and a legacy of PG 2.X
