### ISSUE TITLE
Dependencies via Composer

### ISSUE THREAD

**Issue by coldacid** [PodcastGenerator/PodcastGenerator#378]
For some improvements that I am planning to make to Podcast Generator, I'll need to pull in libraries via Composer. @emilengler and other devs, would you have any opposition to doing so?

One immediate effect could be getting rid of components/getid3 and pulling the getid3 library via Composer.

**Comment by coldacid** [comment]
I've created a [branch in my own fork](https://github.com/coldacid/PodcastGenerator/tree/composer "composer") which makes use of Composer for dependencies and replaces the in-repo copy of getid3 with the Composer package instead. This demonstrates the minimum work for switching over, but does not take advantage of features such as autoloader support. 

Something missing from the code is that preparing a release package for Podcast Generator would require going in and running `composer install` inside the PodcastGenerator/ directory to make sure that the dependencies are present before zipping the package.

**Comment by emilengler** [comment]
It's okay to add composer but please don't make it a mandatory feature! Many of Podcast Generator users aren't tech-savvy and don't even know what a shell is so we will continue shipping the libraries statically.

**Comment by coldacid** [comment]
As I mentioned in https://github.com/PodcastGenerator/PodcastGenerator/issues/378#issuecomment-742848410 we should be pre-running Composer when generating zips or tarballs that the users will actually use for installing or updating Podcast Generator. With proper packaging, there should be no need for users to run Composer themselves.

**Comment by coldacid** [comment]
@emilengler when you produce a release of Podcast Generator, how do you do that? If you have an actual build-and-package script, we can update it to handle the Composer bits so that users who download the release package don't have to handle Composer themselves.

**Comment by emilengler** [comment]
> @emilengler when you produce a release of Podcast Generator, how do you do that? If you have an actual build-and-package script, we can update it to handle the Composer bits so that users who download the release package don't have to handle Composer themselves.

I'm doing the release around 2021-06-31. I don't have a script for this also there's nothing against it. All I do is basically modifying the backwards.php and the version number in globs.php and then of course to write a release note

**Comment by coldacid** [comment]
I've worked out, at least in my own fork of the repository, how to generate the PodcastGenerator.zip with Composer dependencies pulled in, via GitHub Actions. I'm going to mainline that packaging first and once I'm comfortable with it I am going to add in Composer.

**Comment by coldacid** [comment]
This landed in commit 87651ff.
