### ISSUE TITLE
Wrong bootstrap URL in default theme

### ISSUE THREAD

**Issue by chatelao** [PodcastGenerator/PodcastGenerator#383]
IS
- https://getbootstrap.org/

SHOULD
- https://getbootstrap.com/

**Comment by Go-rom** [comment]
Didn't find anything inside the code about "getbooststrap.org"
Where did you see this ? (please provide paths and filenames)
Which PG version are you using ?

**Comment by emilengler** [comment]
> Didn't find anything inside the code about "getbooststrap.org"
> Where did you see this ? (please provide paths and filenames)
> Which PG version are you using ?

Funnily it is on the footer of the index.php in the default theme. Fixed it!
