### ISSUE TITLE
feed.xml breaks with "&" in title

### ISSUE THREAD

**Issue by pbassham** [PodcastGenerator/PodcastGenerator#389]
**System Information**
Podcast Generator Version: 3.1
Webserver: Ubuntu
PHP Version: 7.2

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

XML to work

**Actual behavior**
 
the XML broke and wouldnt validate due to the "&" character, in my case, from a title showing up in the ```<author>``` tag
**How to reproduce**

FTP Process a file with a '&' in the title, and then check the feed.xml. it will not work.

I was able to hack a fix it by wrapping the variable in ```htmlspecialcharacter($author)``` manually in ```feed_generator.php```, but i am sure there is a better place for it. But this at least gets it functioning for me

```
$item .= $indent . '<author>' . htmlspecialchars($author) . '</author>' . $linebreak;
        if (!empty($file->episode->authorPG->namePG)) {
            $item .= $indent . '<itunes:author>' . htmlspecialchars($file->episode->authorPG->namePG) . '</itunes:author>' . $linebreak;
```

**Comment by coldacid** [comment]
That is in fact the correct fix. Could you create a PR for this change? Thanks.

**Comment by pbassham** [comment]
here you go
#390

**Comment by coldacid** [comment]
Thanks. I'll get that merged into my integration branch tonight or over the weekend and hopefully @emilengler will merge it into master shortly as well.

**Comment by coldacid** [comment]
Merged into [coldacid:integration](https://github.com/coldacid/PodcastGenerator/tree/integration) for anyone who is following along that branch!

**Comment by Go-rom** [comment]
> Merged into [coldacid:integration](https://github.com/coldacid/PodcastGenerator/tree/integration) for anyone who is following along that branch!

I am !
Thank you very much

**Comment by emilengler** [comment]
Issue was fixed by yourself :-)
Thanks a lot!
See 31bc1f6b84fe2fac9dc0b8100d6632b9842c91e6
