### ISSUE TITLE
CSRF Site Wide

### ISSUE THREAD

**Issue by MMrhassel** [PodcastGenerator/PodcastGenerator#392]
The Admin Panel lack to CSRF Protection which make an attacker to force the admin to perfom mutliple actions such delete users .... !

https://github.com/PodcastGenerator/PodcastGenerator/blob/4da28d5c604e528b22dfd2829e9fda421b9d43e9/PodcastGenerator/admin/pg_users.php#L38
https://github.com/PodcastGenerator/PodcastGenerator/blob/4da28d5c604e528b22dfd2829e9fda421b9d43e9/PodcastGenerator/admin/pg_users.php#L52
https://github.com/PodcastGenerator/PodcastGenerator/blob/4da28d5c604e528b22dfd2829e9fda421b9d43e9/PodcastGenerator/admin/pg_config.php#L13

**Comment by Go-rom** [comment]
Is is possible to give an hand about that through a PR ?
Right now Emil Engler seems to be very busy

**Comment by emilengler** [comment]
Wow thanks for the report! Will try my best to fix it as soon as possible!

**Comment by emilengler** [comment]
Fixed, thanks for the report!
Maybe it checks now a bit more often than it is required but in terms of security it is better too check too much rather than to less

**Comment by MMrhassel** [comment]
@emilengler 
This good now but it should be add also here and also remove ../ https://github.com/PodcastGenerator/PodcastGenerator/blob/4da28d5c604e528b22dfd2829e9fda421b9d43e9/PodcastGenerator/admin/episodes_edit.php#L23

**Comment by emilengler** [comment]
> @emilengler 
> 
> This good now but it should be add also here and also remove ../ https://github.com/PodcastGenerator/PodcastGenerator/blob/4da28d5c604e528b22dfd2829e9fda421b9d43e9/PodcastGenerator/admin/episodes_edit.php#L23

Yes, I saw this yesterday. Will work on it today

**Comment by emilengler** [comment]
FYI: I will release 3.1.1 today with these two security patches applied
