### ISSUE TITLE
podcast pages in one row?

### ISSUE THREAD

**Issue by kolumbus120** [PodcastGenerator/PodcastGenerator#397]
**Description**
I have too many podcasts. I have 55 pages, but they are in one row. If I remember in old PG they was i more rows. It looks better than scroll to right to click on 54 page
**Motivation**
Just looks not good then you have to scroll to right for older pages
**Legal aspect**

* [ x] I am the inventor of this idea or the idea is public domain
* [x ] I release this idea into the public domain

**Comment by emilengler** [comment]
Modify the `$episodeperpage` variable in config.php

**Comment by kolumbus120** [comment]
> Modify the `$episodeperpage` variable in config.php

Hi. Thank you,
Maybe I was not corret because of my english.
But what if I want use 10 epizodes per page but have the rest numbers of pages in more rows. see prntscr.
I understatnd if I use epusideperpage higher number it does less pages. But it the future I will have the same problem.
Thank you
![prntscr](https://user-images.githubusercontent.com/11219097/107216756-7d0c2880-6a0d-11eb-815c-895eed0cb3ef.png)
