### ISSUE TITLE
Dutch language translations is ready for production

### ISSUE THREAD

**Issue by henrydenhengst** [PodcastGenerator/PodcastGenerator#398]
I checked the [translation](https://www.transifex.com/albertobeta/podcast-generator/translate/#nl_NL/31/291668485) for the Dutch language and it is fine. It can go to production.

On the Dashboard it states that 8 strings are to be translated and 629 strings approval, however in the language section for translation it is shown that 189 lines are translated and 189 not yet approved.

If there is anything to be translated or approved in Dutch just let me know.

(I could not find a way in Transifex to pass on this message.)

**Comment by emilengler** [comment]
Thanks, I will review and import this week or weekend
