### ISSUE TITLE
Where is the Scripts folder that needs to be writeable?

### ISSUE THREAD

**Issue by SEJohnsen** [PodcastGenerator/PodcastGenerator#399]
**System Information**
Podcast Generator Version: 3.1.1
Webserver: Centos 7
PHP Version: 7.4

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**

The installation script on Step 2 says "Scripts is not writeable. Try to adjust file permissions." However, I cannot find the "Scripts" folder. What is this referring to?

**Comment by emilengler** [comment]
The scripts folder is the root directory of Podcast Generator (where all files and folders including media and images are located in)

**Comment by SEJohnsen** [comment]
Emil,
 
Thank you for your quick reply. Since that permission typically applies
recursively, is that redundant with making media and images writeable? And
I'm sorry if this is a dumb question, but is that a security risk, if the
entire public folder is writeable?
 
Best regards,
 
Steve Johnsen

  _____

**Comment by emilengler** [comment]
Just assign the www group to the folder

**Comment by SEJohnsen** [comment]
Emil,
 
Thanks. That works.
 
Best regards,
 
Steve Johnsen

  _____
