### ISSUE TITLE
RSS Redirect (Vol 2.0)

### ISSUE THREAD

**Issue by andyhanselman** [PodcastGenerator/PodcastGenerator#400]
**System Information**
Podcast Generator Version: 3.0.1
Webserver: Apache
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

I saw that as of January of last year, autoredirects of the PG RSS feed to third parties are not allowed. Are automatic redirects of the RSS feed available in the newest version? My client wants to move all of the podcast uploads to Anchor without losing their subscriber base. I did find this article (https://podcastgenerator.net/documentation/FAQ-change-RSS-URL) on your FAQ page, however $feed_URL_replace = ""; is not in my config.php file. I added the line, but it didn't make any changes to my configuration - still not able to redirect to Anchor. Please advise. Thanks!

**Comment by emilengler** [comment]
It's not possible to do this, however you can configure your web server to do so. In your case see here: https://www.hostwinds.com/guide/set-temporary-302-redirect-using-htaccess/

**Comment by andyhanselman** [comment]
Thanks. Worked like a champ. I appreciate the help.
