### ISSUE TITLE
How to upload multiple shows using FTP?

### ISSUE THREAD

**Issue by muhammadnasr** [PodcastGenerator/PodcastGenerator#402]
Thanks for the great project.
is there a way to upload multiple shows using FTP?

**Comment by emilengler** [comment]
No, you need to set up multiple instances of Podcast Generator. However, I doubt that this will be a problem as PG doesn't need databases anyway

**Comment by muhammadnasr** [comment]
Thank you for your reply. Would it be a problem to have around 400 instances?

We have around 400 books and each book have a series of episodes (in order of 10s) that explains it.

We need to upload all those books along with their episodes (order of 1000s). 

I'm a bit new to podcasts, What do you recommend?

**Comment by emilengler** [comment]
I don't think it'll case any problems except a bit more storage consumption.
