### ISSUE TITLE
No upload possible using admin interface

### ISSUE THREAD

**Issue by Exitare** [PodcastGenerator/PodcastGenerator#403]
**System Information**
Podcast Generator Version:  3.1.1
Webserver: Nginx
PHP Version:  7.4.3

**Podcast Generator Config**
I didn't touch the config and your censor tool is not doing anything after pressing the button.

**Description of your problem:**
I am unable to upload new episodes. After providing information for each required field and providing an mp3 file i press the upload episode button.
Podcast generator is then starting to execute the upload.php and that's it. Nothings happen anymore.

<img width="730" alt="Screen Shot 2021-03-11 at 23 53 20" src="https://user-images.githubusercontent.com/13048528/110909472-f759f200-82c4-11eb-8031-d09ee7374bee.png">

**Comment by emilengler** [comment]
You have some kind of nginx error logs?

**Comment by Exitare** [comment]
I am trying to get my hands on them if there are any.

**Comment by Exitare** [comment]
The problem was related to my server configuration. Thanks for your fast response!
I fixed the issue, it was related to php post upload limit.
