### ISSUE TITLE
Categories feed

### ISSUE THREAD

**Issue by Quentin-ctrL** [PodcastGenerator/PodcastGenerator#404]
Hi,

I installed Podcast Generator Version 3.1.1 and I can't feed feed by categories :/
In the demo, I can find it easily (ex: http://www.podcastgenerator.net/demoV2/pg/feed.php?cat=music)
Is this feature removed ?

Thanks

**Comment by emilengler** [comment]
Turns out yes, I forgot it. Will try to reimplement it

**Comment by Quentin-ctrL** [comment]
Nice !
Do you have a release date in mind ?

**Comment by emilengler** [comment]
I plan to release it in the end of june

**Comment by emilengler** [comment]
I might do a quicker pre-release though

**Comment by emmebrus** [comment]
I have the same problem with PG 2.7 version and with PG 2.3 version. Can you help me? Thanks.
