### ISSUE TITLE
Doesn't work. File not found.

### ISSUE THREAD

**Issue by primanox007** [PodcastGenerator/PodcastGenerator#412]
**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

**Actual behavior**
 

**How to reproduce**

**Comment by primanox007** [comment]
Even your support thingie doesn't work! LOL! all the fields I filled in are blank!

To summarize: I uploaded the files and folders (v. 3.1.1) to my server. Directed my browser to their location, and get "FILE NOT FOUND". No setup page, no nothing. Just 404. Nice job lads.

**Comment by emilengler** [comment]
How can I help you when you don't even provide anything? Not even an error log which would be super productive. How do you think I am even motivated in helping you when you enter this project with such a negative attitude?

**Comment by primanox007** [comment]
Figured it out. Was pointing to the wrong folder. It's not clear that you have to navigate to the /PodcastGenerator/PodcastGenerator. I was one level up. That was the issue. 
In response to emilengler, the issue reporting page is not end-user friendly. I don't know html.
