### ISSUE TITLE
Import existing podcast

### ISSUE THREAD

**Issue by primanox007** [PodcastGenerator/PodcastGenerator#413]
**System Information**
Podcast Generator Version: 3.1.1
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```not necessary 

**Description of your problem:**
**Can you import an existing podcast / xml file into the generator?**

**Comment by emilengler** [comment]
No, you can't. This is due to the fact that as far as I know there is no standardized way on how people store Podcasts.
