### ISSUE TITLE
Cant use character åäö in categories

### ISSUE THREAD

**Issue by tellustheguru** [PodcastGenerator/PodcastGenerator#415]
**System Information**
Podcast Generator Version: 
Webserver: Apache 2
PHP Version: 7.4.6

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

A categorie name containg charactar åäö or ÅÄÖ
**Actual behavior**
 
PG does not displaying any categories...
**How to reproduce**

**Comment by NedNet29** [comment]
Hi, 
I believe it's the same problem as mentioned here : https://github.com/PodcastGenerator/PodcastGenerator/issues/386#issuecomment-819270080
HTH

**Comment by emilengler** [comment]
I cannot reproduce on current git master. Either this was fixed already or your setup was kinda unique.
I expect to ship Podcast Generator 3.2 the next days. If the problem persists, we will open the issue again
