### ISSUE TITLE
FTP automatic indexing error if there is an ampersand in the file name

### ISSUE THREAD

**Issue by poison361** [PodcastGenerator/PodcastGenerator#417]
In the old version, there was an option in the settings to automatically rename files containing special characters. Now there is no such setting, and if, for example, the file name contains an ampersand, an error appears in the XML RSS feed, since the ampersand is a service character. It would be good to return the functionality of automatic file renaming, and not just use the strictfilenamepolicy parameter, when files with special characters are simply skipped and do not get into the podcast feed.

**Comment by N4444VX** [comment]
Also unable to edit/delete episode. Gives "Episode does not exist" error. Also breaks RSS feed for me with message **error on line 133 at column 119: EntityRef: expecting ';'**

**Comment by coldacid** [comment]
Strict name policy is going to stay, but with 3.2 filenames will at least be encoded in the RSS feed so as to not break that.
