### ISSUE TITLE
Theme & Stats in header?

### ISSUE THREAD

**Issue by srice777** [PodcastGenerator/PodcastGenerator#421]
**System Information**
Podcast Generator Version: 3.1.1
Webserver: Shared Hosting - Linux Server
PHP Version: 8.0

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

**Description of your problem:**

First let me say a big THANK YOU! for this software.  It is an amazing little work you have going on here.  I would like to add stats to my podcastgenerator installation, but I'm really unsure where to add them.  I opened the categories.php and index.php in the /themes/default folder and pasted the code needed at just before the </header> code as instructed. However it doesn't appear to track anything.  I'm using Matomo to track my stats. It works great on the other 3 web sites I have placed it. So I know it is working, just can't seem to find the right place to plug it in with Podcast Generator.  I sure hope we can get this solved. Thank you again for all the work and effort you have put into this. It works like a charm!

-Shane

**Comment by coldacid** [comment]
Is Matomo something like Google Analytics?

**Comment by srice777** [comment]
Yes, it is an independent privacy oriented analytics tracker. https://matomo.org/ I have it installed on my server.

Sincerely,
Shane Rice

**Comment by coldacid** [comment]
Where are the instructions you followed to put Matomo into your site? And what's the URL of your site so I can take a look at the HTML being generated?

**Comment by srice777** [comment]
Chris,

	I installed Matomo following these intructions:  https://matomo.org/docs/installation/ <https://matomo.org/docs/installation/>  It was pretty easy. I have been using it for about a year now.
I have podcast generator setup here: www.audio.anchorbaptistchurch.net <http://www.audio.anchorbaptistchurch.net/>. I appreciate you taking a look at this.

__________________
Sincerely,
Shane Rice

John 3:16 For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life. For God sent not his Son into the world to condemn the world; but that the world through him might be saved.

**Comment by coldacid** [comment]
Well, it looks like it's installed in the theme index.php properly. After disabling my privacy protection extensions in the browser, your stats server was successfully hit with the information collected by matomo.js, which was properly added to the website by the Javascript block on the page.

EFF Privacy Badger, uBlock Origin, and ClearURLs browser extensions all block the request to the stats server. If you or other visitors to the site have any of those installed, don't expect to get any information on them.
