### ISSUE TITLE
Podcast generator 3.1 3.1.1 installetion failed

### ISSUE THREAD

**Issue by emmebrus** [PodcastGenerator/PodcastGenerator#422]
When I try to install 3.1 or 3.1.1 PG, it appears this
Fatal error: Call to undefined function password_hash() in /web/htdocs/www.associazioneinfinitamente.it/home/podcastprova/setup/createconf.php on line 29 
Can you help me? Thanks.

**Comment by coldacid** [comment]
What version of PHP do you have on your server? `password_hash()` requires at least PHP 5.5.
