### ISSUE TITLE
Incorrect sub category format for Apple

### ISSUE THREAD

**Issue by cohrs** [PodcastGenerator/PodcastGenerator#430]
**System Information**
Podcast Generator Version: 3.1.1 and below
Webserver: apache
PHP Version: 7.2.34

**Podcast Generator Config**

```
Config tool didn't give output but this is the part that is causing issues
$itunes_category[0] = "Business:Marketing"; // iTunes categories (mainCategory:subcategory)

$itunes_category[1] = "";

$itunes_category[2] = "";

```  

**Expected behavior**
Apple has seemingly changed the way these sub categories should be displayed in feed.xml. The want subcategories to be nexted like below
`<itunes:category text="Business">
<itunes:category text="Marketing"/> 
</itunes:category>`

**Actual behavior**
This is how they are being rendered
`<itunes:category text="Business:Marketing"/>`

**How to reproduce**
Choose any subcategory like -- Business:Marketing from the dropdown menu
Go to this URL and put in your rss feed and you will see an error
https://castfeedvalidator.com/

**Comment by coldacid** [comment]
This should be fixed with #365
