### ISSUE TITLE
Feature request ; new google tags on rss feed from 21 September 2021

### ISSUE THREAD

**Issue by gravas68** [PodcastGenerator/PodcastGenerator#432]
Can the new tags required by Google be incorporated into the rss feed?

**    Podcast RSS feeds must include a valid, crawlable image

    Specify the image for your podcast using any one of these elements:

        <googleplay:image>
        <itunes:image>
        <image>

    You can check if you have a valid, crawlable image by searching for your podcast on Google Podcasts. If you see your podcast artwork, then you are meeting this requirement. If you don’t see podcast artwork that you selected for your podcast, follow these troubleshooting steps:

        Make sure that Googlebot is not blocked by robots.txt from indexing your artwork.
        More details on robots.txt and how to manage it can be found in this developer page.

    Podcast RSS feeds must include a description

    A user-friendly description of your podcast must be included using any one of these elements:

        <description>
        <googleplay:description>
        <itunes:summary>

    Podcast RSS feeds must include an author

    The <itunes:author> or <googleplay:author> element must be populated with the name of the organization that you want to appear to listeners as the author of your podcast. This is not the same as the podcast owner requirement (next point below).

    Podcast RSS feeds must define a correctly formatted owner email address

    A valid email address must be defined within <itunes:email> or <googleplay:owner> elements inside your RSS feed.

    If you want to claim your podcast in Google Podcasts Manager, you will need to be able to access this email for verification purposes. 

    If you use a 3rd party hosting provider, please refer to their documentation or contact them to change the email address, if needed.

    Podcast RSS feeds must include correctly formatted link to a valid homepage

    <link> element must be populated with a valid and crawlable URL of your podcast’s homepage.

    Linking your podcast to a homepage will help the discovery and presentation of your podcast on Google surfaces. Also read our previous community post on this topic.**

**Comment by coldacid** [comment]
The tags are already included and supported in Podcast Generator. You just need to configure your podcast site appropriately.

Description, author, and email address can be configured on the *Podcast Details > Change Podcast Details* admin page, and the cover can be configured on the *Podcast Platform Settings > Change Cover Art* admin page. The link tag is automatic based on your PG installation.
