### ISSUE TITLE
Setup step 3 not working.

### ISSUE THREAD

**Issue by sajanssens** [PodcastGenerator/PodcastGenerator#438]
I try to install a new instance of pgen 3.1.1 on my externally hosted environment. However, after entering username/password for admin, I get a blank screen. Directory permissions are 755. I have an older instance (2018) running on the same server without problems. I don't know how to access logfiles. I think I don't have permission.

Reproduce here: http://bramjanssens.nl/pgen/setup/

**Comment by SIMPO18** [comment]
I have the same problem. After setp3 it returns to a blank screen. And close and open again it is still blank. Have you solved this issue yet?

**Comment by sajanssens** [comment]
Unfortunately not. I have used older version...

**Comment by coldacid** [comment]
@sajanssens Do you know what web server and version of PHP is run in your hosting environment? It would be helpful to get the result of phpinfo() for figuring out what's wrong.

**Comment by sajanssens** [comment]
Here it is: http://bramjanssens.nl/info/

**Comment by coldacid** [comment]
Yep, right off the bat you are using an old and unsupported version of PHP. For Podcast Generator 3.0 or newer, you need to be running at least PHP 7.0, preferably 7.4 or newer (as versions older than 7.3 are no longer supported even for security fixes, and 7.3 is about to be dropped when PHP 8.1 is released).

You will need to speak with your service provider about having PHP upgraded. Given the age of PHP 5.x, they shouldn't even be providing such an old version anymore!

**Comment by sajanssens** [comment]
Great, thanks for your swift reply. I'll contact my SP and tell them to upgrade a.s.a.p.!
