### ISSUE TITLE
i can't upload m4a files to podcast

### ISSUE THREAD

**Issue by thadeu220** [PodcastGenerator/PodcastGenerator#442]
i can't upload new episodes... it says this:
Unsupported mime type detected for file with extension .m4a
how do i fix this? i need to upload as M4a / AAC...
i sawd something about adding a new mime type via litespeed, using htaccess... but no idea where do i put the moded .htaccess file
do i put in the pg 3.1 directory, or, in the root of my /home/user folder?
help!
i could upload via mp3 but, this way apple podcasts are not playing with mp3... trying using m4a.

PHP version = 7.4.11
PG version: = 3.1.1
webserver: litespeed
type of file: m4a

if i missed something, please tell me and i edit the issue topic.
i need help!
i need to enable AAC mime type

**Comment by coldacid** [comment]
It looks like the getid3 library we use to determine MIME type and metadata isn't returning a type that Podcast Generator recognized. The change for this does not involve editing .htaccess files but rather one of the component files of Podcast Generator. Could you attach or provide the URL to one of the files that is causing this issue? That way I can determine how to best update the media types component file and provide you with a hotfix for the problem.

**Comment by coldacid** [comment]
This should be fixed in version 3.1.2, please try upgrading and let us know if you are able to upload AAC and M4A episodes now.

**Comment by coldacid** [comment]
New release has fixed the bug
Thanks

> Em 25 de nov. de 2021, à(s) 11:44, Chris Charabaruk ***@***.***> escreveu:
> 
> ﻿
> @thadeu220 your particular issue is not related to htaccess or litespeed httpd but rather a component of Podcast Generator itself. This is fixed in 3.1.2 but that version itself has problems caused when upgrading from an earlier version of PG.
> 
> For now, download this file and copy it over components/supported_media/supported_media.xml in your Podcast Generator directory. That should fix the M4A/AAC upload problem.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.

_Originally posted by @thadeu220 in https://github.com/PodcastGenerator/PodcastGenerator/issues/283#issuecomment-979346453_
