### ISSUE TITLE
Upgrading to 3.1.2 deletes user credentials from config.php file

### ISSUE THREAD

**Issue by jameswill** [PodcastGenerator/PodcastGenerator#443]
**System Information**
Podcast Generator Version: 3.1.2
Webserver: Linux
PHP Version:PHP 7.0

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**
Unable to login into the admin panel as $users_json array in config.php gets emptied.

**Actual behavior**
Details of $users_json should remain as it is so one can login into the admin panel. 

**How to reproduce**
Extract the new package on Podcast 3.1.1
Visiting admin panel vanishes admin details from config.php

**Comment by coldacid** [comment]
Wow, that is really strange. Does this happen whenever visiting admin pages or just the first time after upgrading?

**Comment by jameswill** [comment]
Hi,

I am not able to login into admin panel forever. Because admin details are got emptied from config.php file.

**Comment by coldacid** [comment]
This should be fixed now in 3.1.3.
