### ISSUE TITLE
Can’t see podcasts scheduled for future 

### ISSUE THREAD

**Issue by dskeen** [PodcastGenerator/PodcastGenerator#445]
The issue of not being able to see podcasts scheduled for future date and time has returned with 3.1.2

**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

**Actual behavior**
 

**How to reproduce**

**Comment by coldacid** [comment]
Related: #175

**Comment by coldacid** [comment]
Fixed in 3.2 with a new admin episodes list page.
