### ISSUE TITLE
error 500 after setup

### ISSUE THREAD

**Issue by stefansegers** [PodcastGenerator/PodcastGenerator#447]
**System Information**
Podcast Generator Version: 
Webserver: NGIX on Synology DSM7
PHP Version: 7.4

**Podcast Generator Config**
<?php
$podcastgen_version = "3.1.2"; // Version

$first_installation = 1638661916;

$installationKey = "EvNiHh5v";

$scriptlang = "en_US";

$url = "http://10.0.0.50/podcastgen/";

$absoluteurl = "/volume2/web/podcastgen/"; // The location on the server

$theme_path = "themes/default/";

$upload_dir = "media/"; // "media/" the default folder (Trailing slash required). Set chmod 755

$img_dir = "images/"; // (Trailing slash required). Set chmod 755

$feed_dir = ""; // Where to create feed.xml (empty value = root directory). Set chmod 755

$max_recent = "all"; // How many file to show in the home page

$recent_episode_in_feed = "All"; // How many file to show in the XML feed (1,2,5 etc.. or "All")

$episodeperpage = 10;

$enablestreaming = "yes"; // Enable mp3 streaming? ("yes" or "no")

$freebox = "yes"; // enable freely customizable box

$enablepgnewsinadmin = "yes";

$strictfilenamepolicy = "no"; // strictly rename files (just characters A to Z and numbers) 

$categoriesenabled = "yes";

$cronAutoIndex = 1; //Auto Index New Episodes via Cron

$cronAutoRegenerateRSS = 1; //Auto regenerate RSS via Cron

$indexfile = "index.php";    // Path of the index file

$podcastPassword = "";       // Password to protect the podcast generator webpages, this will NOT protect the audio or XML files. Leave blank to disable.

#####################
# XML Feed stuff

$podcast_title = "Podcast Title";

$podcast_subtitle = "Subtitle";

$podcast_description = "A little description of your podcast.";

$author_name = "Podcast Generator User";

$author_email = "podcastgenerator@example.com";

$itunes_category[0] = "Arts"; // iTunes categories (mainCategory:subcategory)
$itunes_category[1] = "";
$itunes_category[2] = "";

$link = "?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

$feed_language = "en";

$copyright = "All rights reserved";   // Your copyright notice (e.g CC-BY)

$feed_encoding = "utf-8";

$explicit_podcast = "no"; //does your podcast contain explicit language? ("yes" or "no")

$users_json = "{\"stefan\": \"\$2y\$10\$UXZaCQaC9BQDDSg54SMxO.KVAHoVrq5T.IabnaRVYlXJYWkKwgUXa\"}";

// END OF CONFIG

``` 

**Description of your problem:**
So I have downloaded version 3.0 and 3.1.2 on the Synology web server. After setting ALL files and folder to 777 and start the setup I could setup the name/password. After that the app won't start and give error 500.
.

what am i doing wrong here?

**Comment by coldacid** [comment]
Do you have an error.log file from the web server?

**Comment by stefansegers** [comment]
Hi Chris,

Thanks for getting back to me so quickly!
I tried everything to get the log files, but since I am a designer and not
a Linux guru I could not find the files you need.

I tried on my Synology:
- ssh ***@***.*** -p custom_port
then logged in
- sudo -i

- cd /var/log/httpd
- ls

there is the file apache_error_log

From there I tried wget but did not work, Curl not working

ALso tried VIM aparache_log, but the file looks empty.

Maybe I used the wrong file? Also no idea how to download the file?

Sorry for al my noob questions

Op zo 5 dec. 2021 om 21:11 schreef Chris Charabaruk <
***@***.***>:

**Comment by coldacid** [comment]
I would suggest copying apache_error_log to the SSH user home directory, changing ownership to the SSH user, and then using sftp or scp to copy the file from the device to your local computer.

In addition, do you know what version of PHP is installed on your Synology device? Since 3.0, Podcast Generator requires PHP 7+, and PHP versions older than 7.3 are no longer supported by the PHP developers themselves.

**Comment by stefansegers** [comment]
Hi Chris,

My Synology runs Web Station with ngnix + Php 7.0-7.1-7.2-7.3 and 7.4
I can delete the older versions if needed?
[image: Schermafbeelding 2021-12-06 om 19.22.32.png]

I found the /var/log/nginx/error.log

This is what I found in t he log:

Stack trace:
#0 /volume2/web/podcastgen/core/include_admin.php(34): include()
#1 /volume2/web/podcastgen/admin/login.php(15):
require('/volume2/web/po...')
#2 {main}
  thrown in /volume2/web/podcastgen/core/translation.php on line 14" while
reading response header from upstream, client: 10.0.0.136, server: ,
request: "GET /podcastgen/admin/login.php HTTP/1.1", upstream:
"fastcgi://unix:/run/php-fpm/php-c955c07d-aa67-4013-bcda-4189fb9a1f34.sock:",
host: "10.0.0.50"
2021/12/06 08:56:23 [error] 13774#13774: *137197 open()
"/var/services/web/missing" failed (2: No such file or directory), client:
10.0.0.136, server: , request: "GET /missing HTTP/1.1", host: "10.0.0.50",
referrer: "http://10.0.0.50/podcastgen/admin/login.php"
2021/12/06 09:00:52 [error] 13772#13772: *137250 open()
"/var/services/web/.env" failed (2: No such file or directory), client:
202.73.34.226, server: , request: "GET /.env HTTP/1.1", host:
"85.145.240.217"
2021/12/06 09:31:02 [error] 13773#13773: *137260 open()
"/var/services/web/api/bong88-links" failed (2: No such file or directory),
client: 23.183.83.113, server: , request: "GET /api/bong88-links HTTP/1.1",
host: "apibx.bongx9.com", referrer: "https://apibx.bongx9.com
<https://mailtrack.io/trace/link/42e1f8382b9bb1e51e76f929500dd33eab5acd40?url=https%3A%2F%2Fapibx.bongx9.com&userId=4868474&signature=f40c049367c6fb09>
"
2021/12/06 09:41:39 [error] 13774#13774: *137265
"/var/services/web/zeh7dkwfdxw99tdk/index.html" is not found (2: No such
file or directory), client: 80.82.78.39, server: , request: "GET
/zeh7dkwfdxw99tdk/ HTTP/1.1", host: "85.145.240.217:443"
2021/12/06 10:42:08 [error] 13774#13774: *137439
"/var/services/web/solr/index.html" is not found (2: No such file or
directory), client: 162.221.192.26, server: , request: "GET /solr/
HTTP/1.1", host: "85.145.240.217"
2021/12/06 11:20:36 [error] 13772#13772: *137443 open()
"/var/services/web/mifs/.;/services/LogService" failed (2: No such file or
directory), client: 45.155.205.233, server: , request: "POST
/mifs/.;/services/LogService HTTP/1.1", host: "85.145.240.217:443",
referrer: "https://85.145.240.217:443"
2021/12/06 12:04:46 [error] 13772#13772: *137463 open()
"/var/services/web/actuator/health" failed (2: No such file or directory),
client: 192.241.215.63, server: , request: "GET /actuator/health HTTP/1.1",
host: "85.145.240.217"
2021/12/06 12:46:49 [error] 13773#13773: *137470
"/var/services/web/console/index.html" is not found (2: No such file or
directory), client: 45.155.205.233, server: , request: "GET /console/
HTTP/1.1", host: "85.145.240.217:443"
2021/12/06 13:23:43 [error] 13774#13774: *137480 open()
"/var/services/web/.env" failed (2: No such file or directory), client:
109.237.103.38, server: , request: "GET /.env HTTP/1.1", host:
"85.145.240.217"
2021/12/06 14:03:22 [error] 13773#13773: *137486 open()
"/var/services/web/skidn/app/download/list" failed (2: No such file or
directory), client: 23.183.83.113, server: , request: "GET
/skidn/app/download/list HTTP/1.1", host: "api.skidn.com", referrer: "
https://api.skidn.com
<https://mailtrack.io/trace/link/a5236be04bcc7fe9b4ec26f184c15f7edda17865?url=https%3A%2F%2Fapi.skidn.com&userId=4868474&signature=069ba986e681302b>
"
2021/12/06 14:20:37 [error] 13770#13770: *137489 open()
"/var/services/web/_ignition/execute-solution" failed (2: No such file or
directory), client: 45.155.205.233, server: , request: "GET
/_ignition/execute-solution HTTP/1.1", host: "85.145.240.217:443"
2021/12/06 16:59:29 [error] 13770#13770: *138063 open()
"/var/services/web/robots.txt" failed (2: No such file or directory),
client: 3.126.85.81, server: , request: "GET /robots.txt HTTP/1.1", host: "
stefsegers.synology.me"
2021/12/06 17:12:15 [error] 13773#13773: *138073 open()
"/var/services/web/robots.txt" failed (2: No such file or directory),
client: 35.215.117.69, server: , request: "GET /robots.txt HTTP/1.1", host:
"thuis.stefansegers.nl"
2021/12/06 17:12:21 [error] 13770#13770: *138076 open()
"/var/services/web/scrollbar/initFlexcroll.js" failed (2: No such file or
directory), client: 35.215.117.69, server: , request: "GET
/scrollbar/initFlexcroll.js HTTP/1.1", host: "thuis.stefansegers.nl",
referrer: "http://thuis.stefansegers.nl/
<https://mailtrack.io/trace/link/044154c289c8e6bbc267e9e0608ab629b17da184?url=http%3A%2F%2Fthuis.stefansegers.nl%2F&userId=4868474&signature=f8d6d0a3f49d2346>
"
2021/12/06 17:12:21 [error] 13773#13773: *138079 open()
"/var/services/web/scrollbar/flexcroll.js" failed (2: No such file or
directory), client: 35.215.117.69, server: , request: "GET
/scrollbar/flexcroll.js HTTP/1.1", host: "thuis.stefansegers.nl", referrer:
"http://thuis.stefansegers.nl/
<https://mailtrack.io/trace/link/2d91ff2e4d5f764cb8e908a533e46704ca6582ea?url=http%3A%2F%2Fthuis.stefansegers.nl%2F&userId=4868474&signature=cd5a1e1dac7a8c7c>
"
2021/12/06 17:12:36 [error] 13773#13773: *138086 open()
"/var/services/web/app-ads.txt" failed (2: No such file or directory),
client: 35.215.117.69, server: , request: "GET /app-ads.txt HTTP/1.1",
host: "thuis.stefansegers.nl"
2021/12/06 17:12:36 [error] 13770#13770: *138087 open()
"/var/services/web/ads.txt" failed (2: No such file or directory), client:
35.215.117.69, server: , request: "GET /ads.txt HTTP/1.1", host: "
thuis.stefansegers.nl"
2021/12/06 17:15:27 [error] 13773#13773: *138099 open()
"/var/services/web/help.css" failed (2: No such file or directory), client:
27.115.124.9, server: , request: "GET /help.css HTTP/1.1", host:
"85.145.240.217", referrer: "https://85.145.240.217/"
2021/12/06 17:15:27 [error] 13774#13774: *138101 open()
"/var/services/web/scrollbar/flexcroll.css" failed (2: No such file or
directory), client: 27.115.124.9, server: , request: "GET
/scrollbar/flexcroll.css HTTP/1.1", host: "85.145.240.217", referrer: "
https://85.145.240.217/"
2021/12/06 17:15:27 [error] 13773#13773: *138103 open()
"/var/services/web/scrollbar/flexcroll.js" failed (2: No such file or
directory), client: 27.115.124.9, server: , request: "GET
/scrollbar/flexcroll.js HTTP/1.1", host: "85.145.240.217", referrer: "
https://85.145.240.217/"
2021/12/06 17:15:27 [error] 13773#13773: *138105 open()
"/var/services/web/scrollbar/initFlexcroll.js" failed (2: No such file or
directory), client: 27.115.124.9, server: , request: "GET
/scrollbar/initFlexcroll.js HTTP/1.1", host: "85.145.240.217", referrer: "
https://85.145.240.217/"
2021/12/06 17:15:36 [error] 13771#13771: *138112 open()
"/var/services/web/favicon.ico" failed (2: No such file or directory),
client: 27.115.124.43, server: , request: "GET /favicon.ico HTTP/1.1",
host: "85.145.240.217"
2021/12/06 17:15:37 [error] 13769#13769: *138115 open()
"/var/services/web/robots.txt" failed (2: No such file or directory),
client: 27.115.124.43, server: , request: "GET /robots.txt HTTP/1.1", host:
"85.145.240.217"
2021/12/06 17:15:38 [error] 13774#13774: *138118 open()
"/var/services/web/sitemap.xml" failed (2: No such file or directory),
client: 27.115.124.9, server: , request: "GET /sitemap.xml HTTP/1.1", host:
"85.145.240.217"
2021/12/06 17:15:45 [crit] 13772#13772: *138128 SSL_do_handshake() failed
(SSL: error:141CF06C:lib(20):func(463):reason(108)) while SSL handshaking,
client: 27.115.124.75, server: 0.0.0.0:443
2021/12/06 19:11:40 [error] 13774#13774: *138306 FastCGI sent in stderr:
"PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function
bindtextdomain() in /volume2/web/podcastgen/core/translation.php:14
Stack trace:
#0 /volume2/web/podcastgen/core/include.php(30): include()
#1 /volume2/web/podcastgen/index.php(11): require('/volume2/web/po...')
#2 {main}
  thrown in /volume2/web/podcastgen/core/translation.php on line 14" while
reading response header from upstream, client: 10.0.0.136, server: ,
request: "GET /podcastgen/ HTTP/1.1", upstream:
"fastcgi://unix:/run/php-fpm/php-c955c07d-aa67-4013-bcda-4189fb9a1f34.sock:",
host: "10.0.0.50"
2021/12/06 19:11:40 [error] 13770#13770: *138309 open()
"/var/services/web/missing" failed (2: No such file or directory), client:
10.0.0.136, server: , request: "GET /missing HTTP/1.1", host: "10.0.0.50",
referrer: "http://10.0.0.50/podcastgen/"
2021/12/06 19:11:44 [error] 13769#13769: *138313 FastCGI sent in stderr:
"PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function
bindtextdomain() in /volume2/web/podcastgen/core/translation.php:14
Stack trace:
#0 /volume2/web/podcastgen/core/include.php(30): include()
#1 /volume2/web/podcastgen/index.php(11): require('/volume2/web/po...')
#2 {main}
  thrown in /volume2/web/podcastgen/core/translation.php on line 14" while
reading response header from upstream, client: 10.0.0.136, server: ,
request: "GET /podcastgen/ HTTP/1.1", upstream:
"fastcgi://unix:/run/php-fpm/php-c955c07d-aa67-4013-bcda-4189fb9a1f34.sock:",
host: "10.0.0.50"
2021/12/06 19:11:44 [error] 13771#13771: *138316 open()
"/var/services/web/missing" failed (2: No such file or directory), client:
10.0.0.136, server: , request: "GET /missing HTTP/1.1", host: "10.0.0.50",
referrer: "http://10.0.0.50/podcastgen/"
2021/12/06 19:11:44 [error] 13774#13774: *138318 FastCGI sent in stderr:
"PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function
bindtextdomain() in /volume2/web/podcastgen/core/translation.php:14
Stack trace:
#0 /volume2/web/podcastgen/core/include.php(30): include()
#1 /volume2/web/podcastgen/index.php(11): require('/volume2/web/po...')
#2 {main}
  thrown in /volume2/web/podcastgen/core/translation.php on line 14" while
reading response header from upstream, client: 10.0.0.136, server: ,
request: "GET /podcastgen/ HTTP/1.1", upstream:
"fastcgi://unix:/run/php-fpm/php-c955c07d-aa67-4013-bcda-4189fb9a1f34.sock:",
host: "10.0.0.50"
2021/12/06 19:11:44 [error] 13774#13774: *138323 open()
"/var/services/web/missing" failed (2: No such file or directory), client:
10.0.0.136, server: , request: "GET /missing HTTP/1.1", host: "10.0.0.50",
referrer: "http://10.0.0.50/podcastgen/"
2021/12/06 19:11:44 [error] 13773#13773: *138325 FastCGI sent in stderr:
"PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function
bindtextdomain() in /volume2/web/podcastgen/core/translation.php:14
Stack trace:
#0 /volume2/web/podcastgen/core/include.php(30): include()
#1 /volume2/web/podcastgen/index.php(11): require('/volume2/web/po...')
#2 {main}
  thrown in /volume2/web/podcastgen/core/translation.php on line 14" while
reading response header from upstream, client: 10.0.0.136, server: ,
request: "GET /podcastgen/ HTTP/1.1", upstream:
"fastcgi://unix:/run/php-fpm/php-c955c07d-aa67-4013-bcda-4189fb9a1f34.sock:",
host: "10.0.0.50"
2021/12/06 19:11:44 [error] 13772#13772: *138328 open()
"/var/services/web/missing" failed (2: No such file or directory), client:
10.0.0.136, server: , request: "GET /missing HTTP/1.1", host: "10.0.0.50",
referrer: "http://10.0.0.50/podcastgen/"
2021/12/06 19:11:44 [error] 13773#13773: *138330 FastCGI sent in stderr:
"PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function
bindtextdomain() in /volume2/web/podcastgen/core/translation.php:14
Stack trace:
#0 /volume2/web/podcastgen/core/include.php(30): include()
#1 /volume2/web/podcastgen/index.php(11): require('/volume2/web/po...')
#2 {main}
  thrown in /volume2/web/podcastgen/core/translation.php on line 14" while
reading response header from upstream, client: 10.0.0.136, server: ,
request: "GET /podcastgen/ HTTP/1.1", upstream:
"fastcgi://unix:/run/php-fpm/php-c955c07d-aa67-4013-bcda-4189fb9a1f34.sock:",
host: "10.0.0.50"
2021/12/06 19:11:45 [error] 13774#13774: *138333 open()
"/var/services/web/missing" failed (2: No such file or directory), client:
10.0.0.136, server: , request: "GET /missing HTTP/1.1", host: "10.0.0.50",
referrer: "http://10.0.0.50/podcastgen/"
2021/12/06 19:11:45 [error] 13774#13774: *138335 FastCGI sent in stderr:
"PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function
bindtextdomain() in /volume2/web/podcastgen/core/translation.php:14
Stack trace:
#0 /volume2/web/podcastgen/core/include.php(30): include()
#1 /volume2/web/podcastgen/index.php(11): require('/volume2/web/po...')
#2 {main}
  thrown in /volume2/web/podcastgen/core/translation.php on line 14" while
reading response header from upstream, client: 10.0.0.136, server: ,
request: "GET /podcastgen/ HTTP/1.1", upstream:
"fastcgi://unix:/run/php-fpm/php-c955c07d-aa67-4013-bcda-4189fb9a1f34.sock:",
host: "10.0.0.50"
2021/12/06 19:11:45 [error] 13772#13772: *138338 open()
"/var/services/web/missing" failed (2: No such file or directory), client:
10.0.0.136, server: , request: "GET /missing HTTP/1.1", host: "10.0.0.50",
referrer: "http://10.0.0.50/podcastgen/"

Op ma 6 dec. 2021 om 14:31 schreef Chris Charabaruk <
***@***.***>:

**Comment by stefansegers** [comment]
Hi Chris, did I send the correct error.log file?
I hope you can make something out of this?

**Comment by coldacid** [comment]
You need to enable the PHP gettext extension. Your error is happening because the extension is unavailable, and therefore the functions it provides to Podcast Generator are missing. This is usually enabled by default on web hosting services (and I believe in the basic PHP installation) so you'll need to check your device documentation or the Synology community on how to enable it.

**Comment by stefansegers** [comment]
thanks a lot this works!!!

**Comment by stefansegers** [comment]
Only problem now is that when I want to upload a mp3 nothing is happening and after a few minutes I get a blank screen.
Maybe there is another extention that needs to be enabled?

**Comment by coldacid** [comment]
I would expect that this is caused by the maximum upload size allowed by nginx or PHP is smaller than the size of your mp3 file, but I can't be certain. Although, I'd expect that they'd both be configured to have no maximum upload size on a network storage device! Is there anything new in the error log that might suggest an issue?

**Comment by stefansegers** [comment]
Hi Chris, I changed upload_max_filesize to 532M but still the same.
[image: Schermafbeelding 2021-12-08 om 18.35.28.png]

Op wo 8 dec. 2021 om 14:34 schreef Chris Charabaruk <
***@***.***>:

**Comment by coldacid** [comment]
Could you grab the server error.log again?

Also, your screenshots aren't coming through via e-mail. For attachments to work you need to actually drag and drop them on the comment field on the Github issue web page itself.

**Comment by stefansegers** [comment]
Sorry, was not aware that images not weren being sent using email ;)

Here's the error.log with the part of upload

2021/12/09 09:15:12 [error] 15887#15887: *148223 FastCGI sent in stderr: "PHP message: PHP Warning:  POST Content-Length of 107597766 bytes exceeds the limit of 33554432 bytes in Unknown on line 0" while reading response header from upstream, client: 10.0.0.136, server: , request: "POST /podcastgen/admin/episodes_upload.php HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-c955c07d-aa67-4013-bcda-4189fb9a1f34.sock:", host: "10.0.0.50", referrer: "http://10.0.0.50/podcastgen/admin/episodes_upload.php"
2021/12/09 09:16:12 [error] 15884#15884: *148220 upstream prematurely closed connection while reading upstream, client: 10.0.0.136, server: _, request: "POST /podcastgen/admin/episodes_upload.php HTTP/1.1", upstream: "http://unix:/run/webstation_default.sock:/podcastgen/admin/episodes_upload.php", host: "10.0.0.50", referrer: "http://10.0.0.50/podcastgen/admin/episodes_upload.php
![Schermafbeelding 2021-12-08 om 18 35 28](https://user-images.githubusercontent.com/55828944/145359675-bcd7dc82-5d05-4390-94f9-186ff9c0f9d8.png)
"

**Comment by coldacid** [comment]
Ah. post_max_size needs to be equal to or greater than upload_max_filesize. A file sent via an HTTP POST request will be limited to the smaller of the two values. In addition, the second error message suggests that either your web browser or the web server -- most likely the latter -- is terminating the connection after a certain point. You should check to see what the maximum POST size is set to in nginx and ensure that it is again at least equal to the greater of PHP's post_max_size and upload_max_filesize.

**Comment by stefansegers** [comment]
I think I almost got it!! Upload button works but gives an error :(

Unsupported mime type detected for file with extension "mp3"

Op do 9 dec. 2021 om 13:56 schreef Chris Charabaruk <
***@***.***>:

**Comment by coldacid** [comment]
I didn't get a chance to look into this last night, but I'll do so after work today.

**Comment by stefansegers** [comment]
Hi Chris, Any luck yet?

**Comment by coldacid** [comment]
Haven't had a chance yet, sorry.

**Comment by stefansegers** [comment]
Hi Brian, any tips yet for me?

**Comment by stefansegers** [comment]
Hi Chris,

Thanks for your feedback. Sorry, but I did not think I was getting it
working anymore, so I found another solution called Redcirle.

Op wo 2 mrt. 2022 om 05:14 schreef Chris Charabaruk <
***@***.***>:
