### ISSUE TITLE
how to create seasons in apple podcast with podcast generator?

### ISSUE THREAD

**Issue by thadeu220** [PodcastGenerator/PodcastGenerator#451]
Hello. i have a podcast at Google podcast and also apple podcast.
but they have no seasons in the listing
how to add seasons using podcast generator admin?

Thanks for the help!
podcast generator version: 3.1.2
PHP: 7.4.13
Webserver: litespeed
Feed: https://podcasts.megadimensao.com.br/feed.xml

**Comment by coldacid** [comment]
Season support will be coming in version 3.2. In the meantime my personal integration branch has support for setting season numbers on episodes but there's no guarantee that things won't change considerably before then.

See #368
