### ISSUE TITLE
Add option to "no rename" file added

### ISSUE THREAD

**Issue by githubaobab** [PodcastGenerator/PodcastGenerator#457]
**Description**
I want a way to "no rename" files in media directory.
Maybe add an option in the admin interface ?
I have test to mod the "admin/episodes_ftp_feature.php", but I did not succeed.
'        // Select new filenames (with date) if not already exsits
        preg_match('/[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]/', $new_files[$i], $output_array);
        $fname = $new_files[$i];
        if (sizeof($output_array) == 0) {
            $new_filename = '../' . $config['upload_dir'] . date('Y-m-d') . '-' . $new_files[$i];
            $new_filename = str_replace(' ', '_', $new_filename);
            $appendix = 1;
            while (file_exists($new_filename)) {
                $new_filename = '../' . $config['upload_dir'] . date('Y-m-d') . '-' . $appendix . '-' . basename($new_files[$i]);
                $new_filename = str_replace(' ', '_', $new_filename);
                $appendix++;
            }
            rename('../' . $config['upload_dir'] . $new_files[$i], $new_filename);
            $fname = $new_filename;
        }
'

Thanks

**Motivation**
Keep a storage space lite with no rename files (if not, a copy of the original file is keep)

**Legal aspect**
No problem with legal aspect.

* [ ] I am the inventor of this idea or the idea is public domain
* [ ] I release this idea into the public domain

**Comment by coldacid** [comment]
I believe that the file name renaming is actually necessary for current Podcast Generator functionality. At the very least, it's needed to prevent file name collisions when multiple different episodes are uploaded with the same file name.
