### ISSUE TITLE
Lines get lost at build time

### ISSUE THREAD

**Issue by meneerhenk** [PodcastGenerator/PodcastGenerator#459]
Somehow in all v3.x builds all the contents of the file after this line is lost.

https://github.com/PodcastGenerator/PodcastGenerator/blob/ff70618bafa3b2a889175d7971f277683974feaa/PodcastGenerator/core/episodes.php#L143

This is probably due to the composer to components rename.

Did not find time yet to create a pull request. I'm sorry,

**Comment by coldacid** [comment]
Are you talking about the artifact releases out of the Actions tab? Looks like that's fixed now.
