### ISSUE TITLE
Getting translations reviewed / approved

### ISSUE THREAD

**Issue by alwa** [PodcastGenerator/PodcastGenerator#460]
I've contributed with Swedish translations (a long time ago) and everything for 3.1 is translated but it shows up as unreviewed and I don't know what the next step is.

Please advice.

**Comment by coldacid** [comment]
Honestly, I don't know how to deal with the Transifex stuff yet. I need @albertobeta and @emilengler to help me with that.

**Comment by coldacid** [comment]
I think I'm starting to figure this out!

It doesn't look like reviewing has been used in the past, so I'm not going to worry about it until someone complains that a translation is wrong. (And when they do that, I'm going to point them at Transifex where they can review and/or fix the bad translations.)

**Comment by albertobeta** [comment]
@coldacid Transifex is pretty straightforward. For years I've been delegating localization and reviews (if any) to volunteers and for PG I just downloaded the resulting JSON files and added it to the following release

**Comment by coldacid** [comment]
@albertobeta the hard part now is getting the new and updated native strings into Transifex. I'm seeing things about using xgettext and all that, but for existing translations I think I have it figured out.

**Comment by coldacid** [comment]
@alwa we're now prepping for version 3.2, and there are a number of new and changed messages for translation. If you can update your Swedish translations over on [Transifex](https://www.transifex.com/podcast-generator/podcast-generator/32/) we should be able to include them with that release.

**Comment by alwa** [comment]
@coldacid Done now
