### ISSUE TITLE
How to change podcast media folder

### ISSUE THREAD

**Issue by messagedj** [PodcastGenerator/PodcastGenerator#463]
Running Joomla @ Podcastgenerator 3.1.3

I want my podcast media to be uploaded to the Joomla /images/podcast_audio folder

When I change the config file to:
$upload_dir = "../images/podcast_audio/"; 

I get an error "The file upload was not successfully" FTP feature is also not working. 

Who can help?

**Comment by coldacid** [comment]
Podcast Generator does not support `$upload_dir` or `$images_dir` being outside of the install directory (set in `$absoluteurl`). Even if PG can access the directory you specified, it would not be able to generate correct URLs for episodes or cover art with that configuration.
