### ISSUE TITLE
PNG format support for artwork choosing

### ISSUE THREAD

**Issue by x789x** [PodcastGenerator/PodcastGenerator#469]
Check ARTWORK change page  and try to select PNG format file, but looks JPEG support only ,
hope PNG format can support in ARTWORK change page ,thanks!

**Comment by coldacid** [comment]
Depends on #396 as better filename handling is required for the show cover art to allow non-JPEG images.

**Comment by coldacid** [comment]
With version 3.2 we will support a much wider array of image formats for episode and show cover art.
