### ISSUE TITLE
Edit Future published podcast 

### ISSUE THREAD

**Issue by messagedj** [PodcastGenerator/PodcastGenerator#485]
I have added a podcast that should publish tomorrow at 12:00. Now I want to change the podcast info, but I can not edit or find the podcast anywhere....

**Comment by coldacid** [comment]
This is in version 3.2, but that version is only in beta right now. If you're willing to risk it, you can upgrade to [the beta](https://github.com/PodcastGenerator/PodcastGenerator/releases/tag/v3.2.0-beta) but make sure to back everything up first just in case something goes wrong during the process. Unfortunately, the ability to access unpublished episodes is not available in 3.0 or 3.1.

**Comment by coldacid** [comment]
Podcast Generator 3.2 is now released, and you can access the full list of published and unpublished episodes from the admin pages.
