### ISSUE TITLE
translation page for project isn't available

### ISSUE THREAD

**Issue by NedNet29** [PodcastGenerator/PodcastGenerator#490]
Hi all, 

sorry for submitting this as a bug report, but I don't know how to do it in another way

Link to translation seems broken : https://www.transifex.com/albertobeta/podcast-generator/ returns 404 error.

I noticed this because I helped translating to french, and wanted to see if there were new strings with latest release.
By the way, release page mentions "We currently only have translations for the English, German and Spanish languages.", it would be nice to add french ;)

HTH & regards

**Comment by coldacid** [comment]
Sorry, on what page did you find the link? It's https://www.transifex.com/podcast-generator/podcast-generator/ now.

**Comment by coldacid** [comment]
Also, we have a full French (France) translation for 3.2 (along with Estonian, Hebrew, and Swedish) but now we don't have full translations for German or Spanish. I'm waiting for those languages to be complete (and hopefully Czech and Polish will get completed for 3.2 as well) before I drop a release candidate and then the finished 3.2 release.

https://www.transifex.com/podcast-generator/podcast-generator/32/

**Comment by NedNet29** [comment]
I first saw this link in 2 mails I received from notifications@transifex.com on March 6 and 7,  and it is also in "contribute" section of project's main page (https://github.com/PodcastGenerator/PodcastGenerator)

The link you just posted is fine, thanks

**Comment by coldacid** [comment]
Well, I should update the README file first so it has the correct Transifex link.

**Comment by coldacid** [comment]
... And done. Thanks!
