### ISSUE TITLE
"Potential CSRF attack" when trying to manage users

### ISSUE THREAD

**Issue by N4444VX** [PodcastGenerator/PodcastGenerator#491]
**System Information**
Podcast Generator Version: 3.2.0-beta
Webserver: docker - mitlabs/apache-php7.3
PHP Version: docker - mitlabs/apache-php7.3

**Expected behavior**
Expected a page to manage users

**Actual behavior**
Returns blank webpage with only the following: `Potential CSRF attack`  on both Brave and Firefox browsers.

**Docker logs**
```
172.18.0.2 - - [19/Mar/2022:01:47:35 +0000] "GET /admin/pg_users.php?username=user HTTP/1.1" 200 279 "https://podcast.domain.tld/admin/pg_users.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36"
```

**How to reproduce**
Try to click a user link ( https://podcast.domain.tld/admin/pg_users.php?username=user ) on page https://podcast.domain.tld/admin/pg_users.php

**Question**
Is this a PodcastGenerator problem or an Apache/PHP config problem??

**Comment by coldacid** [comment]
Fix is in [v3.2.0 beta 2](https://github.com/PodcastGenerator/PodcastGenerator/releases/tag/v3.2.0-beta.2)
