### ISSUE TITLE
Files with dashes ( - ) in the file name are incorrectly processed in v3.2b3

### ISSUE THREAD

**Issue by LLPP65** [PodcastGenerator/PodcastGenerator#508]
**System Information**
Podcast Generator Version:  3.2 b3
Webserver: Apache
PHP Version: 7.4

**Podcast Generator Config**

```
<?php

$podcastgen_version = '3.2'; // Version

$first_installation = 1648021944;

$installationKey = 'xxxxx';

$scriptlang = 'en_US';

$url = 'xxxxx/';

$absoluteurl = 'xxxxx'; // The location on the server

$theme_path = 'themes/default/';

$upload_dir = 'media/'; // 'media/' the default folder (Trailing slash required). Set chmod 755

$img_dir = 'images/'; // (Trailing slash required). Set chmod 755

$feed_dir = ''; // Where to create feed.xml (empty value = root directory). Set chmod 755

$max_recent = 'all'; // How many file to show in the home page

$recent_episode_in_feed = 'All'; // How many file to show in the XML feed (1,2,5 etc.. or 'All')

$episodeperpage = 10;

$enablestreaming = 'no'; // Enable mp3 streaming? ('yes' or 'no')

$freebox = 'yes'; // enable freely customizable box

$enablepgnewsinadmin = 'yes';

$strictfilenamepolicy = 'no'; // strictly rename files (just characters A to Z and numbers) 

$categoriesenabled = 'yes';

$cronAutoIndex = 1; //Auto Index New Episodes via Cron

$cronAutoRegenerateRSS = 1; //Auto regenerate RSS via Cron

$indexfile = 'index.php';    // Path of the index file

$podcastPassword = '';       // Password to protect the podcast generator webpages, this will NOT protect the audio or XML files. Leave blank to disable.

$customtagsenabled = 'no';   // Advanced functionality for custom RSS tag input

$timezone = '';              // Timezone used for displaying dates and times

#####################

# XML Feed stuff

$podcast_guid = ''; // Globally unique identifier for your podcast

$podcast_title = 'xxxxx';

$podcast_subtitle = 'xxxxx';

$podcast_description = 'xxxxx.';

$author_name = 'xxxxx';

$author_email = 'xxxxx';

$itunes_category[0] = 'Sports'; // iTunes categories (mainCategory:subcategory)

$itunes_category[1] = 'Leisure:Automotive';

$itunes_category[2] = 'Leisure:Hobbies';

$link = "?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

$feed_language = 'en';

$copyright = 'All rights reserved';   // Your copyright notice (e.g CC-BY)

$feed_encoding = "utf-8";

$explicit_podcast = 'no'; //does your podcast contain explicit language? ("yes" or "no")

$podcast_cover = 'xxxxx';

# The e-mail of the technical admin of the podcast

$webmaster = 'xxxxx';

$link = '?name='; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

$feed_language = 'en';

$feed_sort = 'timestamp'; // sort method used to order episodes in the feed (by timestamp or by season/episode number)

$feed_locked = ''; // podcast:locked status ('yes', 'no', '' for off)

$users_json = 'xxxxx';

#####################

# WebSub

$websub_server = '';

#####################

# Podcast Index

$pi_api_key = "";

$pi_api_secret = "";

$pi_podcast_id = 0; // is the podcast in Podcast Index? This is its show ID there.

#####################

# WebSub

$websub_server = "https://pubsubhubbub.appspot.com/";

// END OF CONFIG
```  

**Expected behavior**
MP3 files with underscores in the file name are processed correctly (comments in the id3 tags are extracted and used for podcast title, description and text).

**Actual behavior**
MP3 files with dashes ( - ) in the file name are no processed correctly (comments in the id3 tags are ignored and the title, description and text of the podcast episode are blank. Also, the bitrate and sampling rate are also incorrect).

**How to reproduce**
Use the "ftp import" function. Files with dashes ( - ) in the file name are incorrectly processed.

**Comment by coldacid** [comment]
How are you triggering the FTP import process? Cron job or via admin/episodes_ftp_feature.php? I tried a few different MP3s with dashes in their filenames and everything went properly.

Also did you install from PodcastGenerator-v3.2.0-beta.3.zip, the source code zip, or directly from Git? If it's either of the latter two, you probably don't have getid3 where 3.2 looks for it; you'll need to have Composer installed, go into the root directory of the site, and run `composer install --prefer-dist --no-dev`. This is not necessary with PodcastGenerator-v3.2.0-beta.3.zip as it already has all vendor packages in place.

**Comment by LLPP65** [comment]
I'm triggering the import process from the admin interface. I got the source in the zip file and id3 is working for most of the files. If I start with these files in the media directory:

MotoPod_2022_01_08.mp3
MotoPod_2022_01_19_0.mp3
MotoPod_2022_02_02.mp3
MotoPod_2022_02_09.mp3
MotoPod_2022-02-25.mp3
MotoPod_2022-03-02_0.mp3
MotoPod_2022_03_09.mp3

these are the files in the media directory after the FTP import process:

2022-03-24_MotoPod_2022_01_08.mp3
2022-03-24_MotoPod_2022_01_08.xml
2022-03-24_MotoPod_2022_01_19_0.mp3
2022-03-24_MotoPod_2022_01_19_0.xml
2022-03-24_MotoPod_2022_02_02.mp3
2022-03-24_MotoPod_2022_02_02.xml
2022-03-24_MotoPod_2022_02_09.mp3
2022-03-24_MotoPod_2022_02_09.xml
2022-03-24_MotoPod_2022_03_09.mp3
2022-03-24_MotoPod_2022_03_09.xml
MotoPod_2022-02-25.mp3
MotoPod_2022-02-25.xml
MotoPod_2022-03-02_0.mp3
MotoPod_2022-03-02_0.xml

The files that have not been renamed correspond to the episodes for which the id3 data has not been extracted and the episode displays without content.


![Screen Shot 2022-03-24 at 18 30 28](https://user-images.githubusercontent.com/26736026/159975843-e9480533-e756-4f8f-9740-c23874880b0c.png)

**Comment by coldacid** [comment]
Thanks, that gave me the information I needed to figure out the problem. There's an oversight when files don't need to be renamed, leading to the directory name missing when doing any file operations. I should have a fix shortly.

**Comment by coldacid** [comment]
@LLPP65 could you replace `core/episodes.php` in your installation with [this one](https://raw.githubusercontent.com/PodcastGenerator/PodcastGenerator/318db5dea683ed628a25245f256545f4aeabb706/PodcastGenerator/core/episodes.php) and try again with the XML sidecar files for the failed episodes deleted? If it works, I can merge it in for the release.

**Comment by LLPP65** [comment]
Thanks for the quick turn-around! That seems to have fixed it, the episodes are now displayed correctly. I noticed that the files that were previously indexed incorrectly don't get renamed. 

After processing:
2022-03-24_MotoPod_2022_01_08.mp3
2022-03-24_MotoPod_2022_01_08.xml
2022-03-24_MotoPod_2022_01_19_0.mp3
2022-03-24_MotoPod_2022_01_19_0.xml
2022-03-24_MotoPod_2022_02_02.mp3
2022-03-24_MotoPod_2022_02_02.xml
2022-03-24_MotoPod_2022_02_09.mp3
2022-03-24_MotoPod_2022_02_09.xml
2022-03-24_MotoPod_2022_03_09.mp3
2022-03-24_MotoPod_2022_03_09.xml
MotoPod_2022-02-25.mp3
MotoPod_2022-02-25.xml
MotoPod_2022-03-02_0.mp3
MotoPod_2022-03-02_0.xml

Is there any chance of an option to preserve the name of the mp3 files? It would make my migration of a podcast with almost 700 episodes a lot easier. Thanks!

**Comment by coldacid** [comment]
Podcast Generator relies on having the yyyy-mm-dd pattern somewhere in the filename for some ineffable reason I've yet to determine. I wouldn't rely on there being an option to preserve names until 4.0 at the earliest, when I expect that we'll use local SQLite databases instead of XML files and even filesystem metadata for episode management.

So long as your episode files already match yyyy-mm-dd somewhere in the filename (they have to be dashes, not underscores) then PG will keep the original name.
