### ISSUE TITLE
Episode page selector is verrrry wide

### ISSUE THREAD

**Issue by LLPP65** [PodcastGenerator/PodcastGenerator#510]
**Description**

The episode pager along the bottom of the page is very wide for podcasts with hundreds of episodes. Maybe it should be broken into chunks of 10?

**Motivation**

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

![Screen Shot 2022-03-25 at 09 04 41](https://user-images.githubusercontent.com/26736026/160082646-c13010df-c4c3-48cc-a2e5-94bd119eb8e5.png)

**Comment by coldacid** [comment]
I don't know about chunks of 10, but it should be possible to get the bar to break at browser width like the episode cards do. I'll tackle this for 3.3.
