### ISSUE TITLE
<itunes:summary> and <itunes:keywords> are missing wheter long description and key words are empty or filled.

### ISSUE THREAD

**Issue by mabakach** [PodcastGenerator/PodcastGenerator#514]
**System Information**
Podcast Generator Version:  3.1.4.1
Webserver:  Apache
PHP Version: 7.3.33

**Podcast Generator Config**

```
$podcastgen_version = "3.1.4"; // Version
$first_installation = 1648836063;
$installationKey = "********";
$scriptlang = "de_DE";
$url = "********";
$absoluteurl = "/home/httpd/vhosts/mabaka.ch/httpsdocs/PodcastGenerator/"; // The location on the server
$theme_path = "themes/default/";
$upload_dir = "media/"; // "media/" the default folder (Trailing slash required). Set chmod 755
$img_dir = "images/"; // (Trailing slash required). Set chmod 755
$feed_dir = ""; // Where to create feed.xml (empty value = root directory). Set chmod 755
$max_recent = "all"; // How many file to show in the home page
$recent_episode_in_feed = "All"; // How many file to show in the XML feed (1,2,5 etc.. or "All")
$episodeperpage = 10;
$enablestreaming = "yes"; // Enable mp3 streaming? ("yes" or "no")
$freebox = "yes"; // enable freely customizable box
$enablepgnewsinadmin = "yes";
$strictfilenamepolicy = "no"; // strictly rename files (just characters A to Z and numbers) 
$categoriesenabled = "yes";
$cronAutoIndex = 1; //Auto Index New Episodes via Cron
$cronAutoRegenerateRSS = 1; //Auto regenerate RSS via Cron
$indexfile = "index.php";    // Path of the index file
$podcastPassword = "";       // Password to protect the podcast generator webpages, this will NOT protect the audio or XML files. Leave blank to disable.

#####################
# XML Feed stuff
$podcast_title = "Config Title";
$podcast_subtitle = "Config Subtitle";
$podcast_description = "Config Beschreibung";
$author_name = "Config Author";
$author_email = "config@example.com";
$itunes_category[0] = "Arts"; // iTunes categories (mainCategory:subcategory)
$itunes_category[1] = "";
$itunes_category[2] = "";
$link = "?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)
$feed_language = "de";
$copyright = "Config Copyright";   // Your copyright notice (e.g CC-BY)
$feed_encoding = "utf-8";
$explicit_podcast = "no"; //does your podcast contain explicit language? ("yes" or "no")
$users_json = "********";
// END OF CONFIG

```  

**Expected behavior**
<itunes:summary> and <itunes:keywords> are  added to feed.xml if log description and key words filled in for a specific episode.

**Actual behavior**
<itunes:summary> and <itunes:keywords> are missing wheter long description and key words are empty or filled.

**How to reproduce**

1. Install a fresh copy of PodcastGenerator
2. Add a new episode with a long descrtion.
3. Manually generate the XML feed and download the feed to review it.

**Comment by coldacid** [comment]
@mabakach have you tried the 3.2 beta yet? Do you know if the same problem exists there?

**Comment by mabakach** [comment]
@coldacid : No I have not tested 3.2 beta yet. I will try it next week. I have submitted a pull request (https://github.com/PodcastGenerator/PodcastGenerator/pull/516) to fix this issue in version 3.1.4.1

**Comment by sseguin613** [comment]
I just installed the 3.2 RC Version and I can confirm that with neither the 3.1.4, 3.1.4.1 or the 3.2 RC, the Long Description does not show up in Apple Podcast. It is only displaying the Short description.

**Comment by sseguin613** [comment]
It seems to be displaying the Long Description in the Episode List view (where you see all the podcast episodes) of the podcast show on Apple Podcasts, but using the Short Description in the actual Episode Display (where you only see the one selected episode). So something seems to be flipped.

**Comment by coldacid** [comment]
@sseguin613 this is with regard to the values being filled in the RSS feed itself, not how the content appears in Apple Podcasts. However, this lets us know that this particular bug does not exist in 3.2.

I'm going to put out a 3.1.5 alongside the 3.2 final release this weekend, and include this fix in it.

**Comment by mabakach** [comment]
@coldacid : Thanks for merging the PR.
