### ISSUE TITLE
https://podcastgenerator.github.io/tools/secure_config.html not working in Firefox 98.0.1 on MacOS Monteray

### ISSUE THREAD

**Issue by mabakach** [PodcastGenerator/PodcastGenerator#515]
**Expected behavior**
config.php is censored

**Actual behavior**
Error: Promised response from onMessage listener went out of scope [chrome.js:124:30](moz-extension://4ae4cbf6-00f7-3643-962f-18da41e36ad3/lib/chrome.js)
Uncaught TypeError: Document.evaluate: At least 2 arguments required, but only 0 passed
    onclick https://podcastgenerator.github.io/tools/secure_config.html:1
[secure_config.html:1:1](https://podcastgenerator.github.io/tools/secure_config.html)

**How to reproduce**
Open https://podcastgenerator.github.io/tools/secure_config.html  in the latest version of Firefox and try to censor your config.php

**Comment by coldacid** [comment]
Thanks. Not really a PG problem but a website problem, but it should now be fixed (or at least in a few minutes when the website changes get deployed).
