### ISSUE TITLE
Adding a category with a colon in the name wipes out all categories

### ISSUE THREAD

**Issue by coldacid** [PodcastGenerator/PodcastGenerator#519]
I was adding the below categories and as soon as I added the one in bold, it went to an error page, and I went back to categories page and they're ALL gone. When I try to add any, back to error page............Login is *****/*****

Ejemplos Buenos y malos
Estudio Carta de Santiago
Estudio Libro de Esdras
Estudio Libro de Hageo
Estudio Breve de Zacarías
**Filemón: El Perdón Bíblico**

_Originally posted by @5280designco in https://github.com/PodcastGenerator/PodcastGenerator/issues/518#issuecomment-1087072932_

**Comment by coldacid** [comment]
@5280designco: I tried to reproduce this with 3.2-RC and I neither got an error page nor did the categories disappear. I also compared the current code of the categories management page to the version of the same page in 3.1 and none of the differences points to a reason for this to work in 3.2 but not 3.1. Could you try re-adding the categories? If you get an error page again, take a screenshot of it and attach it to this issue.

**Comment by 5280designco** [comment]
Yes, of course trying to re-add the categories were the very first thing I did. I gave you login assuming you'd try yourself.  I just did it again, recorded here - https://www.awesomescreenshot.com/video/8237479?key=8d47e37390a3444e97eebb13228af5af

**Comment by 5280designco** [comment]
This is extremely annoying. It's pretty basic software. It should work without ":" messing it up. I even just reuploaded all the files again, and I still get the same issue. Did I upload 16gb of media for nothing?

**Comment by 5280designco** [comment]
Wowwwww....I realized the post dates are all 4/2 after the update, or it was like that after importing because it didn't read the ID3 data correctly..............................................................................

**Comment by 5280designco** [comment]
So I restored backup and screenrecorded doing the same thing - adding categories. The first test while not screenrecording, categories disappeared after the 5th entry. The second test while recording, they disappeared after the 6th entry (with the colon - so that was unrelated since it happened on the 5th entry too). Also, I did not update to 3.2 this time, so it's unrelated to that version too. - https://www.awesomescreenshot.com/video/8239190?key=c013e4ebd7eb6ad47622db27a32214d3

**Comment by coldacid** [comment]
If it seems like "basic software" that's because there's actually quite a bit kicking underneath that you don't see.

Now, there's nothing in category management that would delete episodes -- at worst, the categories.xml file might be trashed if two people try editing categories at the exact same time. In fact, the only code that would be included with a request to the category management page isn't called anywhere except from the episode editor page, and then only if the delete button has been pressed for an episode. If *episodes* have gone missing with the categories then I have to suspect that there's something beyond Podcast Generator causing this.

Even when a category is deleted, by the way, episodes that have that category aren't touched at all, at least not in 3.1 or 3.2. The deleted category isn't even removed from the episodes.

The one thing that might be possible is that if the setup/ directory is not deleted after setup is complete, then it could be used to reset everything. This still shouldn't delete any uploaded episodes, but it could destroy any configuration settings, theme buttons, categories, and freebox content. It *shouldn't* as the setup procedure checks for existing freebox, categories, and theme button settings files so as to not overwrite them, but that's the only other thing I can think of where Podcast Generator, or even PHP itself, could be responsible.

What operating system (including distro if Linux or BSD) is on the computer used to host the site, and what version of PHP is installed? What is the web server and what version is it at, as well? Those might provide some clues, hopefully, as to what's going on.

**Comment by 5280designco** [comment]
No one ever said episodes went
missing............................categories went missing............

Debian 11.3 / PHP 7.4.28

Thanks,

[image: 5280 Design Co.] <https://5280.design/>

*Brian Smith*
5280 Design Co.
*direct:*  720.770.5280
*mobile:*  720.230.1234
*main:*  720.552.5280 x101
*website:*  5280.design
*email:*  ***@***.***
*address:*  2806 N Speer Blvd, Denver CO 80211
[image: 5280 Design Co.] <https://facebook.com/5280designco>
[image: 5280 Design Co.] <https://instagram.com/5280designco>
[image: 5280 Design Co.] <https://twitter.com/5280DesignCo>
[image: 5280 Design Co.] <https://www.linkedin.com/in/briansmith84>
<https://mysignature.io/editor/?utm_source=expiredpixel>

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
04/05/22,
05:54:40 PM

**Comment by coldacid** [comment]
Sorry but based on "It should work without ":" messing it up. I even just reuploaded all the files again, and I still get the same issue. Did I upload 16gb of media for nothing?" in one of your other comments, it certainly sounded like that was being suggested.

**Comment by daveajones** [comment]
> No one ever said episodes went missing............................categories went missing............

What’s up with the attitude?  Do you find that demeaning people who are donating their time to help you (for free) is an effective way to get what you want?

**Comment by 5280designco** [comment]
I was putting emphasis on it, because I guess I haven't been clear previously. Nothing works. Fresh install on fresh server and click begin installation (https://ibtsermons.org/PodcastGenerator/)  and straight to the same error page. I have been using massive PHP apps (VoIP, CRM, SMM apps, just about everything from CodeCanyon and elsewhere and they just work - extremely complicated apps). I have no idea why I can't get this app to do basic functions. I guess the fact that the pagination isn't even responsive (in a blog-esque type software that heavily uses pagination due to frequent posts), was a big enough red flag.
