### ISSUE TITLE
Issue with Language Selection of Podcast

### ISSUE THREAD

**Issue by sseguin613** [PodcastGenerator/PodcastGenerator#520]
**System Information**
Podcast Generator Version: 3.1.4.1
Webserver:  Apache/2.4.25 (Debian) 
PHP Version: 7.4.28 

**Podcast Generator Config**

```
<?php

$podcastgen_version = "3.1.4"; // Version

$first_installation = 1648929264;

$installationKey = "0gHPlDN3";

$scriptlang = "es_ES";

$url = "https://www.domain.com/podcast/";

$absoluteurl = "/mnt/public_html/podcast/"; // The location on the server

$theme_path = "themes/default/";

$upload_dir = "media/"; // "media/" the default folder (Trailing slash required). Set chmod 755

$img_dir = "images/"; // (Trailing slash required). Set chmod 755

$feed_dir = ""; // Where to create feed.xml (empty value = root directory). Set chmod 755

$max_recent = "all"; // How many file to show in the home page

$recent_episode_in_feed = "All"; // How many file to show in the XML feed (1,2,5 etc.. or "All")

$episodeperpage = 10;

$enablestreaming = "yes"; // Enable mp3 streaming? ("yes" or "no")

$freebox = "no"; // enable freely customizable box

$enablepgnewsinadmin = "yes";

$strictfilenamepolicy = "no"; // strictly rename files (just characters A to Z and numbers) 

$categoriesenabled = "yes";

$cronAutoIndex = 1; //Auto Index New Episodes via Cron

$cronAutoRegenerateRSS = 1; //Auto regenerate RSS via Cron

$indexfile = "index.php";    // Path of the index file

$podcastPassword = "";       // Password to protect the podcast generator webpages, this will NOT protect the audio or XML files. Leave blank to disable.

#####################

# XML Feed stuff

$podcast_title = "censored";

$podcast_subtitle = "censored";

$podcast_description = "censored ";

$author_name = "censored";

$author_email = "censored";

$itunes_category[0] = "Kids & Family:Education for Kids"; // iTunes categories (mainCategory:subcategory)

$itunes_category[1] = "Kids & Family:Parenting";

$itunes_category[2] = "";

$link = "?name="; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

$feed_language = "es";

$copyright = "copyright";   // Your copyright notice (e.g CC-BY)

$feed_encoding = "utf-8";

$explicit_podcast = "no"; //does your podcast contain explicit language? ("yes" or "no")

$users_json = censored;

// END OF CONFIG


```  

<html><body>

 After successfully adding my podcast to the Apple Podcast Connect, a few hours later I got the following message from Apple:
--
Hello
 
We found an issue with your show, As such, it's not available on Apple Podcasts.
 
Your show category does not correspond to the content of your show. To fix the issue, update the language in Apple Podcasts Connect or within your RSS feed.
 
After you correct the issue in Apple Podcasts Connect, resubmit your show for review. If you need any assistance, contact us.

So
I check my feed and it shows as Spanish (which is what I want). However if I go into the Podcast Details page in Podcast Generator it shows English. If I change it to Spanish or any other language and click Save, it reverts to English.

The Feed.xml file seems to be set to Spanish though. I'm not sure what the problem is. In any case, the podcast language selector in Podcast Details doesn't seem to work. Any change I make goes back to English after I click Save. But for the error email I got above, what can I do to resolve it?

</body>
</html>

**Comment by coldacid** [comment]
This is fixed already for 3.2, and is likely to be backported for a final 3.1 series release if I can make the patch apply cleanly.

It does look like the iTunes categories updates were never backported to 3.1 so I'll have to tackle that as well. However, the only differences are with the Science subcategories, and that there's no "Running" subcategory for Sports despite the list in PG 3.1. If you aren't using any of those subcategories, there shouldn't be an issue with that. Also, it seems that Apple has dropped the number of allowed categories from three to two. If you have three categories selected, that could be the problem.

The only other thing I can think of is that Apple now has localized versions of the categories, which I've seen no sign of, but would not be surprised if they only show the particular categories for the locale they expect the user is from. (I absolutely would not put that past them.) If you go to <https://podcasters.apple.com/support/1691-apple-podcasts-categories> and the categories list is not in English for you, then that might be the issue and it'll have to be something that would need more time and effort to tackle.

**Comment by sseguin613** [comment]
Thanks for the info.

If the podcast is in another language, do the categories need to be written in that language for it to be accepted by Apple? Or is it ok to just pick the English category equivalent? The error message is a bit vague on the specifics, so I'm assuming either the category is not in the same language as the podcast or the podcast is not set with the right language to the audio. I don't know.

**Comment by coldacid** [comment]
I don't know either, but that's what I'd like to find out. If only Apple didn't make everything so opaque and confusing. (I have to deal with some of their nonsense with my day job too, at this point I have a very low opinion of that company.)

**Comment by coldacid** [comment]
Looks like backporting the language selection was okay.
