### ISSUE TITLE
3.2RC Custom Feed data - Change Episode Website url.

### ISSUE THREAD

**Issue by sseguin613** [PodcastGenerator/PodcastGenerator#521]
**System Information**
Podcast Generator Version: 3.2 RC

**Description of your problem:**
With the new 3.2 RC version, there is an option to enable customization of the feed data. With that, can I override the Episode Website URL? For example, to be able to set the Episode Website link in Apple Podcast to go to the proper page on our actual website (rather than the podcast generator website). And what would be the correct parameter to use to do that as an example? Thanks.

I am referring to the Episode Website page, not the Show or Channel webpage.

**Comment by coldacid** [comment]
No, this is only for adding additional tags to the feed, not for overwriting tags that are already generated. For example, I've been using this to provide person, value, and liveItem tags for my own podcast. You would still need to modify `core/feed_generator.php` yourself if you want to customize any of the tags put in the RSS feed by default.

**Comment by coldacid** [comment]
See #488
