### ISSUE TITLE
Setting date on FTP Upload

### ISSUE THREAD

**Issue by MostMoistMike** [PodcastGenerator/PodcastGenerator#566]
I have about 900 episodes to upload via FTP. They all have their date created attribute set correctly, they all have the date in the filename, and the ID3 name, but when I upload them they all just have the current date.

I don't suppose there's any way to upload them via FTP and keep the date?

**Comment by coldacid** [comment]
Podcast Generator checks for the modification, not the creation date of the file, and doesn't actually use the filename or ID3 tags to determine the release date and time of an episode when handling FTP uploaded episodes. If you can set the mod date for your episodes instead, then this should work.

**Comment by MostMoistMike** [comment]
@coldacid Wow, thank you so much, it works! This is a much more elegant solution than what I was facing (just uploading them all with the same date and the date as the title) - Thanks again for the quick response and solution, and for writing what I'm quickly finding to be an awesome little tool!
