### ISSUE TITLE
Automatically Invoke FTP Indexing

### ISSUE THREAD

**Issue by MostMoistMike** [PodcastGenerator/PodcastGenerator#567]
Is it possible to somehow automatically or remotely invoke the FTP indexing? Maybe a PHP file I can run on a schedule or call from a cron?

I'm thinking of a system where I could just drop files into the FTP folder and with a few minutes or a half hour, they're auto-indexed.

**Comment by coldacid** [comment]
Indeed there is! On the Podcast Generator Configuration page, there's a text box containing a URL you can call on a cron job to automatically trigger FTP indexing. Just set up a cron job to curl that URL on the regular, and PG will automatically pick up new episodes that you've FTP'd in.
