### ISSUE TITLE
Podcast Generator 3.2 Zip Extract Errors

### ISSUE THREAD

**Issue by sseguin613** [PodcastGenerator/PodcastGenerator#569]
**System Information**
Podcast Generator Version:  3.2

I get errors on extracting the ZIP file for the new 3.2 version. No matter the computer and ZIP utility I use.

Always on the same file: Data error : PodcastGenerator\vendor\james-heinrich\getid3\helperapps\cygwin1.dll

**Comment by coldacid** [comment]
Looks like GitHub screwed something up when repacking the zip file (it tends to recompress everything from the zip that I actually upload for the release). I'm going to try reuploading and hopefully it won't screw it up this time. I checked the original uploaded zip and there were no data issues, but I definitely saw the problem when testing what's linked on the release page.

**Comment by coldacid** [comment]
Just tested the replaced download and it extracts properly. You should be good to go again for downloading.
