### ISSUE TITLE
Issues in 3.2 - Uploading New MP3 files

### ISSUE THREAD

**Issue by sseguin613** [PodcastGenerator/PodcastGenerator#570]
**System Information**
Podcast Generator Version: 3.2
Webserver: Apache/2.4.25 (Debian) 
PHP Version:  7.4.28 

I am trying to upload new audio recordings since updating to 3.2 RC (as currently the 3.2 download ZIP has some issue). 

For any file I upload, I get a generic error
my audio.mp3 was not uploaded successfully

There doesn't seem to be anything in my server error logs related to the problem so I am unsure what is going on. Never had a problem on 3.1.4.1.

**Comment by coldacid** [comment]
What are the permissions on the media/ directory for your PG site? The "%s was not uploaded successfully" message means that an uploaded file can't be moved from the temporary location where PHP put it to the proper file location, which should be the media/ directory inside your Podcast Generator installation. If the PHP process (usually but not always running under the same account as the web server) cannot write to the media/ directory then this error will appear.

**Comment by sseguin613** [comment]
Hello. The directory is set as 775. Same as the other PG directories. I also tried setting it as 777 and no difference.

I have three sites running PG 3.2RC and they all are experiencing this issue.

**Comment by sseguin613** [comment]
Just updated to 3.2 (from the 3.2 RC) and same issue. PErmissions for the Media folder are 775. I even tried 777 and no change.

I should mention that I have this installed on a Wordpress site, but I also have other PG installs on Joomla sites. Never an issue before but since 3.2 unable to upload files to PG. Wordpress and Joomla have no problems with file uploads, which leads me to believe something wrong with PG 3.2 as it was not an issue on PG 3.1.4.1

**Comment by coldacid** [comment]
Do your install paths contain upper case letters? I think I found a bug in the function that handles construction of the file name used for episodes after upload that would only appear on case-sensitive file systems where PG is installed in a path containing upper case letters.

**Comment by sseguin613** [comment]
All lower case.

**Comment by coldacid** [comment]
Could you replace lines 118 and 119 in admin/episodes_upload.php with the following two lines and then try uploading an episode?

```php
    $uploadDir = '../' . $config['upload_dir'];
    $imagesDir = '../' . $config['img_dir'];
```

The existing lines using `$config['absoluteurl']` *should* work (and do, for my podcast and for my local dev/test site) but it might not work for all PG installations. You should also check your config.php and ensure that `$absoluteurl` in there is properly set to the directory containing your PG install -- not just that the path is correct but that it ends in a forward slash. (`$theme_path`, `$upload_dir`, and `$img_dir` should also all end in a forward slash.)

**Comment by sseguin613** [comment]
Hi I replaced lines 118-119 and did no other changes and the uploads are now going through successfully.

**Comment by coldacid** [comment]
Alright, then I'm going to make those changes and release 3.2.1 with that and the other fix I found.

**Comment by sseguin613** [comment]
On a sidenote, what should the permissions be on all the folders? 775 or 755? (The config.php seems to suggest 755 however my install is 775)

**Comment by coldacid** [comment]
It really depends on the user and group configuration for the web server and/or PHP process. If the owner of the directory is the web server/PHP process user, then 755 is fine. Otherwise, the directory group should be the primary group of the web server/PHP process and the directory permission bits should be 775.
