### ISSUE TITLE
Cover update not recognized by Spotify

### ISSUE THREAD

**Issue by Archiware** [PodcastGenerator/PodcastGenerator#574]
**System Information**
Podcast Generator Version: 3.2.0
Webserver: Caddy
PHP Version: 7.4.3

**Expected behavior**
When I'm uploading a new cover art for my podcast, I expect Spotify to recognize and update it on their platform.

**Actual behavior**
After successfully uploading the new image, the cover stays the same on Spotify.

**How to reproduce**
Upload a new cover for your podcast and have it linked to Spotify.

**Most probable reason**
Spotify states the following on their support page:
> New artwork or audio not showing on Spotify?
> Our system might not have recognized the new audio or image file.
> 
> We recommend saving the new file under a slightly different URL so our system recognizes the change and triggers the update. Your host can help change your file names.
Therefore, the PodcastGenerator should rather upload new cover arts with a new filename and therefore new URL instead of just overwriting the old one.

While I do agree that Spotify should be capable of recognizing the new image even without that (it's really no big deal and they apparently no of that issue), the change shouldn't be that complex and the effect would probably help a lot of users out.

**Comment by coldacid** [comment]
Podcast Generator 3.2 already generates a new cover URL whenever you change the cover image so long as the new image file has a different filename from the existing cover image file. For episode covers, the original filename doesn't even matter. I'll try to get auto-renaming for cover images in for 3.3 but in the meantime so long as the file you upload for podcast cover art is unique Spotify should pick it up.

**Comment by coldacid** [comment]
Show cover image renaming change is in 3.2.2+ and master.
