### ISSUE TITLE
Fatal error while installing Podcast Generator 3.2.2

### ISSUE THREAD

**Issue by prbt2016** [PodcastGenerator/PodcastGenerator#577]
Hello,

I was in the process of manual installation of Podcast Generator v3.2.2 on Centos 7 with Apache 2.2, MYSQL 5.5, PHP 7.0.

However I encountered an error while doing so. When setup hits step3.php i.e the following URL :

http://{{DOMAIN.COM}}/podcast/setup/step3.php

The step throws fatal error i.e :

Warning: require_once(vendor/james-heinrich/getid3/getid3/getid3.php): failed to open stream: No such file or directory in 
/{{PATH}}/{{TO}}/{{PODCAST-DIR}}/core/episodes.php on line 209

Fatal error: require_once(): Failed opening required 'vendor/james-heinrich/getid3/getid3/getid3.php'  in 
/{{PATH}}/{{TO}}/{{PODCAST-DIR}}/core/episodes.php on line 209

Following is the screenshot for the same : 
![test](https://user-images.githubusercontent.com/17871448/162942555-27a3634c-abb9-4d92-ae9f-bec816be4bd7.png)

System Information
Podcast Generator Version: 3.2.2
Webserver: Apache/2.2.34
PHP Version: 7.0.33

Expected behavior
Step 3 should pass correctly

Actual behavior
Fatal error

How to reproduce
1)After step1(lang selection) and step2 i.e (permission check page) click 'Submit' the above error is thrown.

@coldacid Could you please check into this issue?

**Comment by coldacid** [comment]
@prbt2016 well, the file is present. What is the value of `$absoluteurl` in your config.php?

**Comment by coldacid** [comment]
I've stepped through setup in both Linux and Windows environments and in neither case were there any errors. Based on the code, the only things I can think of are either that the absoluteurl config setting was not properly set, or that PHP 7.0 reacts differently to require_once than 7.1+.

Given that PHP 7.0 is [long out of support](https://www.php.net/supported-versions.php) (and in fact even 7.4 is only supported for security fixes at this point) I'd suggest upgrading to PHP 8 if you can. That is the preferred version of PHP for running Podcast Generator 3.2.

**Comment by prbt2016** [comment]
Hello @coldacid ,

The config.php isn't created till step3 in website root. I checked on both Su-PHP , Non-SuPHP(with permission on root folder) servers, windows.

Same error I face .

Have used this package for installation . 

https://github.com/PodcastGenerator/PodcastGenerator/releases/download/v3.2.2/PodcastGenerator-v3.2.2.zip

**Comment by coldacid** [comment]
Okay, can you try this in a shell, then?

```sh
$ cd /{{PATH}}/{{TO}}/{{PODCAST-DIR}}/setup

$ php -a
Interactive mode enabled

php > echo file_exists(realpath("../") . "/" . 'vendor/james-heinrich/getid3/getid3/getid3.php') ? "true" : "false");
```

If the result is true, then it's very likely to be something PHP 7.0 related that doesn't happen in newer versions of PHP. If it's false, then something went wrong when unzipping Podcast Generator as the file definitely exists where it should in the zip file.

**Comment by prbt2016** [comment]
Hello @coldacid ,

The output of the above command i.e : 

echo file_exists(realpath("../") . "/" . 'vendor/james-heinrich/getid3/getid3/getid3.php') ? "true" : "false";

is true.

![test1](https://user-images.githubusercontent.com/17871448/162971041-755f20d1-24f0-4060-8fc0-983c1adfeebc.jpg)

**Comment by prbt2016** [comment]
Hello @coldacid ,

As I have mentioned above . I have tried on 8.0 and 8.1 as well. But there too I am getting the same issue.

**Comment by coldacid** [comment]
I didn't see that you edited your previous comment above. Still, that it works in all the environments I've tested in makes this pretty confusing. For now, if you comment out lines 15-18 and 46-48 in step3.php you should be able to complete setup, although you'll need to manually trigger feed generation afterwards.

I'd like to update podcastgenerator.net but that site isn't actually in my hands. @albertobeta could you DM me on PI Social about that?

**Comment by coldacid** [comment]
Those first eight lines, I thought I had picked that in for the 3.2.2 fix. Just checked and I didn't, oops.

**Comment by coldacid** [comment]
[v3.2.3](https://github.com/PodcastGenerator/PodcastGenerator/releases/tag/v3.2.3) pulls in your earlier fix to the supported languages XML file and rolls back the initial feed generation changes that have been causing you this problem.

**Comment by albertobeta** [comment]
> I'd like to update podcastgenerator.net but that site isn't actually in my hands. @albertobeta could you DM me on PI Social about that?

@coldacid the current website on podcastgenerator.net is a simple PHP CMS I wrote years ago. I'd replace it. I could easily install a WP instance that is simple to manage for everyone, but I understand that you prefer a static website? I have a simple LAMP host there with no SSH.
Let's follow up via email so we plan a proper setup and we make sure the website gets updated.
