### ISSUE TITLE
More issues...........

### ISSUE THREAD

**Issue by 5280designco** [PodcastGenerator/PodcastGenerator#585]
Finally got it installed on a fresh server using 3.2.3 (which I had to update from a couple different versions until it finally worked).

Then....after importing all, small issue, but full grid layout breaks on last row where 2 are missing (https://ibtsermons.org/)

Then....I manually create RSS to ensure that all content is in there, and what do you know? It breaks. RSS feed no longer works, it shows the following. Now I have to reupload (again) 16gb of data. Maybe I first try overwriting source files again. I can't wait to finally get far enough along to import this into Podbean. It's been quite the experience.

![image](https://user-images.githubusercontent.com/73325867/163859968-32480fe4-7293-48db-85c5-dabb5f9fa23e.png)

**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
```  

**Expected behavior**

**Actual behavior**
 

**How to reproduce**

**Comment by 5280designco** [comment]
Didn't have to do with manually creating RSS. Did it period once I reuploaded all....again. I was autoindexing occasionally throughout upload to see when it breaks and made it halfway. Now I will have to do it once again, take a backup every 100 uploaded, to find the breaking point. Absolutely UNREAL.

**Comment by 5280designco** [comment]
SUCCESS! Geez. (Some are now showing full filenames in all data fields???....but oh well, I'll manually fix these. Mindboggling as they come., but what can you expect!!) Glad I narrowed it down to the file that caused the last issue, now dealing with more issues until I finally come out of this. I'm glad I could make aware the many issues prior to your last near-back-to-back updates. I haven't even tried the category issue however, don't want to break the code again, I'll just update categories after I transfer.

![image](https://user-images.githubusercontent.com/73325867/163900475-b9b93bdc-65d9-419c-8115-c1fc858ac8d5.png)

**Comment by coldacid** [comment]
If this is the attitude you're going to take, then please use something else.
