### ISSUE TITLE
Uploaded new cover art, but when linking to my site, old cover art is showing in link thumbnail.

### ISSUE THREAD

**Issue by MrDwight** [PodcastGenerator/PodcastGenerator#592]
**System Information**
Podcast Generator Version: 
Webserver: 
PHP Version:

**Podcast Generator Config**

```
INSERT THE **CENSORED** CONFIG HERE
``` 

Using the latest and greatest version of PG.  So, I uploaded a new cover art image, and it shows as the default on any new material on my site.  However, when sharing links with friends in Facebook, the default PG cover art image is shown in the link preview/thumbnail.  Any ideas why or what I can change to fix that?

**Comment by coldacid** [comment]
I bet that the theme wasn't properly updated to set the cover art image in the OG tags. I'll take a look at this tonight.

**Comment by MrDwight** [comment]
Did you find anything out?

**Comment by MrDwight** [comment]
FYI: So, I replaced the default itunes_image.png file in the images directory with my new cover art image, and went back and checked, and now the correct image is showing in the preview thumbnail.

**Comment by coldacid** [comment]
Sorry, for the last few weeks I've had other more pressing matters to attend to. I should have a proper fix in by the end of the weekend.

**Comment by MrDwight** [comment]
No worries.  I appreciate your help, and  getting back to me.
