### ISSUE TITLE
Podcast Generator 3.2.5 throws Fatal error

### ISSUE THREAD

**Issue by prbt2016** [PodcastGenerator/PodcastGenerator#665]
Hello,

I was in the process of manual installation of Podcast Generator v3.2.5 on Centos 7 with Apache 2.2, MYSQL 5.5, PHP 7.0.

However I encountered an error while doing so. When setup hits step3.php i.e the following URL :

http://{{DOMAIN.COM}}/podcast/setup/step3.php?create=1

The step throws fatal error with a notice and warning i.e :

```
Notice: Undefined variable: config in /{{PATH}}/{{TO}}/{{PODCAST-DIR}}/core/episodes.php on line 209 

Warning: require_once(vendor/james-heinrich/getid3/getid3/getid3.php): failed to open stream: No such file or directory in /{{PATH}}/{{TO}}/{{PODCAST-DIR}}/core/episodes.php on line 209 

Fatal error: require_once(): Failed opening required 'vendor/james-heinrich/getid3/getid3/getid3.php' (include_path='.:/usr/local/apps/php70/lib/php') in /{{PATH}}/{{TO}}/{{PODCAST-DIR}}/core/episodes.php on line 209 
```

Following is the  screenshot for the same :
![test](https://user-images.githubusercontent.com/17871448/170267654-4e67bafe-d007-4d9b-a799-df44f7871ff6.png)

System Information
Podcast Generator Version: 3.2.5
Webserver: Apache/2.2.34
PHP Version: 7.0.33

Expected behavior
Step 3 should pass correctly

Actual behavior
Fatal error

How to reproduce
1)After step1(lang selection) and step2 i.e (permission check page) , After entering admin details on step 3 and click 'Submit' the above error is thrown.

Faced a similar kind of  issue #577 in 3.2.2 which I had reported earlier. But it was on a different step i.e after permission check page.

@coldacid Could you please check into this issue and try replicating this?

Getting this same issue on multiple testing environments i.e Linux / Windows both.

**Comment by coldacid** [comment]
@prbt2016 the good news is that if this is where it crashed, then setup is actually complete and successful. However, the fact that it crashed is still a bug, and I have a fix en route. I unfortunately won't be able to make a release until either my lunch break or after work, so it may be anywhere from five to 12 hours before 3.2.6 is available.

**Comment by coldacid** [comment]
Looks like I was able to get it done on the train, 3.2.6 is now released.

**Comment by prbt2016** [comment]
Hello @coldacid ,

Thanks a lot for looking into the issue . Shall check with 3.2.6. 

Regards.

**Comment by prbt2016** [comment]
Hello @coldacid ,

Thanks for the fixing the issue. 3.2.6 works absolutely fine.

Regards.
