### ISSUE TITLE
I want a feed per catagory

### ISSUE THREAD

**Issue by JohnnyQuazar** [PodcastGenerator/PodcastGenerator#678]
Just diving in, it is not apparent what this would require... I want 3 feeds from my site:

Original - all the content
Interest1 - half of the content
Interest2 - other half of the content

I will have 3 audiences. True fans will want to hear everything, while some will be interested in one thing, or the other, but not both.

Doable? thanks!

**Comment by coldacid** [comment]
This is already available with v3.2. Using categories, you can use feed.php?cat={category} to get an RSS feed of only those episodes within the named category.
