### ISSUE TITLE
Add "preload=metadata" to audio/video tags

### ISSUE THREAD

**Issue by LLPP65** [PodcastGenerator/PodcastGenerator#682]
**Description**

Add preload=metadata to the audio/video tag, at least on the listepisodes.php page and possibly on the singleepisode.php page.

**Motivation**

Without a preload=none or preload=metadata in the audio/video tags, every episode on the page is downloaded. This is probably not what the end-user wants and it artificially inflates download stats.

**Legal aspect**

* [x] I am the inventor of this idea or the idea is public domain
* [x] I release this idea into the public domain

**Comment by coldacid** [comment]
I think that `preload=none` might be the better option since `preload=metadata` would still lead to a request for the episode media that could fudge stats.

**Comment by LLPP65** [comment]
Preload=meta results in http range (partial) requests, and the response is a 206 code. My stats package (Matomo) counts them as a file access but not as a download. I'm not sure what the standard treatment is in other packages. 

Thanks,
Len
