### ISSUE TITLE
Podcast Image appears to be stored next to the audio files

### ISSUE THREAD

**Issue by computertalkradio** [PodcastGenerator/PodcastGenerator#686]
When I attach an image to an individual episode (not really desired), or I set an image to represent the entire podcast, it seems that the next time that I use the FTP Feature (Auto Indexing), that it recognizes that image as a podcast, and tries to load it in amonst the podcast itself.  

Extending off of the initial statement (attaching to an individual episode), I'd like to be able to delete the associated link, and revert to the default image from the podcast.

**Comment by coldacid** [comment]
When using the FTP feature, cover art needs to be embedded in the episode media file itself. The only files that should ever be in the media/ directory should be the episode media and data files. If you name your media files to start with the YYYY-mm-dd pattern, then you should be able to upload cover images to your images/ directory with the same name (apart from extension; needs to be JPG or PNG) as the episode media file and PG will pick it up as long as there's no cover art embedded in the media file.

To set the series cover art, you need to use the appropriate admin page; PG does not support setting series cover art by FTP.

**Comment by computertalkradio** [comment]
If I go to Admin / Podcast Platform Settings / Change Cover Art, and then choose a PNG or JPG file, it sets it for many of the uploaded podcasts.  It also uploads that file into the media director, not the images folder.  That means that the next time that I use the Episodes / FTP Feature (Auto-indexing) / Begin...  it finds that previous cover art in the same folder, and imports it as if it is a podcast.

With this, I previously set the image on a few episodes manually, as I was working to fix this, and now I don't know how to back out the chosen image, and go with the default image.
