### ISSUE TITLE
Add Itunes Episode Type for next update

### ISSUE THREAD

**Issue by mat54840** [PodcastGenerator/PodcastGenerator#694]
Hello there, 

Would it be possible to add <itunes:episodeType> on the next update? 
It helps a lot for showing to apple when you want to add a Bonus or a Trailer episode for your show. 

Thanks :-) 
Mat.

**Comment by coldacid** [comment]
See https://github.com/PodcastGenerator/PodcastGenerator/issues/185#issuecomment-1248008337
