### ISSUE TITLE
Installation errors installing

### ISSUE THREAD

**Issue by Stormthirst** [PodcastGenerator/PodcastGenerator#695]
**System Information**
Podcast Generator Version: 3.2.7
Webserver: Apache 2 on Linux
PHP Version: 
php -v
PHP 8.1.2 (cli) (built: Aug  8 2022 07:28:23) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.2, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.2, Copyright (c), by Zend Technologies

Config incomplete as the server 500's on step 2

**How to reproduce**
I've attempted to reinstall and it's still not helped

**Comment by coldacid** [comment]
Can you check the PHP and web server error logs? That it simply 500s on you doesn't give me enough information to figure out the problem.

**Comment by Stormthirst** [comment]
[Thu Oct 06 08:39:28.786616 2022] [php:error] [pid 1080933] [client 192.168.2.47:58899] PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /home/andrew/public_html/Beau/setup/step2.php:30\nStack trace:\n#0 /home/andrew/public_html/Beau/setup/step2.php(30): fwrite()\n#1 {main}\n  thrown in /home/andrew/public_html/Beau/setup/step2.php on line 30, referer: http://dios/~andrew/Beau/setup/step1.php

**Comment by coldacid** [comment]
Looks like the media or images directory may not exist, or that the directories don't have permissions set up that allow the web server (or PHP "user") to create files in them. This definitely needs to be handled better in step2.php but the root issue is the file system on your web host.

For Podcast Generator to work properly, there needs to be a media/ directory and an images/ directory in the same directory as index.php and both of those directories, along with the directory containing index.php, need to be "writable" by the web server. The code in step2.php that is crashing is the code which tests if the directories can be written to.

**Comment by Stormthirst** [comment]
I've set all the files and directories in there to 777, and media and images directories exist. No change. In both images and media there is a test.txt file created by the webserver, judging by the file permissions.

[Sat Oct 08 20:51:09.054584 2022] [php:error] [pid 1163417] [client 192.168.2.47:62697] PHP Fatal error:  Uncaught TypeError: fwrite(): Argument #1 ($stream) must be of type resource, bool given in /home/andrew/public_html/Beau/setup/step2.php:40\nStack trace:\n#0 /home/andrew/public_html/Beau/setup/step2.php(40): fwrite()\n#1 {main}\n  thrown in /home/andrew/public_html/Beau/setup/step2.php on line 40, referer: http://dios/~andrew/Beau/setup/step1.php

**Comment by Stormthirst** [comment]
Scratch that - the root directory (in this case "Beau") wasn't writable, even though the subdirectories were.

Installation complete!

**Comment by coldacid** [comment]
Yeah, I'm going to make this a bit more obvious with some changes to step2.php. At the very least, hovering over the directory "names" on the page should show a tooltip with the actual path of the directory being tested or permission-set.
