### ISSUE TITLE
Podcast Generator 3.2.7 - Internal Server Error

### ISSUE THREAD

**Issue by gravas68** [PodcastGenerator/PodcastGenerator#705]
**System Information**
Podcast Generator Version: Podcast Generator 3.2.7
Webserver:  UK2.NET
    Apache Version | 2.4.54
    PHP Version | 8.1.11
    Architecture | x86_64
    Operating System | linux
    Perl Version | 5.16.3

Upgraded to Podcast Generator 3.2.7. from 3.1

Windows 7 Pro - FileZilla 3.60.2 for the ftp.

On the Admin section, clicking View Podcast results in an error:

Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@bethanyec.co.uk to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

I did not do anything different from previous upgrades.

**Podcast Generator Config**

```
<?php

$podcastgen_version = '3.2.7'; // Version

$first_installation = 1598200827;

CENSORED installationKey

$scriptlang = 'en_US';

CENSORED url

$absoluteurl = '/home/bethanye/public_html/PodcastGenerator-3.1/PodcastGenerator/'; // The location on the server

$theme_path = 'themes/default/';

$upload_dir = 'media/'; // 'media/' the default folder (Trailing slash required). Set chmod 755

$img_dir = 'images/'; // (Trailing slash required). Set chmod 755

$feed_dir = ''; // Where to create feed.xml (empty value = root directory). Set chmod 755

$max_recent = all; // How many file to show in the home page

$recent_episode_in_feed = 'All'; // How many file to show in the XML feed (1,2,5 etc.. or 'All')

$episodeperpage = 10;

$enablestreaming = 'yes'; // Enable mp3 streaming? ('yes' or 'no')

$freebox = 'yes'; // enable freely customizable box

$enablepgnewsinadmin = 'yes';

$strictfilenamepolicy = 'no'; // strictly rename files (just characters A to Z and numbers) 

$categoriesenabled = 'yes';

$cronAutoIndex = 1; //Auto Index New Episodes via Cron

$cronAutoRegenerateRSS = 1; //Auto regenerate RSS via Cron

$indexfile = 'index.php';    // Path of the index file

$podcastPassword = '';       // Password to protect the podcast generator webpages, this will NOT protect the audio or XML files. Leave blank to disable.

$customtagsenabled = 'no';   // Advanced functionality for custom RSS tag input

$timezone = '';              // Timezone used for displaying dates and times

#####################

# XML Feed stuff

$podcast_guid = ''; // Globally unique identifier for your podcast

CENSORED podcast_title

CENSORED podcast_subtitle

CENSORED podcast_description

$podcast_cover = 'folder.png';

CENSORED author_name

CENSORED author_email

# The e-mail of the technical admin of the podcast

$webmaster = 'info@bethanyec.co.uk';

$itunes_category[0] = 'Religion & Spirituality'; // iTunes categories (mainCategory:subcategory)

$itunes_category[1] = 'Religion & Spirituality:Christianity';

$itunes_category[2] = '';

$link = '?name='; // permalink URL of single episode (appears in the <link> and <guid> tags in the feed)

$feed_language = 'en';

$feed_sort = 'timestamp'; // sort method used to order episodes in the feed (by timestamp or by season/episode number)

$feed_locked = ''; // podcast:locked status ('yes', 'no', '' for off)

CENSORED copyright

$feed_encoding = 'utf-8';

CENSORED explicit_podcast

$users_json = '{"bethanyec": "$2y$10$TcsFD3qXXQwavCVx/TSTNOzOtpdh3PwrJRd0Cv34QBCeNC7zhZFPK"}';

#####################

# WebSub

$websub_server = '';

#####################

# Podcast Index

$pi_api_key = '';

$pi_api_secret = '';

$pi_podcast_id = 0; // is the podcast in Podcast Index? This is its show ID there.

// END OF CONFIG




``` 

**Description of your problem:**

**Comment by coldacid** [comment]
Could you provide the server PHP error log?

**Comment by gravas68** [comment]
Thank you for responding.  I am not technical.  Where would the PHP error log be stored?  I use UK2.net for webhosting.  Will this be part of the Control Panel setting, or do I need to request the logs via UK2 support?

**Comment by gravas68** [comment]
I found these on the server folder (via Filezilla)  the dates are older then the ones on my backup file - taken of the whole directory before I updated.
[admin_error_log.txt](https://github.com/PodcastGenerator/PodcastGenerator/files/9858502/admin_error_log.txt)
[error_log.txt](https://github.com/PodcastGenerator/PodcastGenerator/files/9858503/error_log.txt)

**Comment by gravas68** [comment]
the error logs from my backup installation (3.1) the log files have a date of 23 October 2022.
[admin_error_log.txt](https://github.com/PodcastGenerator/PodcastGenerator/files/9858565/admin_error_log.txt)
[error_log.txt](https://github.com/PodcastGenerator/PodcastGenerator/files/9858568/error_log.txt)

**Comment by coldacid** [comment]
Unfortunately, from the logs provided, I can't determine what's gone wrong. The earlier (deleted) log files were from 2020 and 2021, predating 3.2.7, and the most recent log file is a server log by the look of things, not a PHP log, and is all failed requests for WordPress files. All I can suggest is upgrade to 3.2.9 when it comes out later today and see if the problem happens again.

**Comment by gravas68** [comment]
I have updated to 3.2.9 - no change, it seems the admin page is not generating the 'podcast' page - the one that allows the Freebox link to the full website.  When I mouseover the various options it does appear to have no link / destination.

**Comment by coldacid** [comment]
What's the URL of the particular admin page where this is happening and what exactly are you doing? Please provide specific directions so I can try and reproduce on my test site.

**Comment by gravas68** [comment]
Thank you for your help.


https://www.bethanyec.co.uk/PodcastGenerator-3.1/PodcastGenerator/admin/index.php

All of the functions of the admim login seem to work, apart from View Podcast. Where previously a page including the options in the Freebox, 

Now an error page is displayed.

https://www.bethanyec.co.uk/PodcastGenerator-3.1/PodcastGenerator/



Internal Server Error

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator at webmaster@bethanyec.co.uk to inform them of the time this error occurred, and the actions you performed just before this error.

More information about this error may be available in the server error log.

Additionally, a 500 Internal Server Error error was encountered while trying to use an ErrorDocument to handle the request.

**Comment by gravas68** [comment]
Our webspace provider UK2.net are not as helpful as they could be:

error log:

[Fri Nov 04 08:00:22.671151 2022] [:error] [pid 2566233:tid 47552906987264] [client 40.127.80.211:56606] File does not exist: /home/bethanye/public_html/xmlrpc.php
[Thu Nov 03 18:04:41.286878 2022] [:error] [pid 535193:tid 47552746047232] [client 86.3.227.51:57550] File does not exist: /home/bethanye/public_html/PodcastGenerator-3.1/PodcastGenerator/admin/freebox.php
[Thu Nov 03 18:03:47.936313 2022] [:error] [pid 535193:tid 47552783869696] [client 86.3.227.51:56796] File does not exist: /home/bethanye/public_html/PodcastGenerator-3.1/PodcastGenerator/admin/freebox.php
[Thu Nov 03 17:39:45.406590 2022] [:error] [pid 535076:tid 47552921696000] [client 86.3.227.51:33133] File does not exist: /home/bethanye/public_html/PodcastGenerator-3.1/PodcastGenerator/admin/tore_cover.php
[Thu Nov 03 17:31:23.039548 2022] [:error] [pid 488874:tid 47552800679680] [client 138.128.174.146:60962] File does not exist: /home/bethanye/public_html/wp-login.php
[Thu Nov 03 16:33:43.891635 2022] [:error] [pid 341451:tid 47552779667200] [client 86.3.227.51:35418] File does not exist: /home/bethanye/public_html/PodcastGenerator-3.1/PodcastGenerator/listepisodes.php
[Thu Nov 03 06:28:31.020114 2022] [:error] [pid 3825670:tid 47552894379776] [client 46.161.27.156:48154] File does not exist: /home/bethanye/public_html/wp-login.php
[Thu Nov 03 06:06:03.656315 2022] [:error] [pid 3751369:tid 47552888076032] [client 20.115.56.6:50445] File does not exist: /home/bethanye/public_html/xmlrpc.php

**Comment by coldacid** [comment]
I think that you have a broken installation. There _is no_ admin/tore_cover.php file certainly, but nowhere in the code (at least in the repo) is store_cover.php linked to as tore_cover.php without the S. In addition, the freebox admin page is admin/theme_freebox.php not admin/freebox.php. Lastly, listepisodes.php is in the themes/default directory, not the PG root directory.

Unfortunately there's nothing that I can do for you, as this does not appear to be a bug with Podcast Generator itself but rather the "physical" installation of PG on your website.

**Comment by gravas68** [comment]
Thank you again
I've checked the error log (from the server) to the physical locations of the files,  They appear to be where you indicated.  

/home/bethanye/public_html/PodcastGenerator-3.1/PodcastGenerator/admin/freebox.php
/home/bethanye/public_html/PodcastGenerator-3.1/PodcastGenerator/admin/tore_cover.php
/home/bethanye/public_html/PodcastGenerator-3.1/PodcastGenerator/listepisodes.php
/home/bethanye/public_html/wp-login.php
/home/bethanye/public_html/xmlrpc.php

https://www.bethanyec.co.uk/PodcastGenerator-3.1/PodcastGenerator/admin/theme_freebox.php
https://www.bethanyec.co.uk/PodcastGenerator-3.1/PodcastGenerator/admin/store_cover.php
https://www.bethanyec.co.uk/PodcastGenerator-3.1/PodcastGenerator/themes/default/listepisodes.php
??
??

 As you report, the log refers to tore_cover.php m which should be store_cover.php

**Comment by coldacid** [comment]
In that case, you might want to see different hosting because something is majorly screwed up with your hosting service.
