### ISSUE TITLE
Download button opens episode media in browser rather than downloads the episode

### ISSUE THREAD

**Issue by coldacid** [PodcastGenerator/PodcastGenerator#714]
### Discussed in https://github.com/PodcastGenerator/PodcastGenerator/discussions/712

<div type='discussions-op-text'>

<sup>Originally posted by **gj2355** October 27, 2022</sup>
Hello,

Loving the latest version of PodcastGenerator

One thing I have found is that when I click the download button the podcast plays. It doesn't download. I've tried different browsers with the same result.

Is that because it's my own podcast, and perhaps it will download for a visitor? Or have I done something wrong? 

Thanks</div>

**Comment by gj2355** [comment]
Someone suggested it might be a PHP problem so I contacted my ISP. Their reply....

your download button is "a download call script". The function "download" acts only as a button to open/play the file. So you have to create a script to the "call to action" button to assign a task that would download, and this is scripting, not php.ini settings.
