### ISSUE TITLE
Podcast 3.2.8 | "Upload new episode" not working

### ISSUE THREAD

**Issue by GaneshKandu** [PodcastGenerator/PodcastGenerator#721]
#### after debug I found issue in episodes.php file.

https://github.com/PodcastGenerator/PodcastGenerator/blob/da939beaed9d347d87f3ef5f645f5f9c5044318d/PodcastGenerator/core/episodes.php#L405-L418

#### Seems issue is fixed in master.

https://github.com/PodcastGenerator/PodcastGenerator/blob/92089cf85a11ff883ad621e6ce6c554074f93305/PodcastGenerator/core/episodes.php#L543-L556

#### Please release it with fix.

**Comment by coldacid** [comment]
Fixed in 3.2.9
