### ISSUE TITLE
Fatal error:  Uncaught Error: Class "PodcastGenerator\\Configuration" not found

### ISSUE THREAD

**Issue by prolibre** [PodcastGenerator/PodcastGenerator#724]
**System Information** Debian
Podcast Generator Version: 3.2.9
Webserver: Apache
PHP Version: 8.1

Fatal error after update (old version 3.2.7)
The update does not work for me (all files are overwritten).

Error in log : 

`[Fri Nov 11 12:59:49.000283 2022] [php:error] [pid 2176913] [client IP:65092] PHP Fatal error:  Uncaught Error: Class "PodcastGenerator\\Configuration" not found in /DIRECTORY_INSTALL/core/include.php:17\nStack trace:\n#0 /DIRECTORY_INSTALL/index.php(12): require()\n#1 {main}\n  thrown in /DIRECTORY_INSTALL/podcast/core/include.php on line 17`

Thanks in advance.

**Comment by prolibre** [comment]
Bad download version

**Comment by coldacid** [comment]
You're not the only person who seems to have had this problem. Where did you grab the bad download from?

**Comment by prolibre** [comment]
> You're not the only person who seems to have had this problem. Where did you grab the bad download from?

I had trouble finding the download link (http://podcastgenerator.net/download leads to the blog).  I think I downloaded the "master" directly from github. 
Have a nice day.

**Comment by coldacid** [comment]
That'd do it, yeah. Thanks for letting me know.
