### ISSUE TITLE
Can't login after setup

### ISSUE THREAD

**Issue by moemueller** [PodcastGenerator/PodcastGenerator#726]
**System Information**
Podcast Generator Version: 3.2.9
Webserver: dogado.de
PHP Version: 8.1

**Expected behavior**

Login with correct credentials

**Actual behavior**
 
I can't login with the right credentials.

**How to reproduce**

I have changed my webhoster and before that I tested it on another domain on the new webhoster, it worked there perfectly. When I copied that successful installation to the different domain and I got a http 500 error. 
I wanted to do a clean setup before I implement my current feed, which is from a way older PodcastGenerator Version.
I copied the files from PodcastGenerator folder to the ftp and run the setup. After I entered the username and password + confirmation, the setup finished, but I can't login to the admin area. (No error messages, the inputs only clear themselves after I press "Loing") I tried to reset the password with the reset.php file, didn't work. I have tried it multiple times and run the setup again and again, no change. Sometimes I still get a http 500 error after the setup. The two different domains are equally set up with php 8.2.
Thanks for the help!

**Comment by moemueller** [comment]
Error Log (last two logs):

*PATH* = Domain
podcastfeed is the renamed folder of PodcastGenerator

Tue Nov 22 23:01:46.269468 2022] [proxy_fcgi:error] [pid 2830884:tid 140341520680704] [client 93.234.80.47:6108] AH01071: Got error 'PHP message: PHP Warning:  session_start(): open(/tmp/sess_8d8e83957f2beb234dec506754f22ca6, O_RDWR) failed: No such file or directory (2) in *PATH*/podcastfeed/admin/checkLogin.php on line 10PHP message: PHP Warning:  session_start(): Failed to read session data: files (path: /tmp) in *PATH*/podcastfeed/admin/checkLogin.php on line 10', referer: *PATH*/podcastfeed/admin/login.php?login=1
[Tue Nov 22 23:01:46.327157 2022] [proxy_fcgi:error] [pid 2830884:tid 140341856388864] [client 93.234.80.47:6120] AH01071: Got error 'PHP message: PHP Warning:  session_start(): open(/tmp/sess_8d8e83957f2beb234dec506754f22ca6, O_RDWR) failed: No such file or directory (2) in *PATH*/podcastfeed/admin/login.php on line 10PHP message: PHP Warning:  session_start(): Failed to read session data: files (path: /tmp) in *PATH*/podcastfeed/admin/login.php on line 10', referer: *PATH*/podcastfeed/admin/login.php?login=1

**Comment by coldacid** [comment]
First, try clearing your browser cookies, it looks like it might be trying to hold onto an old session. Second, you need to check with your new host if the `/tmp` directory is fully accessible to the web server or PHP process as this is required for PHP session management to function properly.

**Comment by moemueller** [comment]
After reinstalling multiple times it worked, even when I received an error after the setup.
I'm not sure what the problem was. /tmp was fully accessible, PHP worked fine. 
Thank you for the suggestions. This can be closed.
