### ISSUE TITLE
Documentation/Wiki

### ISSUE THREAD

**Issue by jbenz** [PodcastGenerator/PodcastGenerator#732]
Previously there was helpful documentation regarding install, upgrade, and other issues/concerns. On my last visit to the new website those pages were no where to be found. Not sure if there is any plan to bring those over to github or another doc platform. 

I'd be willing to offer assistance in moving those pages over and/or updating docs as needed if there is a need.

**Comment by coldacid** [comment]
I'll look into this as we migrate to a new platform for the website.

**Comment by SamiChab** [comment]
@coldacid any update on this ?
