### ISSUE TITLE
Categories pages have errors

### ISSUE THREAD

**Issue by NeaMitika** [PodcastGenerator/PodcastGenerator#735]
Hi, i started to code a new theme and i have arrived at the "Categories" and on the the default theme it gives me some errors , here screenshots:
![image](https://user-images.githubusercontent.com/59248866/209411047-49a9a4ce-0a5a-4964-90fc-5a83dc2eae9e.png)
![image](https://user-images.githubusercontent.com/59248866/209411060-7fa3a14f-dfe7-4196-aa67-3b04dc7438e4.png)

I am noticing that there is a lot of new code on the upcoming version, i was wondering if maybe the structure of the theme could change so it easier to create them...

Something like wordpress does (but not strictly)

- index.php
- categories.php
- search.php
- single-episode.php 

and so on...

I tried to do so on my code 
![image](https://user-images.githubusercontent.com/59248866/209411225-a7444629-07f2-4b6e-bc56-a2e181b0d44e.png)
And inside the index i did something like this

`    <main>

        <?php
            // IF name was passed, do this instead
            if (isset($_GET[$link])) {

                include 'single-episode.php';

            } elseif (isset($_GET['search'])) {

                // results page 
                include 'results-page.php';

            } elseif (isset($_GET["cat"])) {

                include 'categories.php';

            } else{
                
                include 'last-episode.php';

                include 'latest-episodes.php';

                include 'all-episodes.php';

            }
        ?>

    </main>`

but the categories page not only gives me errors in the default theme and on my theme too but its structured differently and i cant simply include it... 

:)

**Comment by coldacid** [comment]
Changing how themes work would be a breaking change and so wouldn't happen until 4.0.

Please create a new issue with specific details for the category page errors and warnings, and please include details such as PG version and PHP version and sanitized configuration.
